### ISSUE TITLE
request : ventrilo server status

### ISSUE THREAD

**Issue by jeroenvheel** [Austinb/GameQ#1]
can you implement ventrilo status

**Comment by Austinb** [comment]
Which version?  Currently in the process of adding a bunch of stuff to v2.

**Comment by jeroenvheel** [comment]
i'm working with the latest ventrilo version 3.0.3

**Comment by Austinb** [comment]
Sorry.  I meant are you using v1 or v2 of the GameQ library?  Version 1 should have ventrilo support.  I have not gotten that far with v2 yet.

**Comment by jeroenvheel** [comment]
V2

**Comment by Austinb** [comment]
Ok I have it slated to be added with Teamspeak 3
