### ISSUE TITLE
cube 2 sauerbraten redeclipse

### ISSUE THREAD

**Issue by Poil** [Austinb/GameQ#101]
Hi,

I've tried to convert the class from the original GameQ code but I'm too bad.
It'll be cool if you can add this protocol :)

Best regards

**Comment by Austinb** [comment]
Do you have a server up that this code can be tested against?  If so please provide more information.

**Comment by Poil** [comment]
Hi,

I have a redeclipse server : game.quakelive.fr
Listen port 28801
Query port 28802

Ty

**Comment by Austinb** [comment]
I have a email out to one of the developers.  I was unable to find any information about the protocol and it has changed from cube 1 so that is why your attempts probably failed.  Hopefully I will be able to add this soon.

If you or anyone else has any more info on the protocol structure let me know.

**Comment by Poil** [comment]
Hi,

I can query my serveur with qstat, more infos https://qstat.svn.sourceforge.net/svnroot/qstat/trunk/qstat2/cube2.c https://qstat.svn.sourceforge.net/svnroot/qstat/trunk/qstat2/cube2.h
With the original gameQ I used protocol sauerbraten (from sauerbraten.php)

Thanks =)

**Comment by Austinb** [comment]
Please check out the latest code and let me know if you have any issues.

**Comment by Poil** [comment]
Hi,

gq_hostname is not working
gq_maxplayers is a random  ? (on my server it's 16)
gq_numplayers and gq_online are correct 

I will check if I can fix this I've some holiday this week.

Thanks for your job

**Comment by Poil** [comment]
Your value in gq_maxplayers is the time to "round end" in second ! 

I think there is a missing "field" I've add a var_dump to http://web.quakelive.fr/GameQ/examples/redeclipse.php

Feel free to check

This is better but not optimal (what is uuu xxx zzz ...)

```
        // NOTE: the following items were figured out using some source and trial and error
        $result->add('num_players', $this->readInt($buf));
        $result->add('version', $this->readInt($buf));
        $result->add('protocol', $this->readInt($buf));
        $result->add('mastermode', $this->readInt($buf));
        $result->add('mutator', $this->readInt($buf));
        $result->add('time_remaining', $this->readInt($buf));
        $result->add('max_players', $this->readInt($buf));
        $result->add('uuu', $this->readInt($buf));
        $result->add('xxx', $this->readInt($buf));
        $result->add('zzz', $this->readInt($buf));

        // @todo: Sometimes there is an extra char here before the map string.  Not sure what causes it or how
        // to even check for its existance.

        $result->add('map', $buf->readString());
        $result->add('servername', $buf->readString());
```

**Comment by Austinb** [comment]
I am unable to figure out how many of those items exists before the strings of map name.  When I tested some other servers they had fewer settings, some had more.  Since this is beta I pushed up work I had done so I could get some feedback.  I will see if I can figure out where the number of items is defined.  Or I will have to do some kind of loop and break when a string is detected.

So that code you have there is correct for your server in terms of settings?  I noticed there was a mode and mastermode (mm) when I was using some windows based server browser for the game to find game servers to test against.

**Comment by Poil** [comment]
I'm looking this, perhaps this can help us
http://redflare.ofthings.net/ 
https://github.com/stainsby/redflare/blob/master/lib/protocol.js

And this code in C seem to be clear
http://sourceforge.net/projects/cubestat/

**Comment by Austinb** [comment]
Ok so it seems that cube 2 sauerbraten redeclipse is different from just plain cube 2 sauerbraten, is this the case?  When I checked that link of servers on redflare I was able to more easily figure out where things should end.  For the regular cube 2 sauerbraten the result from the query is very different. Also the version number seems to be higher, redclipse servers are version 220 and sauerbraten are versions 259-263.  I guess there is a fork of the game server being used for redclipse that is older?

I was able to do more work but it appears that the query responses are very different between the 2 different games (with similar names).  Can you provide any more information?

**Comment by Poil** [comment]
Hi,

Sorry I have no more information :/

It seem to work really fine now for RedEclipse, thanks for your great job! I

**Comment by Austinb** [comment]
Well as it stands now cube2 seems to work fine and redeclipse is working as well.  If you have any specific issues or bugs with the protocol please open up a new issue.
