### ISSUE TITLE
[Request] Red Orchestra 2

### ISSUE THREAD

**Issue by sebkacz** [Austinb/GameQ#102]
Red Orchestra 2 is based off Unreal Engine 3, and querying the server responds 50% of the time, but doesn't show any data apart from the server being online, ip address and port number.

When running it with ut3 selected, it returns this error:

[Wed Apr 10 21:28:05 2013] [error] [client fe80::2a37:37ff:fe13:b539] PHP Fatal error:  Uncaught exception 'GameQ_ProtocolsException' with message 'Unable to read length={$length} from buffer.  Bad protocol format or return?' in /Library/WebServer/Documents/gameq/buffer.php:106\nStack trace:\n#0 /Library/WebServer/Documents/gameq/buffer.php(282): GameQ_Buffer->read(2)\n#1 /Library/WebServer/Documents/gameq/protocols/gamespy3.php(127): GameQ_Buffer->readInt16()\n#2 /Library/WebServer/Documents/gameq/protocols/gamespy3.php(199): GameQ_Protocols_Gamespy3->preProcess_all(Array)\n#3 [internal function]: GameQ_Protocols_Gamespy3->process_all()\n#4 /Library/WebServer/Documents/gameq/protocols/core.php(547): call_user_func_array(Array, Array)\n#5 /Library/WebServer/Documents/GameQ.php(476): GameQ_Protocols_Core->processResponse()\n#6 /Library/WebServer/Documents/GameQ.php(458): GameQ->filterResponse(Object(GameQ_Protocols_Gamespy3))\n#7 /Library/WebServer/Documents/example.php(15): GameQ->requestData()\n#8 {main}\n\nNext exception 'GameQException' with message 'Unable to read length={$length} from buffer.  Bad prot in /Library/WebServer/Documents/gameq/protocols/core.php on line 555

**Comment by Austinb** [comment]
My guess is something may be a bit different with the implementation of the GS3 protocol.  Each game that uses it implements it a bit differently it seems.  I have added this as a feature request.  Can you provide an ip:port to test against?  Thanks.
