### ISSUE TITLE
Add Arma 3 Support

### ISSUE THREAD

**Issue by firefly2442** [Austinb/GameQ#104]
I tried extending GameSpyv3 for Arma3 because I thought it would be similar to Arma 2 but it didn't seem to work.  It just isn't able to connect for some reason.  I was searching around online and came across this:

http://pastie.org/6101655

It's in Python but it appears to work and fetches the data.  Are you able to tell from this script and/or the results if they have deviated significantly from the GameSpyv3 protocol?  I know Arma 2 was a little off...

I'm just curious where to start if you think it's best to get it working with the existing GameSpyv3 protocol or if it would be better to just write it from scratch...

Thanks.

**Comment by Austinb** [comment]
Actually that script you linked to me handles both gs v3 & v2.   Since I assumed the script worked I tried some ArmA3 servers from gametracker using GSv2 for arma3 and it works fine.  Will push up the new class in a few.  Thanks for the info.
