### ISSUE TITLE
BF3 Server Doesnt query

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#105]
Im trying to query the following BF3 server and it always appears as offline.

IP: 82.96.119.126
Server Port: 25210
Query Port: 47210

On GameMonitor, it shows the server is up (http://www.gametracker.com/server_info/82.96.119.126:25210/)

**Comment by Austinb** [comment]
The following works for me:

``` php
gq = new GameQ();
$gq->addServer(array(
        //'id' => 1,
        'type' => 'bf3',
        'host' => '82.96.119.126:47210'

));
```

``` php
Array
(
    [82.96.119.126:47210] => Array
        (
            [country] => DE
            [dedicated] => 1
            [gametype] => TeamDeathMatch0
            [gq_address] => 82.96.119.126
            [gq_dedicated] => 1
            [gq_gametype] => TeamDeathMatch0
            [gq_hostname] => [BB] Gaming Servers | Noshahr Canals 24/7 | HC
            [gq_mapname] => MP_017
            [gq_maxplayers] => 16
            [gq_mod] => 
            [gq_numplayers] => rank
            .....
       )
)
```

**Comment by Ruok2bu** [comment]
I have the server query set up as:

$servers = array(
    array(
        'id' => 'BF3',
        'type' => 'bf3',
        'host' => '82.96.119.126:47210',
    )
);

And the server still shows up as offline.  I tried testing from 2 different locations and 2 different computers and the server shows up as offline in both locations (one of the computers doesnt have an outgoing firewall in place so query would work).

**Comment by Austinb** [comment]
My guess is either those ips are being blocked or the internal code has been modified.  I would try a clean clone of the v2 branch and try it out.  Let me know if it does not work.

**Comment by Ruok2bu** [comment]
: :o: 

It works.  Before i was just copying the new files over the old ones.  But first deleting the directory and copying the new files fixed it.

Thanks!

**Comment by Ruok2bu** [comment]
Any idea why it doesnt work on my web server though?  The web server doesnt have an outgoing firewall, yet BF3 as well as most DayZ servers appear offline all the time.

**Comment by Ruok2bu** [comment]
NM, my fault.  Firewall.  I was told it was disabled.  It wasnt.
