### ISSUE TITLE
GameQ randomly returning offline results.

### ISSUE THREAD

**Issue by dilgihon** [Austinb/GameQ#106]
The script is querying one server which runs about 9 game servers at once;
- 3 CS:S servers
- 2 Killing Floor servers (query port: 7708, 7710)
- 2 Minecraft servers
- 1 Terraria TShock server (Rest Api port: 5667)
- 1 GMod server 27055

Ever since I added Terraria TShock Server to the server list array, it keeps returning offline results for random servers, usually being the Killing Floor servers and the GMod server.
The servers are perfectly functional.

So Terraria TShock query is making all this mess since if I remove that server from the query list everything goes back to normal.
Changing the port does not make the difference nor does the timeout option.

**Comment by Austinb** [comment]
If you query the tshock server on its own does it work?  I am curious as to why it would be conflicting with the others.  If you can provide information to me via email for the servers so I can setup the same tests I would appreciate it.

**Comment by dilgihon** [comment]
What I had to do is create two instances of GameQ, one for all other games and the other for only Terraria servers (we just launched another Terraria server).
Also, Terraria server query does not return the maximum slot for players as well.

If you mean by if we only query the tshock server in one stance of GameQ, then yes it does work.

**Comment by Austinb** [comment]
Unless the API has changed there is no way to retrieve the current player count.  I set it to 0 so it would be defined. If they added more return keys I can add those pretty quickly.

I will try to test and see if I can find the conflict between the different types and tshock.  It is probably something to do with the headers being sent and causing some other issue.

**Comment by dilgihon** [comment]
Awesome.
Please keep me posted

**Comment by Austinb** [comment]
I did some quick testing and was unable to recreate the issue.  If you are still having the issue please reopen this ticket and private message me the list of servers you are using.  I would like to debug this but I have not had a lot of time to devote to this project over that last several months, my apologies.
