### ISSUE TITLE
Getting weird characters from hostname

### ISSUE THREAD

**Issue by plight** [Austinb/GameQ#108]
I am getting results back for hostname as ^1D^5eadz ^1Z^5one^9 

I have seen this happen on Quake 4 and COD game types.  Some work fine, others do not.  I do not see a common thread between the ones that work and those that do not.

Here is the server info from the example listed:    71.254.142.139:28004

**Comment by Austinb** [comment]
Most likely color codes in the host name.  Stripcolor filter may work.

**Comment by plight** [comment]
Thanks for the quick response!  

I added the filter via:  $gq->setFilter('normalise', 'stripcolor');

Is this the correct syntax for multiple filters? it does not appear to be working.

**Comment by Austinb** [comment]
No, setFilter() only allows one filter at a time.  The second argument is for possible parameters later, if needed.  You can chain calls though

```
$gq->setFilter('normalise')->setFilter('stripcolor');
```

Sorry for the really late response. Been super busy ;(
