### ISSUE TITLE
Empty players array for cssource server with password on!

### ISSUE THREAD

**Issue by deejayxb** [Austinb/GameQ#111]
Hello,

I have a small problem, for one of my cssource servers (a war server) the gameq returns empty players array. There are players on server and the numplayers is ok but the list of players is empty (see image)
This is a random issue, sometimes the array/list is empty, sometimes is ok..

![emptyarrayplayers](https://f.cloud.github.com/assets/4712079/659608/f659e0c4-d6a9-11e2-8cd1-a4793925cf85.jpg)

**Comment by Austinb** [comment]
Hmm I am wondering if this is expected behavior if the server is passworded (private).  I will have to test it a bit later.  Is that server still online so I can test against it?

**Comment by deejayxb** [comment]
Hi,

This bug happens also on my nonprivate (without password) servers

xb.gameforest.ro:27216
xb.gameforest.ro:27215

Both are online and sometimes the playername list is empty..

Thank You!
Dragos

**Comment by deejayxb** [comment]
![gameqbug](https://f.cloud.github.com/assets/4712079/790767/ab990994-eb2f-11e2-9e64-8e3f6e9aa7e7.jpg)

this is an image with some of my servers, the text in red explains the bug..

**Comment by deejayxb** [comment]
closed by mistake, reopened..

**Comment by Austinb** [comment]
I think this is a feature with the source protocol.  When the server is pass worded it does not return the player list via the public protocol. I just checked the raw response and the player response is empty. 

If you think about this it makes some sense.  I think valve did not want the player list to be public for a private server.  I am sure the player list can be retrieved via the rcon protocol for pass worded servers but GameQ does not have this support.

**Comment by deejayxb** [comment]
Hi

This issue happens also on public servers..
On private server does work but also sometimes player list is empty.. on public server the same..

Dragos

Austin Bischoff notifications@github.com wrote:

> I think this is a feature with the source protocol.  When the server is
> pass worded it does not return the player list via the public protocol.
> I just checked the raw response and the player response is empty. 
> 
> If you think about this it makes some sense.  I think valve did not
> want the player list to be public for a private server.  I am sure the
> player list can be retrieved via the rcon protocol for pass worded
> servers but GameQ does not have this support. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Austinb/GameQ/issues/111#issuecomment-28715644

Dragos Zarnescu

## 

Sent from my Note3 mobile.
