### ISSUE TITLE
Some Minecraft server's don't return results? (says offline, when server is active)

### ISSUE THREAD

**Issue by unenergizer** [Austinb/GameQ#115]
Hello,

I am creating a top-site using this library for Minecraft servers.  So far everything is going well.  However I have noticed that some MC servers won't return results.  For instance some servers come back as online and some servers come back as offline.

I have a cronjob that runs the script, it pings 1 server at a time (looping through a db), then updates the information in the database with new stats.  The database then displays it's list of results to the user with a simple serverList.php file that I have created.

All servers are fed to GameQ.php with IP:Port (regardless if using the default port).
The servers that are online, but don't respond, I have tested with including and excluding the port.  Some of these servers have domain names and some of them are IP address.

Example:
$gsip = 'play.everwither.net';
$gsPort = '25565';

//Lets call GameQ & send the server Info
$gq = new GameQ();
$gq->addServer(array(
    'id' => '',
    'type' => $gsType,
    'host' => $gs_IP,
));

Thank you for your help.  You can find servers to test this on MineStatus.net

**Comment by Austinb** [comment]
Are the servers' ports enabled? I know in minecraft you have to explicitly enable the server the respond to queries.  I can test a bit later.

**Comment by Austinb** [comment]
I tested your server and the server is coming back offline.  I did check the script against other public servers and it seems to be behaving properly. I believe Gamespy3 (which is what minecraft uses) returns nothing if there are no players on the server.  I remember something like this from before.  Please have someone join your server and re-query.
