### ISSUE TITLE
query port in array ?

### ISSUE THREAD

**Issue by Supryk** [Austinb/GameQ#118]
it pasible to add query port to array 2 i have 2 ts3 servers whit difrent port

**Comment by Austinb** [comment]
For each different server you will need to add a server entry.  So if you have two teamspeak servers on the same ip you will have to add the server twice, one for each port.

**Comment by Supryk** [comment]
I add server like that

[php]   $servers = Array
    (
        array(
            'type' => 'teamspeak3',
            'host' => '212.59.253.4',
            'slots' => '32'
        ),
    );[/php]

I have two servders an the servers has other master_server_port
1 = 10011
2= 21856
Can I put in array this port ?
[php]   $servers = Array
    (
        array(
            'type' => 'teamspeak3',
            'host' => '212.59.253.4',
                        'port' => '10011',
            'slots' => '32'
        ),
    );[/php]

**Comment by Supryk** [comment]
bump
