### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by matbcvo** [Austinb/GameQ#119]
Hello,

I want use this library on my web service. But there GameQ won't work. Which port on web service must be opened?

**Comment by Austinb** [comment]
I am unsure what you are trying to query.  To query a server the query port for that server must be open to query by GameQ.  If you are on the same physical machine you do not need to open the port.  As far as GameQ it just needs the ability to create ports to connect to the servers you want to query.  So if you have any outbound firewall restrictions you will have to relax these as GameQ uses any available outbound ports on the machine running the script.

**Comment by matbcvo** [comment]
Web service support said that UDP ports is blocked. They require correct port to open so GameQ would work. They wont open all UDP ports.

**Comment by Austinb** [comment]
Hmm well that is a problem.  The script does not have anyway to define a range of ports to use for making outbound connections to other servers to query.  Something like this would take time to add into the code and I haven't had much free time for this project over the last few months. I will have to look and see if there is an easy way to add something like this.

Just to clarify you are not talking about opening up ports for an actual game server but needing outbound ports for GameQ to be able to connect to other servers correct?

**Comment by matbcvo** [comment]
Yeah, correct. They just need an correct port (TCP or UDP?) to open, so GameQ can get data from gameservers.

**Comment by matbcvo** [comment]
Or how I can use GameQ without requiring port opened?
