### ISSUE TITLE
Change GameQException to an option & add sub-exception handling

### ISSUE THREAD

**Issue by Austinb** [Austinb/GameQ#12]
For multiple servers when trying to make a call and something fails it throws an exception and causes it to die where the error happens instead of continuing on.

Solution should be as follows:
1. Make throwing of GameQException optional (except where requirements are necessary i.e. php includes).
2. Make a secondary exception handler for just the protocol side of the GameQ system that can be caught internally (and externally) and will allow the server requestData loop to continue after setting the rest of the information from the throwing method as an empty array.   Name: GameQProtocolException

**Comment by gcphost** [comment]
I would like to see the exceptions not exit the app - if using gameq2 in a separate app, say within a while loop, and an exception is caught - the while loop is killed and the rest of the app wont run

**Comment by Austinb** [comment]
Make sure you have debug => false when running the application.  
- When debug is true and errors such as connection errors, host not found, etc... will cause the script to abort when the exception is thrown. 
- When debug is false when an exception is thrown in a protocol class (i.e. source, gamespy3, etc...) the exception is still thrown but the application catches the exception and doesn't allow it to bubble up.  However the data returned for the server that had the exception will be mostly empty and assumed offline.
- Anything within the main class or secondary classes (not GameQProtocol) such as missing dependencies or modules from php will still throw a fatal exception that will break the data loop. 

If you are having a specific issue where a GameQProtocolException is breaking the loop while debug is false please post a new issue with the exception information so I can go fix it.

**Comment by Austinb** [comment]
Everything here seems to be working properly.  If anyone has an issue specifically with errors and debug mode please open a new issue.
