### ISSUE TITLE
teamspeak3

### ISSUE THREAD

**Issue by matbcvo** [Austinb/GameQ#121]
Hello,

As you see.. http://s.staatus.eu/GameQ-2/examples/index.php
80.79.112.199:9987 (teamspeak) query is 10011.
http://www.gametracker.com/server_info/80.79.112.199:9987 (here it shows that server is online)
Why GameQ can't get data from my TeamSpeak 3 server?

$servers = array(
    array(
        'id' => '',
        'type' => 'teamspeak3',
        'host' => '80.79.112.199:10011',
    )
);

tried :9987 and :10011, still doesn't matter...

---

Well, sometimes works, like 10% chance that will get data.

**Comment by KostyaEsmukov** [comment]
You should cache query results. TS3 servers bans clients when they request information too often. They send error message in reply to the new connection until ban time expiration.

**Comment by matbcvo** [comment]
I built that way. Still GameQ is not stable, I think.
http://s.staatus.eu/index.php?page=servers
Sometimes all servers are offline. All servers data are requested every 5 minutes.

**Comment by Sitting-Duc** [comment]
I seem unable to retrieve data when using the teamspeak3 protocol as well.. I am not sure on the cause.

**Comment by Sitting-Duc** [comment]
Not really sure but I just tried using Prosinec's server instead of mine and it works fine :/ I will put down whatever issue I am having as server related most likely.
