### ISSUE TITLE
GameQ2 protocol problem

### ISSUE THREAD

**Issue by webkolo** [Austinb/GameQ#123]
Hey.

When i try to check teamspeak3 server response i get error in:
Warning: stream_select() [function.stream-select]: No stream arrays were passed in /GameQ.php on line 804

Server IP: 178.217.187.127:8500

Can u please check this error and give me some fix for this?
Sorry for my bad english.

Best regards,
webkolo.

**Comment by Hronici1** [comment]
Same with any Protocol

**Comment by Austinb** [comment]
I tested the protocol fine with 199.233.235.213:9987.  The master port which is usually 10011 needs to be accessible to outside connections.  I tried the server you provided and it does not connect.
