### ISSUE TITLE
Add support 7 days to die

### ISSUE THREAD

**Issue by Hronici1** [Austinb/GameQ#124]
Hi! Support GameQ 7 Days to Die. Defaut port: 25000

http://7daystodie.com/

**Comment by Austinb** [comment]
When the game comes out of alpha state I will be happy to spend the time on building a protocol class for the game.  Also I do not see any specs on a public query protocol so I will need this documentation as well.

**Comment by Hronici** [comment]
Out Alpha version Steam

**Comment by Austinb** [comment]
Do you have a server I can test against that is always running?

**Comment by Hronici** [comment]
I can give details of running servers or try to run a server on your PC, but I'm not sure it will. Sorry for the english, I'm from Russia.

**Comment by Hronici** [comment]
That config file server https://drive.google.com/file/d/0B4ePxLBQkSH4Yjg0am1jdTZsaFU/edit?usp=sharing

**Comment by Hronici** [comment]
What else can I help?

**Comment by Endimmion** [comment]
You can query a 7 Days To Die server with "source" protocol. The query port is the server port +1 (if the server run on port 25000, the query port is automatically 25001)

There is one bug, the player count is incorrect. It report often a player count more higher than the maxplayer limit.

If think the server might still count disconnected players or bots.

**Comment by Austinb** [comment]
Added in commit e267fc9cc496
