### ISSUE TITLE
Inconsistant warning: stream_select(): No stream arrays were passed in

### ISSUE THREAD

**Issue by ceribik** [Austinb/GameQ#128]
If you pass in the server details of a single server with an invalid port, then a warning is given:

stream_select(): No stream arrays were passed
    stream_select() in GameQ.php at line 805
    GameQ->sockets_listen() in GameQ.php at line 700
    GameQ->queryServerInfo() in GameQ.php at line 595

If you pass in multiple servers (valid or invalid), and at least one server is successfully connected to, then no warning is given.

**Comment by Austinb** [comment]
Does this happen with debug => false?

**Comment by ceribik** [comment]
Yep, that's correct.

With debug => true, I instead get:

Fatal error: Uncaught exception 'GameQException' with message 'GameQ::socket_open Error creating socket to server tcp://119.252.191.193:25507. Error: ' in /foo/GameQ.php:764 

Stack trace: #0 /foo/GameQ.php(685): GameQ->socket_open(Object(GameQ_Protocols_Bf4)) 
#1 /foo/GameQ.php(602): GameQ->queryServerInfo(Array) 
#2 /foo/GameQ.php(454): GameQ->requestMulti(Array) 
#3 /foo/test.php(49): GameQ->requestData() 
#4 {main} thrown in /foo/GameQ.php on line 764
