### ISSUE TITLE
ManiaPlanet games support

### ISSUE THREAD

**Issue by ToRRent1812** [Austinb/GameQ#133]
Hi, is there any chance to support TrackMania 2 and Shootmania in GameQ?

I know it's possible to get server data with Manialib/Web Services like here: http://www.maniaviewer.com/index.php?site=serverlist&titleId=2
But I don't want to use another library/framework to get server data from 2-3 games.

**Comment by Austinb** [comment]
As far as I can tell you must have an api key and access to query any information and must use a XML-RPC interface to make it happen.  Do you know of any other way to query these types of servers without requiring login information to access basic information about the server?

**Comment by ToRRent1812** [comment]
I found this http://www11.zippyshare.com/v/95359265/file.html
To get server name, players and map, server admin must put IP, port and SuperAdmin login/password.
