### ISSUE TITLE
battlefield 4 bug

### ISSUE THREAD

**Issue by kisakov** [Austinb/GameQ#134]
I have this warning with many bf4 servers "PHP Warning:  stream_select(): No stream arrays were passed in /GameQ.php on line 804".
And script working for 9 seconds. But I have a timeout - 3 seconds. $gq->setOption('timeout', 3);

**Comment by Austinb** [comment]
Check the ip:port of the server you are trying to access.  BF4 client and query ports are not the same.

**Comment by Austinb** [comment]
The warning you were seeing is related to #128 but that issue was a result of zero valid servers being passed.  Please shoot me the server information for the server you are trying to query.

**Comment by kisakov** [comment]
Thank you for quick response. For example i have a problem with 173.199.93.119:30030
I found this server in gametracker http://www.gametracker.com/server_info/173.199.93.119:30030
There is specific function in a code, where execution takes too long.
In GameQ.php file -  function queryServerInfo(Array $instances=NULL).
if(($socket = $this->socket_open($instance)) === FALSE) 

$this->socket_open($instance) - this takes to much time.
And after 9 seconds I receive the warning - "PHP Warning: stream_select(): No stream arrays were passed in /GameQ.php on line 804" 
And setOption('timeout', 3) doesn't work in this case.
With some another servers it works great =)

**Comment by kisakov** [comment]
with your last commits warning disappear. But execution takes too long with no result.

**Comment by kisakov** [comment]
About timeout. A think it was my fault. Because timeout work's for each request - not for all. 
Script with timeout 3 seconds work's 9 seconds. I decreased this argument and now it's ok.
For battlefield 4 script works longer than Counter-Strike 1.6 or Call of Duty 4. But it is not critical.
Thank you for your support of the library. And thank you for helping.

**Comment by Austinb** [comment]
Yea the timeout is for each server.  You can tweak the time between requests (the time the script will wait for a response) and shorten the time a little.  Also the game server's location from the server requesting the information will have a big effect on the speed.  I want to put some time into tweaking the speed to make it faster but I just do not have the free time currently.
