### ISSUE TITLE
question about player statistics

### ISSUE THREAD

**Issue by kisakov** [Austinb/GameQ#135]
Can I get a specific player statistics with GameQ lib?
For example if I know nickname and server ip:port. Can I get statistic for this player?
Or for example top players for concrete server?
Or I can only receive statistics about all the players at the moment?

**Comment by Austinb** [comment]
It depends on the game server. Most game servers do not provide a lot of player information via the open protocol ports.  Some provide more via a restricted access system but that is beyond the scope of this library.

I return all available information for every game supported to allow the users to use what they want. Chances are if the information is not being returned it is unavailable via the open protocol.  If there is a specific game you want to be added to the library please create a new issue with the game information and any server protocol information as well.

Feel free to reopen if you have any more questions.
