### ISSUE TITLE
DayZ Standalone

### ISSUE THREAD

**Issue by FV-Chris** [Austinb/GameQ#136]
The DayZ Standalone Servers work not with GameSpy.
It is possible to add DayZ Standalone to GameQ?

**Comment by Austinb** [comment]
The Arma 2 DayZ Mod has been renamed to dayzmod from dayz.  Dayz is now the standalone version of the Steam based game.

**Comment by FV-Chris** [comment]
Thx for the fast add, i have test it and i see no information from the Gameserver.
Here is the Link to our test site: http://wptest.evil-jokers.com/gsviewer/test.php

**Comment by Austinb** [comment]
I tested the ip:port in that file and it seems it does not work.  However when I query any server from http://www.gametracker.com/search/dayz/? using port 27016 it works as expected.

Are there any other mods or anything else installed or is this just a vanilla install? Also are the ports open to the public?

**Comment by FV-Chris** [comment]
The Server ist Hosted by Gameservers.com and i have only the Port 2302.
Gameservers.com has set our Gameserver automaticle in Gametracker: http://www.gametracker.com/server_info/195.122.135.147:2302/
We cant install any mods or addons.
*EDIT
I have tested another Server from Gameservers.com with the Port 27016 this works Perfekt but 2302 will not work.

*EDIT 2
Okay i have the Problem, by Servers with Join Port 2302 is the query 27017 by DayZ SA Servers from Gameservers.com
