### ISSUE TITLE
Create example of player name ping and score

### ISSUE THREAD

**Issue by oddball118** [Austinb/GameQ#138]
Can you create an example showing player names, ping and score. I just can't figure it out.  Thanks, great work.

**Comment by Austinb** [comment]
Can you provide the server information and the game type?

You can also print out the response and see the raw structure of the result.  Using the example on https://github.com/Austinb/GameQ/wiki/Usage-%26-Examples-v2

To reference the players array they are all under players.  To access them would look something like:

``` php
print_r($results['id|ip:port']['players']);
```

If there are 0 players that will return an empty array.  If you have any further questions please reopen this issue.

**Comment by oddball118** [comment]
That's what I thought but if I do this it shows no results:

<?php
// Include the main class file
require 'GameQ.php';

$servers = array(
    array(
        'id' => 'xxxxxxxxxxx',
        'type' => 'cod4',
        'host' => 'xxx.xxx.xxx.xxx:xxxxx',
    ),
);

// Init the class, only need this once
$gq = new GameQ(); // or $gq = GameQ::factory();
$gq->setOption('timeout', 5); // Seconds
$gq->setOption('debug', TRUE);
$gq->setFilter('normalise');
$gq->addServers($servers);

$results = $gq->requestData();
print_r($results['id|ip:port']['players']);

But if I do this I get back data:

<?php
// Include the main class file
require 'GameQ.php';

$servers = array(
    array(
        'id' => 'xxxxxxxxxxx',
        'type' => 'cod4',
        'host' => 'xxx.xxx.xxx.xxx:xxxxx',
    ),
);

// Init the class, only need this once
$gq = new GameQ(); // or $gq = GameQ::factory();
$gq->setOption('timeout', 5); // Seconds
$gq->setOption('debug', TRUE);
$gq->setFilter('normalise');
$gq->addServers($servers);

$results = $gq->requestData();
print_r($results);

**Comment by Austinb** [comment]
The key of 'id|ip:port' shown here

``` php
print_r($results['id|ip:port']['players']);
```

Has to be replaced with the value you pass in 'id' => xxxxxx when you add the server.  If no id is passed the key is the ip:port information of the server when added.

``` php
print_r($results['xxxxxx']['players']);
```

**Comment by oddball118** [comment]
Isn't the value set in the array above it?
