### ISSUE TITLE
Add Mumble support

### ISSUE THREAD

**Issue by skylord123** [Austinb/GameQ#139]
I need to query mumble servers with my system. 

I have an example server here: sithous.com:64738

I will try to stay on the server so you can test it.

**Comment by skylord123** [comment]
After viewing the mumble doc some more I found that GameTracker made a plugin for mumble that allows you to query it.
I then found another plugin that allows you to get data from the server. The source is here:
https://github.com/edmundask/MurmurQuery/blob/master/classes/MurmurQuery.php

and plugin list is here:
http://mumble.sourceforge.net/3rd_Party_Applications

I'm considering trying to get mumble to work myself. That way I can see how the system works. If you start on it just post here to let me know. Otherwise I will attempt it. I haven't bothered much with sockets and php so it will be new to me, but I will give it a shot if you aren't already working on it. If you are working on it I hope the files above help you out (although you probably already found them). :)

**Comment by Austinb** [comment]
Added in 7619cbe176
