### ISSUE TITLE
php 5.2 supported

### ISSUE THREAD

**Issue by gcphost** [Austinb/GameQ#14]
hi again 2 questions here

1) php 5.2 is now working ok - the site says requires 5.3 still - any plan to change that?

2) do you have paypal donations setup?

**Comment by Austinb** [comment]
I have been unable to test it on php 5.2.  Once I have it working on a 5.2 version I will change the requirements.  Thanks for the update.

I will add a donate link soon.

-Austin

**Comment by gcphost** [comment]
thanks! donation sent :D

**Comment by Austinb** [comment]
I tested out a few different types of servers and it appears that 5.2.17 will work for v2.  If you find different please make a new issue and include the error information as well as the server you are trying to query.
