### ISSUE TITLE
Just cause 2 wont display names of players

### ISSUE THREAD

**Issue by skylord123** [Austinb/GameQ#144]
I did a test query of just cause 2. It returns the player list, but only shows the time for each player. You have no idea what name of each player is. 

Curious if this is a bug or just doesn't return player names. On the jc2mp website you can click servers and it shows the player names so I think this is a bug.

**Comment by Austinb** [comment]
I need a public server to test against.  Every server I have found is private meaning the player list is not returned. This is a source issue not a GameQ one.

**Comment by skylord123** [comment]
None of the servers on their website are public?

http://www.jc-mp.com/servers/

If the server was private wouldn't it not return any players at all (not just names, but playtime as well)?
It's strange how the jc-mp website can query the players just fine (except for the server with a ton of players >= 400).

**Comment by Austinb** [comment]
Yea it says I need an account to see that list.  I was looking on Gametracker which all appear to be passworded. 

I believe in Source if a server is private (passworded) it will not return any player information, just the number of players it has.

**Comment by skylord123** [comment]
This server has over 100 people online right now and lists players on their website:
178.33.164.69:7777

I did some more testing on their site. There are a couple that do fail to query, so I get what you mean. Try the one above and let me know. 

Thanks for getting back to me.

**Comment by skylord123** [comment]
Yeah, I just logged in using steam to get the list. That server I just listed should work for testing.

**Comment by Austinb** [comment]
Thanks.  Will test now and get back to you.

**Comment by skylord123** [comment]
Also, just tested this server and I got an error from gameq:
162.243.5.83:7777

Error:
ContextErrorException: Notice: Undefined index: map in /var/www/{REMOVED}/vendor/austinb/gameq/gameq/protocols/jc2.php line 35

**Comment by Austinb** [comment]
Yea I just fixed that bug and some others with jc2 and pushed them up.  Pull down.

**Comment by Austinb** [comment]
It appears the server you sent me (and others) are not returning the player name information in the response.  I checked the raw response and the position in the response where the name should be as defined by the source spec is empty.  My guess is other systems are using the OGP protocol to get the information.  

But I did find this thread http://www.jc-mp.com/forums/index.php?topic=2836.0 where they are shifting to gamespy4 to fix their issues. So hopefully this will come out soon.

**Comment by skylord123** [comment]
Yeah, that last issue was fixed. Sorry about that. Still having the first issue.

**Comment by Austinb** [comment]
I will see if I can squeeze some time in to change over to the OGP system they are using for the time being.

**Comment by skylord123** [comment]
Sounds good. I will keep posted on this for more information.

Thanks for the information and support!

**Comment by skylord123** [comment]
If I revert the version checker and lambda functions will it be okay? I can
also set the php version to something else.

Also if there is anything else you want me to remove/change let me know. I
originally wanted the getProtocols function because I needed it, but then
decided to contribute as well.

Just let me know what needs to be changed to be acceptable.

**Comment by Austinb** [comment]
If someone can provide a couple of servers with players in here I would appreciate it.  Trying to login to the JC2MP site with my steam info is giving me some kind of odd error.  Thanks.

**Comment by Austinb** [comment]
I do not have this game nor do I have access to it.  I few servers with players so I can test the new protocol against the server.  Thanks.

**Comment by rststeam** [comment]
Players:    123 / 1000
Host:   192.95.54.13:7777

Players:    60 / 500
Host:   195.138.78.198:7777

Players:    116 / 1000
Host:   37.157.247.35:7777

Here you go.

**Comment by Austinb** [comment]
Thanks, push coming.  Finally got some time to test this.
