### ISSUE TITLE
BF1942 and BF2 queries fail

### ISSUE THREAD

**Issue by skylord123** [Austinb/GameQ#146]
I think it may have to do with gamespy3. I tried querying servers from gametracker.com no matter how many users, they all come up as offline.

I can't seem to get killingfloor servers to respond either. The timeout is set to 5 seconds. Any ideas?

EDIT: Crysis doesn't work either. It uses gamespy 3 as well.

EDIT2: AA (america's army) doesn't seem to work either using gamespy2.

**Comment by Austinb** [comment]
Need the connection information.  All these games have one thing in common, they all use different query ports than the actual client connect port.

**Comment by Austinb** [comment]
If you have further information please open this issue back up.
