### ISSUE TITLE
wrong player details for CS16

### ISSUE THREAD

**Issue by Geeknux** [Austinb/GameQ#147]
Hi, i tried on many different server that using cs16, i try to get player kills, deaths, etc... but GameQ result for gq_kills is "false", gq_deaths eq false
why? is is a bug or something?

**Comment by Austinb** [comment]
Probably a bug with normalize.  I will check as soon as I have time.

**Comment by Austinb** [comment]
Actually the steam response does not return kills/deaths in the traditional sense.  The score key is what you are looking for.  This varies between games. See https://developer.valvesoftware.com/wiki/Server_queries#Response_Format_2
