### ISSUE TITLE
Players array building incorrectly A2:OA

### ISSUE THREAD

**Issue by Verox-** [Austinb/GameQ#149]
The players array does not build correctly, either normalized or not.
https://gist.github.com/Veroxa/360384edfe0280c1813d

Player names are definatly being pulled from the server except they are being outputted directly to the results array resulting in entries like 'Player1' => 'Player2' ect.

This also occurs when using the gamespy3 protocol.
Testing server: 70.42.74.59:2302
http://forums.unitedoperations.net/uosim/GameQ/examples/

**Comment by Austinb** [comment]
I am aware of an issue in A2:OA that returns info the breaks the Gamespy 3 protocol standard. This causes all kinds of odd behavior.  I have it on my todo list but no time currently.

**Comment by Verox-** [comment]
This is no longer an issue as Arma 2 no longer uses the Gamespy protocol.
