### ISSUE TITLE
Minecraft queries

### ISSUE THREAD

**Issue by Austinb** [Austinb/GameQ#15]
It seems that the plugin from minequery is not stable.  Need to take a look at implementing something like https://github.com/xPaw/PHP-Minecraft-Query which uses a more "traditional" method of gathering server information.

**Comment by AmkCity** [comment]
Minequery.jar 
This plugin works well and is stable on most servers.
http://dev.bukkit.org/server-mods/minequery/

**Comment by Austinb** [comment]
Version 2 already supports Minequery: https://github.com/Austinb/GameQ/wiki/Supported-servers-list-v2  The issue currently is it seems to not be stable enough nor does it provide as much information as the other link above (https://github.com/xPaw/PHP-Minecraft-Query). This requires something to be running as well but appears it is built into the actual minequery server.

**Comment by AmkCity** [comment]
I'm sorry, did not realize that minequery - this is minecraft query

**Comment by AmkCity** [comment]
type: minequery
Fatal error: Cannot instantiate abstract class GameQ_Protocols_Minequery in C:\xampp\htdocs\amursk-portal.ru\game_stats\GameQ.php on line 340

**Comment by Austinb** [comment]
I think minequery was written to not be called directly.  Try Minecraft.  I will remove the abstract when I make minecraft query work, might be able to get to it today.

**Comment by Austinb** [comment]
Turns out that Minecraft has built in gs4 (gamespy 3) handling.  I just pushed up the changes for this but it seems like GitHub is lagging a bit.
