### ISSUE TITLE
Rust Returns no data.

### ISSUE THREAD

**Issue by GavoTrav** [Austinb/GameQ#152]
Rust implemented a Server Query port today under the same as source servers.

http://facepunch.com/showthread.php?t=1344705

Currently returns;
Array ( [my_server] => Array ( [gq_online] => [gq_address] => 123.123.123.123 [gq_port] => _PORT_ [gq_protocol] => source [gq_type] => rust [gq_transport] => udp [gq_joinlink] => steam://connect/server.playrust.me:23805/ ) )

**Comment by ghost** [comment]
I'm having this same issue too.

**Comment by Austinb** [comment]
Rust (A2S) - Server query port is server port+1
