### ISSUE TITLE
Rust - Multiplay - No data

### ISSUE THREAD

**Issue by ghost** [Austinb/GameQ#154]
Hello,

Some servers that are hosted with Multiplay are showing no data on the return. Could you please take a look at this?

**Comment by GavoTrav** [comment]
Same as this, https://github.com/Austinb/GameQ/issues/152

Its not only Multiplay i've tried a bunch of servers that werent even mine and they still show nothing.

**Comment by Austinb** [comment]
Rust (A2S) - Server query port is server port+1
