### ISSUE TITLE
Shared Hosting - Won't ping anything

### ISSUE THREAD

**Issue by mckooter** [Austinb/GameQ#155]
I tried ripping through the code a bit but couldn't find it. I have several hosts, but the one I want to use this on won't work at all. I upload the script and just goto the Examples page and everything times out? 

Is there anything special I need to contact the webhost to ensure that I have it turned on? 

I can always link one host to another but would rather see if im missing something dumb

**Comment by Kurounin** [comment]
Check with the host provider if they allow packets to be sent through the query ports of the specific game servers you are querying.

**Comment by Austinb** [comment]
You need to be able to ping outbound. Many service providers do not allow you to query outside host for security reasons, ddos mitigation, etc.  You will have to contact your provider you are trying to use and see if they have any solutions. If not you will have to find another server provider. 

Also check the minimum requirements against what is built on the server.
