### ISSUE TITLE
JC2MP Player Count Not Reporting Properly (Updated)

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#156]
The fields gq_numplayers and gq_maxplayers are not reporting the actual player counts.  gq_numplayers is always 0 and gq_maxplayers is only the first 2 digits.

Can you fix it?

**Comment by Austinb** [comment]
Need a valid server to test against. It wont let me login to the JC2MP site via steam, getting some kind of error.  Please shoot me a list of a couple of servers to test this.

**Comment by Ruok2bu** [comment]
Here's the test im running against:

http://ftwgamer.com/test/examples/

The first JC2MP server is mine and its not showing the counts properly while the second JC2MP server is someone else's and its showing some of the counts properly (gq_maxplayers only shows 2 digits instead of the actual max slot count).

Also on that same example page, i have a Starbound server and the player list isint displaying either.

**Comment by Austinb** [comment]
Page does not exist.  Please use #144 for further updates.

**Comment by Ruok2bu** [comment]
Oops, i moved hosts and i forgot to move that folder, that's why it 404'd.  It's fixed now though.

http://ftwgamer.com/test/examples/
