### ISSUE TITLE
BF3 hostname weirdness

### ISSUE THREAD

**Issue by ghost** [Austinb/GameQ#160]
Gametracker shows

```
! ! ! !WWW.MB2.CZ
```

GameQ shows

```
! ! ! !^3WWW.^2MB2.^3CZ
```

**Comment by Austinb** [comment]
Try the color filter.  Those are old school color codes from the quake days.  I guess bf3 supports them as well.

**Comment by ghost** [comment]
I already use both filters

```
->setFilter('normalise')
->setFilter('stripcolor')
```

**Comment by Austinb** [comment]
Circling back on this, had little time the last month.

If you can provide the server ip:port and I can take a look at it.

**Comment by ghost** [comment]
213.168.176.170:30081
