### ISSUE TITLE
UT2004 problem

### ISSUE THREAD

**Issue by ghost** [Austinb/GameQ#162]
On some servers, i've noticed, that GameQ returns strange results, while Gametracker doesn't:

```
["g2.miasma.org:7778"]=>
    ["gq_mapname"]=>
        string(0) ""
    ["gq_numplayers"]=>
        string(2) "16"
    ["gq_maxplayers"]=>
        string(10) "1936609107"
    ["maxplayers"]=>
        string(10) "1936609107"
    ["ping"]=>
        string(10) "1735745900"
    ["playercount"]=>
        string(10) "1313804544"
```

Gametracker:

![mia](https://f.cloud.github.com/assets/5147647/2116143/19950f46-906d-11e3-9a09-f2cae07166ec.png)

**Comment by Austinb** [comment]
I am aware of bugs with very old query protocols, ut2004 is one of those.  Without more information and being able to connect to the server shown I cant really help.

**Comment by ghost** [comment]
This is the server: http://www.gametracker.com/server_info/185.16.84.4:7777
