### ISSUE TITLE
Archeblade

### ISSUE THREAD

**Issue by ghost** [Austinb/GameQ#163]
Archeblade is free to play and allows to host own servers.

See http://store.steampowered.com/app/207230/

Would be nice, if this could be added.

**Comment by ghost** [comment]
Reading the server is possible, as seen on http://www.game-monitor.com/archeblade_GameServer/184.172.24.42:11002/USDallas70-.html

**Comment by Austinb** [comment]
It seems to be using UT3 protocol on top of Gamespy3 but I need the port information.  Any documentation you can provide would be a great help to adding this game.

**Comment by ghost** [comment]
What exactly do you need? Maybe, a screen helps?

![screenshot 2014-03-05 16 15 13](https://f.cloud.github.com/assets/5147647/2334513/796e0240-a479-11e3-8ff3-254affd0dec4.png)

**Comment by Austinb** [comment]
What is the ip for that server in the screenshot?

**Comment by ghost** [comment]
- censored -

**Comment by Austinb** [comment]
So I was able to connect but the server is not returning any information.  I think the challenge and/or query packets are different from standard gamespy3.  I cant seem to find any information on the query protocol and that information is the best way to be able to add the game.

**Comment by ghost** [comment]
Is there anything i could do to help? Wireshark?

**Comment by ghost** [comment]
I could also try to set up a windows server and send you the login informations, so you could try it by yourself.

**Comment by Austinb** [comment]
Having a server online to test is the best thing.  I found something in the forums that said the protocol was unreal.  I am not sure that is correct.  May have to ask the game developer for information.

**Comment by ghost** [comment]
It was me, who asked there :P Because i'm very interested in this.

**Comment by Austinb** [comment]
Ahh ok.  Well if you can keep a server up and let me know the ip and query port I can trial and error it and see if I can figure it out.
