### ISSUE TITLE
Starbound dedection problem

### ISSUE THREAD

**Issue by TinCow** [Austinb/GameQ#165]
Starbound seems to be having issues.  We recently increased our player cap to 32 from 8.  The server was returning info fine before now.  The server worked fine up to 11 players, but at some point after that it stopped returning info and instead spits back Offline false/false.  However, the server is online and running fine and no settings have changed.  I'm not sure if a high player count actually impacted it or whether it was caused by something else, but it did stop reporting player count properly shortly after we increased our player cap, so it seems like that may be related.

If you'd like to test the server response, the Starbound server in question is running here:
95.211.218.224:21025

**Comment by Austinb** [comment]
Was there an update to the Starbound server package recently?

**Comment by BirknerAlex** [comment]
Yes, on 3. March at 11 PM (utc+1)

**Comment by Austinb** [comment]
It appears that 95.211.218.224:21025 is not giving me a response so I cant test it. I would suggest making sure your version is the latest and let me know if you are still having issues.

I pulled a couple of servers off of gametracker but only one had over 11 players and it seemed to work fine. 37.59.43.65:21025 had 13 at the time.

**Comment by TinCow** [comment]
Since I made the bug report, I've actually installed a server wrapper
(StarryPy) that may be impacting your tests.  The server wrapper itself
takes over port 21025, to intercept connections, and the Starbound server
itself is now running on port 21024.  If you are testing it on my server
(95.211.218.224), try using post 21024 as for your testing.

**Comment by Austinb** [comment]
I am not getting any kind of response from your server on either 21024 or 21025.

**Comment by Austinb** [comment]
Are you using anything like https://bitbucket.org/zvorgan/starrypy-server-status/ to allow querying to take place?  Its also possible StarryPy is mangling the response or something but I am not getting any response currently.

**Comment by TinCow** [comment]
No, I am not using anything other than default StarryPy.  StarryPy also
does not modify the Starbound server itself in any way, beyond requiring a
port change.

I've just rebooted both Starbound and StarryPy, see if that helps.

**Comment by Austinb** [comment]
I am still unable to get any response on either port at the ip 95.211.218.224.  Its possible there is a firewall blocking my requests.

**Comment by TinCow** [comment]
I actually cannot confirm that everything is working perfectly on the
server as I am at work and unable to actually connect to the server
in-game, however the console looks like both Starbound and StarryPy are
running properly.  If it helps, I am using GameQ via a separate plugin for
Xenforo.  That plugin has an a 'generic' ping option as well, for games not
supported by GameQ.  I am currently using that option for the Starbound
server, as it does at least show the proper online/offline status for the
server, though without any info on player numbers.  You can see the plugin
operating at my website: mobiusgamers.org

**Comment by Austinb** [comment]
Until I can get a response from the server I cant really help.  I tried other servers, some worked and some didnt.  Usually when a server doesnt respond I attribute it to a firewall or routing issue.  But as it stands now the protocol looks to be the same (A2S), I just cant connect to that server to verify.

**Comment by TinCow** [comment]
It should be working now.  Turns out we never opened port 21024 when we added StarryPy, as it didn't need outside access to operate.  21024 now responds properly.  Be aware that I didn't notice the system bugging out though until it got to about 12 people online, so I'm not sure if you'll get useful data with less than that online (which is the case ATM).
