### ISSUE TITLE
Battlefield 4 - Undefined offsets

### ISSUE THREAD

**Issue by ceribik** [Austinb/GameQ#174]
I'm receiving the following errors:

 ErrorException: Undefined offset: 22 - foo/gameq/protocols/bf4.php:126
 ErrorException: Undefined offset: 23 - foo/gameq/protocols/bf4.php:127

Looking at the code and comment:
        // @todo: Supposed to be a field here <matchMakingEnabled: boolean>, its in R13 docs but doesnt return in response
        $result->add('blaze_player_count', $words[$index_current + 13]);
        $result->add('blaze_game_state', $words[$index_current + 14]);

It seems the issue is mostly with the server query documentation being wrong. 

Should these lines be commented out?

**Comment by Austinb** [comment]
Its possible the query response changed.  Did they remove those items from the end of the response?

**Comment by ceribik** [comment]
At the time when I made this report, it seemed like it.
