### ISSUE TITLE
mta port join and query 

### ISSUE THREAD

**Issue by Supryk** [Austinb/GameQ#176]
HI
If we have server IP like this:
46.29.17.251:22003
To query mta server we mast add 123 to port. IP must look 
46.29.17.251:22126
To connect we must have this
46.29.17.251:22003
mtasa://46.29.17.251:22003

Any chance to do it in mta.php?

**Comment by csplkiller** [comment]
Game for play port +0
Request port +123

$port=$port+123;

**Comment by csplkiller** [comment]
Query script, if you need... GTA, MTA

function monitor_server_gta($ip, $port, $request) {
if(!$ip OR !$port){return FALSE;}
$fp = fsockopen('udp://' . $ip, $port, $errno, $errstr);
stream_set_timeout($fp, 1, 0); stream_set_blocking($fp, true);
$packet = 'SAMP';
$packet .= chr(strtok($ip, '.'));
$packet .= chr(strtok('.'));
$packet .= chr(strtok('.'));
$packet .= chr(strtok('.'));
$packet .= chr($port & 0xFF);
$packet .= chr($port >> 8 & 0xFF);
fwrite($fp, $packet.'i');
$buffer = @fread($fp, 11);
if (!$buffer){return FALSE;}
$is_passworded = ord(fread($fp, 1));
$plr_count = ord(fread($fp, 2));
$max_plrs = ord(fread($fp, 2));
$strlen = ord(fread($fp, 4));
$hostname = fread($fp, $strlen);
$strlen = ord(fread($fp, 4));
$gamemode = fread($fp, $strlen);
$strlen = ord(fread($fp, 4));
$mapname = str_replace(" ", "_", fread($fp, $strlen));
fwrite($fp, $packet.'c');
fread($fp, 11);
$plr_count = ord(fread($fp, 2));
if ($request == "players") {
    if ($plr_count > 0) {
    for ($i=0; $i<$plr_count; $i++)
        {
            $strlen = ord(fread($fp, 1));
            $plrname = fread($fp, $strlen);
            $score = ord(fread($fp, 4));
            $player[$i + 1]['kills']  = $score;
            $player[$i + 1]['ping']   = 0;
            $player[$i + 1]['name']   = $plrname;
        }
    }
    fclose($fp);
    return $player;
    }
fclose($fp);
return array('name'=>"$hostname ( $gamemode )", 'totalplayers' => $plr_count, 'maxplayers'=>$max_plrs, 'map'=>$mapname, 'serverlocked'=>$is_passworded, 'gamename'=>"GTA SA");
}

**Comment by Austinb** [comment]
The connect port was an after thought and probably should have been added to this version.  It is hacky and requires too much working around to implement.   Also makes the idea of which port to use more confusing.  I am not making any more changes to the client connect port at this time due to lack of time and wanting to spend any free time I do have on v3.

**Comment by Walid10** [comment]
Hi please i have a question : about MTA sa i tried this but didn't work : 
<?php
require_once 'GameQ.php';

$server['mtasa'] = array ('mtasa', 'my server IP', 22003+123); //ip & port
$query = new GameQ;
$query -> addServers ($server);
$data = $query->requestData();

foreach ($server AS $server_id => $values) {
    $info = $data[$server_id];
    if (!isset($info["servername"])) {
        echo 'Server offline';
    } else {
        echo "Server name: ";
        echo $info["servername"];
        echo '<br/>';
        echo "Gamemode: ";
        echo $info["gametype"];
        echo '<br/>';
        echo "Map: ";
        echo $info["map"];
        echo '<br/>';
        echo "Players: ";
        echo $info["num_players"] ."/". $info["max_players"];
        echo '<br/>';
        echo $info['password'] == '0' ? 'No' : 'Yes';
        echo "Password: ";
        echo $pw;
        echo '<br/><br/>';
    }
    }
?>

error log:

fwrite(): send of 1 bytes failed with errno=1 Operation not permitted
