### ISSUE TITLE
Warsow Players array always empty even when players on server

### ISSUE THREAD

**Issue by warsowau** [Austinb/GameQ#177]
Hi, I'm trying to use GameQ to build a server browser in my website for the Australian warsow community. However, the players array in the results is always empty

Any chance you could fix this up? A new version of warsow was released just recently, that might be the problem

**Comment by danut1994gl** [comment]
Exactly same problem i have, I don't know how can i make visible players table..

**Comment by Austinb** [comment]
Do you have a sever with players on it I can test against?

**Comment by Austinb** [comment]
Closing due to lack of response.  Please feel free to reopen this issue if you can provide a test server with players or a link to a list of active servers.
