### ISSUE TITLE
New Game Request

### ISSUE THREAD

**Issue by danut1994gl** [Austinb/GameQ#178]
If you can please add support for Counter-Strike 2D. It's a popular game.

http://www.cs2d.com/

This game already exist in this version » http://gameq.sourceforge.net/

**Comment by danut1994gl** [comment]
Any response ? :+1:

**Comment by danut1994gl** [comment]
Any response ? :+1:

**Comment by Austinb** [comment]
Can you provide a working server ip:port?  The conversion is simple but I am having trouble querying any servers from the cs2d site list.
