### ISSUE TITLE
teamspeak 2 support

### ISSUE THREAD

**Issue by gcphost** [Austinb/GameQ#18]
we're looking to finally upgrade to gameq2 as its now supporting several important fixes over gameq1 - but there is no ts2 support.

I cant mix gameq1 and 2 in the same script so it has to be either-or

any interest in getting ts2 supported?

**Comment by Austinb** [comment]
Shouldnt be a big issue getting it built assuming I have something to test it against. I will see if I can get something done this week.

**Comment by gcphost** [comment]
thanks for adding support!@
