### ISSUE TITLE
Web server blocking requests

### ISSUE THREAD

**Issue by ghost** [Austinb/GameQ#180]
I have this script hosted on Hosting24 and I asked them to open the port "2302" but I am still getting "The server *******\* is down" are there any other ports that need to be open?

I know for a fact is not on my side because it works on xampp at home.

This is for an arma 2 OA (armedassault2OA) server request.

**Comment by Austinb** [comment]
The script does not use the game port to make outbound connections, it uses whatever ports are free.  It is possible your provider is blocking all outbound ports from the server to prevent dos and other bad behavior.  Unfortunately this is all on their end and there is nothing I can do to help.

**Comment by ghost** [comment]
Are there any ports I can ask my host to open? 

Edit - Ok I got the host to open ports: 2302,2303,2304,2305 and it works
