### ISSUE TITLE
Gamespy-based games like ARMA don't work

### ISSUE THREAD

**Issue by ceribik** [Austinb/GameQ#183]
Due to the gamespy shutdown, gamespy-based games like ARMA don't work properly. 

In the case of ARMA 3 (and probably the other ARMA games), they are now using the source query protocol, so it's an easy fix for them. I should point out I've tested it for ARMA 3 and works using the catch-all source server class.

**Comment by Endimmion** [comment]
Ceribik can you give the url of the source server class you used to query Arma3? I tried to query the new Arma 3 server with this one https://github.com/xPaw/PHP-Source-Query-Class without success

**Comment by ceribik** [comment]
It's the source server one in GameQ.

**Comment by Endimmion** [comment]
Can you show me a working example?

**Comment by Endimmion** [comment]
I have found one. the problem was that few servers use the defaut query port.

**Comment by ghost** [comment]
Arma 2 still works fine for me,

EDIT - Your right its the new update for arma, it moves everything to steam servers.

**Comment by ceribik** [comment]
Source: http://forums.bistudio.com/showthread.php?175463-End-of-Gamespy

**Comment by fritzmg** [comment]
I notice the same (?) problem with Crysis Wars now. The Master server went down recently and ever since some Crysis Wars servers are not scannable by GameQ anymore.

Services like gametracker.com cannot scan the respective servers anymore either. However game-monitor.com can still scan all the Crysis Wars servers correctly, so there must be a way.

**Comment by fritzmg** [comment]
So far, the only thing I've figured out is, that the challenge response for the servers that do not work anymore is always "     0@0" (09 10 20 30 40 30 00 in hexadecimal).

**Comment by Austinb** [comment]
If anyone has a newer sever up and running please send me the info so I can verify the change works.  In the mean time you can change the gametype from armedassault3 to source when you query and in theory it should work fine. There is some issue regarding the query port so I am unable to connect to any public servers for testing.

**Comment by ghost** [comment]
The server I am trying to connect to is "37.187.134.78" hopefully you can use that server. Its an arma 2 OA server.

**Comment by Verox-** [comment]
You can use our server for testing if you like, we run both Arma 3 and Arma 2: CO servers.
address:gameport:queryport
arma2.unitedoperations.net:2302:27001
arma3.unitedoperations.net:2402:2403

**Comment by firefly2442** [comment]
Just FYI, the default Arma 3 steam query port is 2303.  See here:

https://community.bistudio.com/wiki/Arma_3_Dedicated_Server#Port_Forwarding

I was able to change the query type to "source" and it worked after setting the appropriate port for both Arma2OA and Arma3.  Some of the fields/entries that worked or were provided from the GameSpy query don't seem to work or are different for the Source query.

**Comment by Verox-** [comment]
The default Arma 3 query port is linked to whatever your game server port is configured as. By default it's 2303 (game + 1). It seemed to completely ignore the custom port configured.

https://community.bistudio.com/wiki/server.cfg#Arma_2:_Operation_Arrowhead_.26_Arma_3_-_STEAM_ports_configuration

**Comment by Austinb** [comment]
Verified the port and ARAM3 is working.  Unable to get ARMA 2 to work.  If there are other games please open a new issue for each game that needs to be converted so it is easier to keep track of what is outstanding.   Sorry for the late update havent had much time to work on this.

**Comment by Verox-** [comment]
Got Arma 2 working under Source protocol, you need to be certain you're using the correct port and NOT the gameserver port. You can check which port you're using in your server.cfg file for Arma 2 and Arma 3.
This may be worth mentioning in the wiki.

**Comment by ghost** [comment]
steamqueryport          =27016; //default 27016, needs to be unique if multiple servers on same box

Is this what your talking about? This is in the server.cfg

**Comment by Verox-** [comment]
That is indeed it, mind your Arma 3 server may or may not default to gameserver + 2, I've not quite worked out how that behaves yet.

**Comment by Austinb** [comment]
Fixed with merge #190
