### ISSUE TITLE
Star Made Server Support

### ISSUE THREAD

**Issue by Saiboogu** [Austinb/GameQ#188]
Can we get Starmade server support? I have a server up @ linbox.pr-gaming.net:4242 if it helps.

I also see this class has been created already: http://www.twosphere.com.au/projects/starmade-query-php-class (included in the header of the PHP is an open usage license for the code)

It would be nice to see it included in GameQ for the consistent experience. Thanks.

**Comment by Austinb** [comment]
Thank you for the client script but is there a protocol document available?  If so please comment with a link.  It is much easier to start with the protocol documentation rather than trying to reverse engineer a query client.

**Comment by Saiboogu** [comment]
I've done some Googling, and posted questions on the StarMade forums and subreddit, but no luck finding a protocol document. Sorry.

**Comment by Saiboogu** [comment]
The StarMade dev said he would be glad to help, and you should email him. His address is at the bottom of the 2nd link.

http://www.reddit.com/r/Starmade/comments/2e2ual/looking_for_query_protocol_documentation/
http://star-made.org/terms_and_conditions#imprint

**Comment by Austinb** [comment]
Reference: https://github.com/sonicsnes/node-gamedig/blob/master/protocols/starmade.js

**Comment by Austinb** [comment]
Turns out the node version of the protocol at https://github.com/sonicsnes/node-gamedig/blob/master/protocols/starmade.js is just a trial and error.  Used docs from Robin Promesberger at starmade to build. 

Unsure if I will port this to v2 due to the buffer requirements to read big endian bytes.  Default of the Buffer class is machine order.

**Comment by Austinb** [comment]
Not porting to v2, closing ticket.
