### ISSUE TITLE
CoD Black Ops support

### ISSUE THREAD

**Issue by TacTicToe66** [Austinb/GameQ#189]
I know this has been asked before. I have the protocol info needed to create the protocol script. I just do not know how to port it to GameQ. Can you add support for this if I send you the info you need? You will need to add a line for the admin to add their rcon password for it to query all the info. 

Please?

**Comment by Austinb** [comment]
In order to build this I basically need a running test server with players.  Passing login info is not an issue the problem is testing.

**Comment by TacTicToe66** [comment]
I have a pretty active Nuketown server. I will PM you the rcon as long as you dont have to reboot the server or anything. That sort of tends to piss off players.  :)

**Comment by TacTicToe66** [comment]
Any news?

**Comment by TacTicToe66** [comment]
BUMP???

**Comment by Austinb** [comment]
I never received any information to build and test the protocol with.  Closing.
