### ISSUE TITLE
Gamespy 2 & 3 updates to Source Protocol

### ISSUE THREAD

**Issue by Austinb** [Austinb/GameQ#191]
Need to know a list of games that need to be migrated from GameSpy to Source (A2S).  Any games that will no longer work will be retired from the system. I am assuming that some games will not be updated given their age but I could be wrong in this assumption. 

Please provide any games that need to be changed or better yet provide a pull request and reference this issue please.

**Comment by Verox-** [comment]
I've already gone through the entire list of supported protocols and changed the relevant ones in the latest merge. The games didn't change can still be queried with the Gamespy protocols and some games have been given community updates to have them continue working after the master-server shut down so there should be no need to remove any game support.

**Comment by Austinb** [comment]
If there are any more of these that need to be updated please make pull requests and reference this issue.
