### ISSUE TITLE
server is online (local server) but displayed as offline

### ISSUE THREAD

**Issue by Parilar** [Austinb/GameQ#196]
Hello
After i could find out how to fixx my other problem , i've got  an new one.
My teamspeak Server (Same with Minecraft) is running locally on Port 9987. But it is displayed as offline.

![image](https://cloud.githubusercontent.com/assets/8159646/4058471/599b5882-2dd6-11e4-8b33-3e3dbbae20ce.png)

What could be the problem ? I've red that locally there can't be a port problem.

**Comment by Austinb** [comment]
Sorry for the really late reply.  Are you still having this issue?  If so please reopen this issue.
