### ISSUE TITLE
gamespy3 protocol issue (empty challenge request id)

### ISSUE THREAD

**Issue by fritzmg** [Austinb/GameQ#197]
Since the shutdown of the Gamespy servers there has been an issue with scanning games that are using the gamespy3/4 protocol (and still are). At least if it is a _Crysis Wars_ server (and running the MWLL Mod). Once the server has no connection to the Gamespy Master Server when it boots up, the first response after the challenge request is always

```
09 XX XX XX XX 30 00
```

i.e. the challenge ID string returned by the server is always "0". This creates two issues:
### Challenge ID parsing fails

This code in `GameQ_Protocols_Gamespy3::parseChallengeAndApply()` will return `false` in such a case:

``` php
// Pull out the challenge
$challenge = substr(preg_replace( "/[^0-9\-]/si", "", $this->challenge_buffer->getBuffer()), 1);
```

But this is not actually a problem, the main problem is:
### The second request will be wrong

If the challenge response returned a "0" challenge ID, then the second request needs to be

```
FE FD 00 WW WW WW WW FF FF FF 01
```

instead of

```
FE FD 00 WW WW WW WW ZZ ZZ ZZ ZZ FF FF FF 01
```

i.e. the part where you would send the challenge ID as a byte encoded int (**Z**) must be ommited completely! Otherwise the server will not respond with the information.

To quickly fix this, I changed only the `GameQ_Protocols_Gamespy3::parseChallengeAndApply()` as follows:

``` php
protected function parseChallengeAndApply()
{
    // Pull out the challenge
    $challenge = substr(preg_replace( "/[^0-9\-]/si", "", $this->challenge_buffer->getBuffer()), 1);

    // by default, no challenge result
    $challenge_result = '';

    if( $challenge )
    {
        $challenge_result = sprintf(
            "%c%c%c%c",
            ( $challenge >> 24 ),
            ( $challenge >> 16 ),
            ( $challenge >> 8 ),
            ( $challenge >> 0 )
            );
    }

    // Apply the challenge and return
    return $this->challengeApply($challenge_result);
}
```

So this way, if the `substr( preg_replace( ... ) )` part fails, the `$challenge_result` will simply be an empty string, instead of `false` or `0`. And when it's an empty string, the resulting second request packet will look like this:

```
FE FD 00 WW WW WW WW FF FF FF 01
```

thus the server will respond with all the data again in the second response (instead of no data).

**Comment by Austinb** [comment]
Is this issue still occurring?  If so reopen this issue and please provide a server ip:port so I can look into it.

**Comment by fritzmg** [comment]
Yes, this issue is still occuring (without my change). You can test with `176.9.140.228:64100` for example (or any IP on [this list](http://stats.spikx.net/mwll.html), I think).

Btw. I found out about the other format of the second request (when the challenge ID is `0`) by wiresharking the traffic of [Qtracker](http://www.qtracker.com/).
