### ISSUE TITLE
Red Orchestra 2

### ISSUE THREAD

**Issue by devu4** [Austinb/GameQ#198]
Getting this error when I add any server with 'type' => 'redorchestra2'

Fatal error: Uncaught exception 'GameQ_ProtocolsException' with message 'Unable to read length={$length} from buffer. Bad protocol format or return?' in /home/u369087336/public_html/gameq/buffer.php:106 Stack trace: #0 /home/u369087336/public_html/gameq/protocols/source.php(108): GameQ_Buffer->read(4) #1 /home/u369087336/public_html/gameq/protocols/core.php(494): GameQ_Protocols_Source->parseChallengeAndApply() #2 /home/u369087336/public_html/GameQ.php(594): GameQ_Protocols_Core->challengeVerifyAndParse() #3 /home/u369087336/public_html/GameQ.php(459): GameQ->requestMulti(Array) #4 /home/u369087336/public_html/examples/index.php(208): GameQ->requestData() #5 {main} thrown in /home/u369087336/public_html/gameq/buffer.php on line 106

**Comment by Verox-** [comment]
Could you provide a few addresses of the servers and query ports you are trying query?

**Comment by devu4** [comment]
31.186.251.139:7777

**Comment by devu4** [comment]
any luck?

**Comment by devu4** [comment]
Issue fixed; I changed host to just the ip with no port, Its now using 27015 as query port
