### ISSUE TITLE
Player Time

### ISSUE THREAD

**Issue by Lasim** [Austinb/GameQ#199]
Hey,

how to translate Player time to human readable time?

I got array like this:

[players] => 
    [0] =>
            [name] = "XXXX",
            [score] = "2",
            [time] = "264.06530761719",       

How to translate 264.06530761719  to Hr. Min ?
Microtime, Date?

Thank you!

**Comment by Verox-** [comment]
This would depend on which protocol was returning the data. What game were you trying to query?

**Comment by Lasim** [comment]
Hi Verox,

im trying to query out Counter Strike source Server.

**Comment by Verox-** [comment]
Counter Strike Source uses the A2S protocol. Time is the number of seconds a player has been connected to the server.

https://developer.valvesoftware.com/wiki/Server_queries#Response_Format_2

**Comment by Lasim** [comment]
Thank you!

**Comment by Blackskyliner** [comment]
There should be a Filter or Normalizer to convert time values of multiple protocols to either a DateTime with the absolute time when he connected to the server or relative Time through DateInterval. Or normalize all times to the second.microseconds format.

**Comment by Austinb** [comment]
@Blackskyliner Please add this as a request in its own ticket.  Might be able to do it for v2 but more likely will go into v3.
