### ISSUE TITLE
spl_autoload() could not be loaded

### ISSUE THREAD

**Issue by matrixcraftsvn** [Austinb/GameQ#200]
Maybe i'm doing this wrong, however I used the Example.php script to check my Ts3 Server,
I changed $servers to
$servers = array(
        array(
                'id' => 'ID: TeamSpeak3',
                'type' => 'Teamspeak3',
                'host' => '81.169.206.237:9987',
        )
);

now I'm getting this error
Fatal error: spl_autoload(): Class GameQ\Server could not be loaded in /opt/lampp/htdocs/gameq3/GameQ.php on line 148

I'm useing GameQ v3
but even with GameQ v2 it dont work, I set the timeout to 10 seconds, but it says the connection timed out without waiting.

**Comment by Verox-** [comment]
The ID should be 'teamspeak3' not 'ID: TeamSpeak3' 
Use GameQ v2 for now, it's much more stable.

**Comment by Austinb** [comment]
GameQ v3 is very alpha.  If you get it to work or fix your problem please provide any feedback.  Looking to get back into this in the coming weeks and get something stable out for testing.

**Comment by matrixcraftsvn** [comment]
when i use v2, and set the timeout to 10 seconds, it just go without waiting "The server did not respond within the specified time."

**Comment by Verox-** [comment]
Try using the Query port, i'm not entirely sure how TS3 is implemented in GameQ but if it uses the ServerQuery functionality then you need to use port 11001 (by default, I think, check your server config).

**Comment by WanielDeiss** [comment]
I have the same problem with dayz, in v3.

`Fatal error: spl_autoload(): Class GameQ\Server could not be loaded in /Applications/MAMP/htdocs/dayztest/gameq/GameQ/gameq.php on line 162`

I use PHP 5.5.14 on a local machine (Mac).

**Comment by Austinb** [comment]
The only available protocol in v3 at the moment is source.  I am still working on it but it is very unstable and missing some pieces still.  If you wish to use GameQ in production or with anything other than Source please use v2.

**Comment by Austinb** [comment]
Seems there were some bugs in the autoloader (see: http://stackoverflow.com/questions/3187192/using-spl-autoload-not-able-to-load-class).

**Comment by Austinb** [comment]
Just to inform all of you using v3 in one form or another I have just pushed up a big change moving the library to the PSR-4 spec.  Also changed the Autoloader.php as well.  So you will need to update your includes if you are using version 3 outside of composer.  Please provide any feedback you can..

**Comment by Austinb** [comment]
Closing.  If you have an issue with the autoloader as it sits now in the latest dev please reopen.
