### ISSUE TITLE
Minecraft server not responding

### ISSUE THREAD

**Issue by skylord123** [Austinb/GameQ#203]
I have a minecraft server that I am trying to query and it is not working. Server query is enabled and port is correct as gametracker.com can track it just fine.

Server information: 64.87.51.162:25565

Seems that if I change the port number is takes longer to respond then the actual query port. I tried to query the server from same machine and also from remote machine with no luck.

I think there is something wrong with the protocol of some sort. 

EDIT: Query port has been changed to 25566 instead of 25565 just to double check. Same issue as before. If you need to test please use port 25566 on the above IP address. Thanks.

**Comment by Kandru** [comment]
Your server does not respond to GameTracker, too. Could you please fix this so I can test it with GameQ? http://www.gametracker.com/server_info/64.87.51.162:25565/
