### ISSUE TITLE
Undefined index name and score

### ISSUE THREAD

**Issue by Snakzi** [Austinb/GameQ#205]
Hi,

I tried

$player_name = $results['MYID']['name'];
$player_score = $results['MYID']['score'];

but it says "undefined index name and score".

$maxplayers = $results['MYID']['max_players'];
$server_name = $results['MYID']['hostname'];

is working. what to do?

**Comment by Lasim** [comment]
Please read about PHP Array - Multidimensional Array

http://php.net/manual/de/language.types.array.php

Use
print_r($array_name);
to print array

What you're looking for is:
echo $player_name['server_id']['players'][ID]['name']

**Comment by Snakzi** [comment]
Thanks, its working.
