### ISSUE TITLE
Teamspeak3 doesn't work

### ISSUE THREAD

**Issue by Gun22** [Austinb/GameQ#207]
Website says: <pre>Fatal error: Uncaught exception 'GameQException' with message 'GameQ::socket_open Error creating socket to server tcp://37.17.173.144:9987. Error: ' in /var/www/seeunited/UCP/grafikon/GameQ.php:756 Stack trace: #0 /var/www/seeunited/UCP/grafikon/GameQ.php(677): GameQ->socket_open(Object(GameQ_Protocols_Teamspeak3)) #1 /var/www/seeunited/UCP/grafikon/GameQ.php(594): GameQ->queryServerInfo(Array) #2 /var/www/seeunited/UCP/grafikon/GameQ.php(454): GameQ->requestMulti(Array) #3 /var/www/seeunited/UCP/grafikon/funkciok.php(54): GameQ->requestData() #4 /var/www/seeunited/UCP/grafikon/funkciok.php(93): szerver_Query('teamspeak3', '37.17.173.144', '9987') #5 {main} thrown in /var/www/seeunited/UCP/grafikon/GameQ.php on line 756</pre>

The code is the following:

<pre>$szerverek = array(
    array(
        'id' => 'teamspeak3',
        'type' => 'teamspeak3',
        'host' => '37.17.173.144:9987',
        'options' => array(
            'master_server_port' => 9987,
        )
    ),
);

$gq = new GameQ();
$gq->setOption('timeout', 5);
$gq->setOption('debug', TRUE);
$gq->setFilter('normalise');
$gq->addServers($szerverek);

$adat = $gq->requestData();
var_dump($adat);</pre>

**Comment by Supryk** [comment]
maybe 'master_server_port' => 10011, ?

perms on ts3 ok?
b_virtualserver_info_view
b_virtualserver_channelgroup_list
b_virtualserver_client_list
b_virtualserver_channel_list
b_serverinstance_version_view - not necessarily

**Comment by Gun22** [comment]
now it's working with:
<code>
$gq->addServer(array(
    'id' => 'teamspeak3',
    'type' => 'teamspeak3',
    'host' => '37.17.173.62:9987',
    'options' => array(
        'master_server_port' => 10011,
    )
));
</code>

but if I refresh it twice quickly, it says:
<code>Uncaught exception 'GameQ_ProtocolsException' with message 'GameQ_Protocols_Teamspeak3::verify_header: Length of buffer is not long enough</code>

**Comment by Austinb** [comment]
Usually the master server port and client ports are not the same.  They should be 2 different ports based on how I remember teamspeak working.  Please provide the master and client connect ports.
