### ISSUE TITLE
Game support: Trackmania Series

### ISSUE THREAD

**Issue by jmgraeffe** [Austinb/GameQ#209]
It will be nice to have a query support for Trackmania and the Gbx-XMLRCP protocol.
Because of the using of Gbx data format and a huge amount of requestable information (which is other than the others) it can be a bit difficult.

There is a PHP class written by someone already, here is the link for some protocol information:
http://www.xaseco.org/Downloads/gbxremote.zip
And here is an information forum topic about the author:
http://www.tm-forum.com/viewtopic.php?t=28070

**Comment by Austinb** [comment]
Possible help on integration:
http://www.gamers.org/tm2/docs/ListMethods_2011-08-01.html Seems call have to be done via xml-rpc.  

Maybe this: https://github.com/maniaplanet/maniaplanet-ws-sdk.
https://forum.maniaplanet.com/viewtopic.php?f=463&t=26913
https://github.com/Jojo44/GBXRemote
https://github.com/NewboO/dedicated-server-api

In all cases it appears you need to have login information for the server itself or the API.

**Comment by Austinb** [comment]
Without login information it is impossible to build.  Closing
