### ISSUE TITLE
gamespy code not working?

### ISSUE THREAD

**Issue by gcphost** [Austinb/GameQ#21]
I try the type code of gamespy, gamespy2, gamespy3 but none work - sorry if I am missing something simple.

$gcode="gamespy2";
$fip="xxxxx";
$fport="12200";

$servers = array(array('id' => 'server', 'type' => $gcode, 'host' => $fip.":".$fport));

**Comment by Austinb** [comment]
Hello,

Gamespy v1:
Battlefield 1942 - 216.52.148.184:14570 (Query 23000) Verified
Red Orchestra - 149.255.33.50:7757 (Query 7767) Verified

Gamespy v2:
Battlefield: Vietnam - 69.28.221.179:15567 (Query 23000) Verified
F.E.A.R - 68.232.166.188:27888 Verified

GameSpy v3:
Crysiswars - 69.9.170.61:64100 Verified
UT3 - 8.12.17.12:7777 (Query 6500) Verified

Gamespy does not always follow standard query ports.  So game != query in most cases.  Most of the games you can specify the query port in the server settings I believe.

**Comment by Austinb** [comment]
If you have a specific issue with a server or game please feel free to post it here or send me a pm and send me the info so I can look and debug.   Without knowing the server information I can not offer anything other than to check the query port.  Some of the information in the wiki has known offsets of game port to query port but those are defaults only.  If the game server allows changing the query port then there is no easy way to find it. 

If you have any other info or issues please reopen this ticket or create a new one.

**Comment by Austinb** [comment]
Just to revisit this if you are trying to specify the class gamespyX you will be unable to with the way the classes are built.  They are meant to be extended upon and are designated as abstract and php will not allow you to call them directly.  If you need a specific game added that is easy.  Just copy one of the existing classes that extend the gamespy version you are looking for and change all the info.

If more people need generic gamespyX calling ability I can remove the abstract part of the classes.
