### ISSUE TITLE
Where is GameQ V3?

### ISSUE THREAD

**Issue by gcphost** [Austinb/GameQ#210]
Where is V3 hosted?

The only thing I find is on someone else github account:
https://github.com/kostya0shift/GameQ3

**Comment by Austinb** [comment]
I have a branch setup with some preliminary changes here: https://github.com/Austinb/GameQ/tree/v3.  Unfortunately I have had little time to come back to this project as of late.  Hopefully will be able to get back to v3 in a couple of weeks. 

If you do test it out please provide any feedback you can on performance and any other changes from the current v2 setup you would like.  

Currently the only working protocol for v3 is Source and it is very basic support but should be able to give you raw information for most games using the A2S (source) protocol.
