### ISSUE TITLE
About Mta:sa 

### ISSUE THREAD

**Issue by Walid10** [Austinb/GameQ#214]
Hi please i have a question : about MTA sa i tried this but didn't work : 
<?php
require_once 'GameQ.php';

$server['mtasa'] = array ('mtasa', 'my server IP', 22003+123); //ip & port
$query = new GameQ;
$query -> addServers ($server);
$data = $query->requestData();

foreach ($server AS $server_id => $values) {
$info = $data[$server_id];
if (!isset($info["servername"])) {
echo 'Server offline';
} else {
echo "Server name: ";
echo $info["servername"];
echo '
';
echo "Gamemode: ";
echo $info["gametype"];
echo '
';
echo "Map: ";
echo $info["map"];
echo '
';
echo "Players: ";
echo $info["num_players"] ."/". $info["max_players"];
echo '
';
echo $info['password'] == '0' ? 'No' : 'Yes';
echo "Password: ";
echo $pw;
echo '

';
}
}
?>

error log:

fwrite(): send of 1 bytes failed with errno=1 Operation not permitted

**Comment by Verox-** [comment]
Some hosting companies disable sockets, if this is the case then you can only switch hosting companies.
Check php_info() and look for disabled socket functions.

Next time, please, only post once. Posting the same thing multiple times will not get it answered any faster.

**Comment by Walid10** [comment]
sorry about this because it's the first time that use github anyways please can you explane to me how to disable socket.

Erro log : fwrite(): send of 1 bytes failed with errno=1 Operation not permitted in GameQ/Communicate.php on line 138

**Comment by Walid10** [comment]
any help

**Comment by Lasim** [comment]
As Verox said, you hosting company don't allow to use REMOTE socket.
To test it you can test remo ftp connection via php for exmaple
http://stackoverflow.com/a/3729732

**Comment by Austinb** [comment]
I believe that @Lasim and @Verox- are correct.  Some hosting companies block outgoing ports except for specific ones to prevent their servers being used for nefarious purposes.   You will probably have to find another hosting provider or contact their support to see if they can help.
