### ISSUE TITLE
Add name_long as a returned data field

### ISSUE THREAD

**Issue by johndrinkwater** [Austinb/GameQ#220]
Some protocols don’t return a friendly/long name in their game_descr, even with the normalise plugin in use.
Games like `Killing Floor` and `Mount & Blade: Warband`, return a blank field for game_descr if the server is empty, with the only reasonably user-facing data being gq_type which has their short name, killingfloor or warband etc.

**Comment by Austinb** [comment]
Fixed in v3 in d7ee4dbbb216ffff1d78a0773dd74284b17361b9 will port to v2 soon.
