### ISSUE TITLE
laravel

### ISSUE THREAD

**Issue by boyfromhell** [Austinb/GameQ#222]
hi there.
It can be used with laravel GameQ.
And if you can,
Can you give an example please.

**Comment by Austinb** [comment]
You should be able to add this to your composer.json:

``` javascript
"austinb/gameq": "2.*@dev"
```

Then run a composer update to have it pull down.  After that the \GameQ() class should be in your autoloader pathing and be accessible.  I am not sure since the v2 system was built before composer and the like got big.

**Comment by boyfromhell** [comment]
Thank You.
I succeeded v3.
But v2, give a lot of errors yet.

**Comment by Austinb** [comment]
Need more information such as errors.  It is possible in v2 you may need to include the GameQ.php file.  I have never used v2 in a composer based install.

**Comment by rbozan** [comment]
How would you use this with Laravel after you installed it in composer?

**Comment by rbozan** [comment]
Thanks for answering
