### ISSUE TITLE
gg_online always true in v3

### ISSUE THREAD

**Issue by boyfromhell** [Austinb/GameQ#224]
In GameQ gg_online v3 is always one.
And when it is closed.

**Comment by Austinb** [comment]
What protocol and if you can provide the ip:port of the server.  It is possible there is a bug in there since it is still being built.

**Comment by boyfromhell** [comment]
So in v2
'type' => 'source',
'host' => '64.74.97.225:27015'

gg_online return true

'type' => 'source',
 'host' => '64.74.97.22:27015'
return null

In v3 
'type' => 'source',
'host' => '64.74.97.225:27015'

Return gg_online true

'type' => 'source',
'host' => '64.74.97.22:27015'

return true

in gg_online v3 is always true
