### ISSUE TITLE
Battlefield Hardline Suppport

### ISSUE THREAD

**Issue by dudenell** [Austinb/GameQ#234]
Was wondering if it would be possible to support BF Hardline. Thanks!

**Comment by Endimmion** [comment]
Meanwhile you can use BF4 protocol, it works.

**Comment by Austinb** [comment]
Is there any documentation for this game.  Both 3 and 4 had server documentation that was released.  I want to see if the returned keys changed or any new ones were added.  Thanks.

**Comment by dudenell** [comment]
http://eaassets-a.akamaihd.net/dice-games/BFH/ServerDocumentation/BFH_PC_Server_R2_525698_AdministratorDocumentationV2.2.zip

I believe that's the latest, games pretty new so

**Comment by Austinb** [comment]
Added to v2 in 5b56f8ae0873b6602d8819e690638f099cfffa22

**Comment by Austinb** [comment]
Thanks for the documents.  Appears this version is still incomplete like bf4 is, oh well. Also appears the punkbuster version is not returned in bfh.
