### ISSUE TITLE
Fetching Issue

### ISSUE THREAD

**Issue by ellisonpatterson** [Austinb/GameQ#235]
So I make a fetchData request, and I get this general information:

`[3] => array(18) {
    ["gq_address"] => string(29) "xxxx"
    ["gq_dedicated"] => bool(false)
    ["gq_gametype"] => bool(false)
    ["gq_hostname"] => bool(false)
    ["gq_joinlink"] => string(52) "steam://connect/xxxx:27015/"
    ["gq_mapname"] => bool(false)
    ["gq_maxplayers"] => bool(false)
    ["gq_mod"] => bool(false)
    ["gq_name"] => string(15) "Team Fortress 2"
    ["gq_numplayers"] => bool(false)
    ["gq_online"] => bool(false)
    ["gq_password"] => bool(false)
    ["gq_port"] => string(5) "27015"
    ["gq_protocol"] => string(6) "source"
    ["gq_transport"] => string(3) "udp"
    ["gq_type"] => string(3) "tf2"
    ["players"] => array(0) {
    }
    ["teams"] => array(0) {
    }
  }`

But when I re-execute the script, it gives me full detail about the server. Why would it be doing this?

**Comment by Austinb** [comment]
Which version?  Also what is your ping time between the server making the calls and the game server?
