### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by phipag97** [Austinb/GameQ#238]
Version 2.0.3
Russian characters for example are incorrectly parsed. Unable to insert in an utf-8 formatted mysql db for example (see "sv_hostname"):
array (
  '80.77.175.114:28961' => 
  array (
    'admin' => '^1M^3A^2N^4I^6C ^4M^6I^1N^3E^2R',
    'email' => 'manic.miner@mail.ru',
    'g_antilag' => '1',
    'g_compassShowEnemies' => '0',
    'g_gametype' => 'war',
    'gamename' => 'Call of Duty 4',
    'gameplay' => 'RANKED',
    'location' => '^7R^4U^1S',
    'mapname' => 'mp_countdown',
    'maps' => 'Team DeathMatch Only',
    'protocol' => '1',
    'rules' => 'All Perks Allowed',
    'shortversion' => '1.2',
    'spieltype' => 'HardCore',
    'sv_allowAnonymous' => '0',
    'sv_disableClientConsole' => '0',
    'sv_floodProtect' => '1',
    'sv_hostname' => '^1�.^2�.^3�.^5.^6.',
    'sv_maxclients' => '50',
    'sv_maxPing' => '350',
    'sv_maxRate' => '25000',
    'sv_minPing' => '0',
    'sv_privateClients' => '0',
    'sv_punkbuster' => '0',
    'sv_pure' => '1',
    'sv_voice' => '1',
    'ui_maxclients' => '50',

**Comment by Austinb** [comment]
This is a known issues as there is no standardization between the different protocols to make all the encoding the same.  You will have to manually utf8 encode the fields that need it before saving the data in a utf8 defined field.

**Comment by phipag97** [comment]
I just get an empty string after utf8 encoding. However, for the source engine for example it works as expected.

**Comment by Austinb** [comment]
If the hostname is the same as your output up there it will probably be empty as there appears to be no real low ascii characters in the response.  For Source it always returns data encoded in utf8 format.  See: https://developer.valvesoftware.com/wiki/Server_queries#Data_Types in the "string" response type.

**Comment by phipag97** [comment]
Thanks, I got that. But I do not get how to show these characters for quake3. Or is this impossible?
