### ISSUE TITLE
GameQ2 Sytnax Error in Protocols/Source.php

### ISSUE THREAD

**Issue by own3mall** [Austinb/GameQ#241]
Hi,

The GameQ2 example "index.php" which queries a bf3 and cs16 server does not work.  It fails to run with the following message:

~/Downloads/GameQ-2/examples$ php index.phpPHP Parse error:  syntax error, unexpected '[' in /home/earnolmartin/Downloads/GameQ-2/gameq/protocols/source.php on line 43

This is on PHP 5.3.10 with Ubuntu 12.04.  Thus, I'm thinking there is a problem with the source protocol in GameQ?

**Comment by Austinb** [comment]
Issue is with my editor converting array() into the shorthand [] which is not supported until php 5.4.
