### ISSUE TITLE
KF2 Protocol

### ISSUE THREAD

**Issue by kc1r74p** [Austinb/GameQ#243]
Seems like they use Source Protocol for KF2 Default Port 27015.
There are some useful fields: CurrentWave, MaxZedCount, ...

**Comment by Austinb** [comment]
Will add once it is launched and there are production servers around to build tests against.

**Comment by gothroach** [comment]
Feel free to query against valjean.kf.0xf.org - query ports start at 27015 and go up as odd numbers from there.

EDIT: I had to move my servers to a different IP in the same block, I updated the hostname in my comment.

**Comment by Austinb** [comment]
Thanks.  I will try to build this during the week.

**Comment by Austinb** [comment]
Class added with tests @ 837e8cb
