### ISSUE TITLE
dayzmod, arma 2, arma 2 oa status server don't work in GameQv2

### ISSUE THREAD

**Issue by hekut146** [Austinb/GameQ#244]
##

**Comment by Lasim** [comment]
If you don't understand how to install v3 read the php basics doc about OOP

http://php.net/manual/en/language.oop5.basic.php

**Comment by hekut146** [comment]
I filled the files from version 3 to the web server in the transition to the example he gives a blank screen (White)

**Comment by Lasim** [comment]
You need to enable error messages 

http://stackoverflow.com/questions/5438060/showing-all-errors-and-warnings

Just add on top of your php file

error_reporting(E_ALL);
ini_set('display_errors', 1);

**Comment by hekut146** [comment]
First mistake was not connected the right way, replaced the: require '../src/GameQ/GameQ.php';
Second error: Fatal error: Class 'GameQ' not found in /var/www/dz/examples/index.php on line 26

**Comment by Lasim** [comment]
The Problem is:
File:  /var/www/dz/examples/index.php 
Lune: 26

THIS:
require_once('/path/to/src/GameQ/Autoloader.php');

Enter "Absolute Path" to your Autloader.php file

Example:
require_once('/var/www/dz/examples/GameQ/Autoloader.php');

**Comment by hekut146** [comment]
index.php: 
line 26: $gq = new GameQ();

error:
Fatal error: Namespace declaration statement has to be the very first statement in the script in /var/www/dz/src/GameQ/GameQ.php on line 23

whed i add:
require_once('/var/www/dz/src/GameQ/Autoloader.php');

see:
Fatal error: Namespace declaration statement has to be the very first statement in the script in /var/www/dz/src/GameQ/GameQ.php on line 23

**Comment by hekut146** [comment]
people please help

**Comment by hekut146** [comment]
<?php

error_reporting(E_ALL);
ini_set('display_errors', 1);

require_once('/var/www/dz/src/GameQ/Autoloader.php');
require '../src/GameQ/GameQ.php';

$GameQ = new \GameQ\GameQ();
$GameQ->addServer([
    'type' => 'armedassault2oa',
    'host' => '85.159.42.196:2402',
]);

$results = $GameQ->process();

?>
 
I see empty screen, no errors when i write echo 'test' i see test no status server in v2 and v3 GameQ

**Comment by Austinb** [comment]
Make sure you have downloaded the latest version of v3 if you are going that route and not using composer.   Also you do not need both the autoloader and the GameQ.php files included.  The autoloader in v3 handles setting up the loading for the entire library. 

Version 2 should still work.  Please check the ports you are attempting to use to make sure they are the query ports and not the client ports.  Also check to make sure the host you are running the library on does not block outgoing ports.

What version of php are you using?

**Comment by hekut146** [comment]
If test i write ip:port 85 .159.42.196: 2402 - server arma.ru 2 wasteland this server is online but this script don't show status and other information i download last v3 version GameQ and php version 5.5.9-1ubuntu4.4

**Comment by Austinb** [comment]
Version 3 does not have support for vanilla arma 2.  Just arma2:oa and above. If the server at 2402 is an arma2 oa server I need the query port to test since the usual offset is not working.

**Comment by hekut146** [comment]
This server is arma 2 oa and currently online, I play on it, you would not be able to help me set up a script?

**Comment by hekut146** [comment]
print_r($results); script show ip:port name server 'id' and game name and a lot of Array

**Comment by hekut146** [comment]
Array ( [ARMA2.RU -Wasteland Sandbox- #1] => Array ( [gq_address] => 85.159.42.196 [gq_dedicated] => [gq_gametype] => [gq_hostname] => [gq_joinlink] => steam://connect/85.159.42.196:2402/ [gq_mapname] => [gq_maxplayers] => [gq_mod] => [gq_name] => Armed Assault 2: Operation Arrowhead [gq_numplayers] => [gq_online] => [gq_password] => [gq_port_client] => 2402 [gq_port_query] => 2401 [gq_protocol] => source [gq_transport] => udp [gq_type] => armedassault2oa [players] => Array ( ) [teams] => Array ( ) ) )

**Comment by hekut146** [comment]
In general, I understood that as arranged but the status of the server arma 2 oa and dayzmod does not work, does not provide information, please help

**Comment by hekut146** [comment]
solution to this problem forced installation of a quarry port -1 of game port to server.cfg 
steamPort = 2302;
steamQueryPort = 2301;

**Comment by Austinb** [comment]
If you have a link for this info please provide it.  Glad to hear you got it working.
