### ISSUE TITLE
Want to show only some parameters

### ISSUE THREAD

**Issue by leandrotruppa** [Austinb/GameQ#245]
Hello,

I am trying to understand the code and make my own servers list with GameQ. But i cant understand how to show only the things i want from the server info.

i dont know much about php and i need to show. Hostname server, Ip, Port, Players online, Max Players, Online or offline status. The problem i have its i need to show only this things and have a way to style by myself.

I need to use something like:

".maxplayers." ".online_players." ".ip." ".port." etc

How i can do it?

**Comment by Austinb** [comment]
To see the structures output you can do a print_r() on the responses to see how the data is setup.  All of the information is returned for all of the servers but you can cherry pick what information you want.

If you are doing this via a web page use the pre tag so it will pretty up the output so you can read it.  You can leave that off if doing the calls via the command line.

``` php
echo '<pre>';
print_r($results);
```

**Comment by Austinb** [comment]
If you have any more issues please reopen the issue.

**Comment by leandrotruppa** [comment]
Hi Austinb i tried the code you say and i get a lot of things of my own servers. Also i tried to get only a few data from each server with none success. Can you give an example of how to get the hostname?

I tried using $data['hostname'] but isnt working.
