### ISSUE TITLE
Teamspeak 3 status errors GameQ v3

### ISSUE THREAD

**Issue by hekut146** [Austinb/GameQ#247]
##

**Comment by Austinb** [comment]
The query_port server option is required in v3 given how teamspeak operates with a client and master port setup. See: https://github.com/austinb/gameq/wiki/Examples%20v3#teamspeak-2--3

Is your particular setup different?

**Comment by hekut146** [comment]
Errors were gone but the information and will not be displayed

**Comment by hekut146** [comment]
and when i set
error_reporting(E_ALL);
ini_set('display_errors', 1);

a see:
Notice: fwrite(): send of 25 bytes failed with errno=104 Connection reset by peer in /var/www/dz/status/files/Query/Native.php on line 64

Notice: fwrite(): send of 33 bytes failed with errno=32 Broken pipe in /var/www/dz/status/files/Query/Native.php on line 64
Сервер временно не доступен.Array ( [hgn.no-ip.org:9987] => Array ( [gq_address] => hgn.no-ip.org [gq_dedicated] => [gq_hostname] => [gq_joinlink] => ts3server://hgn.no-ip.org?port=9987 [gq_maxplayers] => [gq_name] => Teamspeak 3 [gq_numplayers] => [gq_online] => [gq_password] => [gq_port_client] => 9987 [gq_port_query] => 10011 [gq_protocol] => teamspeak3 [gq_transport] => tcp [gq_type] => teamspeak3 [players] => Array ( ) [teams] => Array ( ) ) )

**Comment by hekut146** [comment]
i can connect to ts 3 server in consol putty in telnet

**Comment by Austinb** [comment]
Those errors mean the host is not letting those connections go out or the server on the other end is rejecting them (instead of dropping).   Assuming those ports and the ip are correct you will need to check with your hosting provider and see what their policies are.

**Comment by hekut146** [comment]
Apache and ts 3 server install in my computer apache in ubuntu ip - x.x.x.3, ts 3 ip - x.x.x.2, what i need to do what this script display information?

**Comment by Austinb** [comment]
Not sure why the original issue was edited to be cleared.  Closing.
