### ISSUE TITLE
CoD MW3 TeknoGod server not work

### ISSUE THREAD

**Issue by AmkCity** [Austinb/GameQ#25]
CoD MW3 TeknoGod server is not ansvers from any ports
net_query = Port 55100
net_port =  27016
net_authPort 8766 
net_masterServerPort = 27017

**Comment by Austinb** [comment]
Hello,

Do you have the ip for the server?  I did notice while testing for MW3 that sometimes servers did not respond while others did. 

Examples from gametracker.com.

Querying 31.132.1.23:27015 works and returns all info (A2S)
Querying 93.93.65.88:27020 works as well

But 
Querying 66.150.164.154:27015 does not return any info.

My guess the query port is different and I have no way of finding it without port scanning which is bad.

-Austin

**Comment by AmkCity** [comment]
ip 83.234.147.40:27016

**Comment by Austinb** [comment]
Do you have admin control over this server?  If so I assume the command line has +set net_queryPort 55100 in it?  If not what is the net_queryPort setting?

Also, make sure the firewall is open for the port as well.  I assume players can get to the server and play.  If you test one of those working servers from my previous reply do you get a response with information as well?

-Austin

**Comment by AmkCity** [comment]
start settings:
start TeknoMW3_dedicated.exe +set dedicated 1 +set sv_config "server.cfg" +set net_queryPort 55100 +set net_port 27016 +set net_authPort 8766 +set net_masterServerPort 27017 +start_map_rotate

**Comment by Austinb** [comment]
Sorry for the late response.  Did you check to make sure the port is open to the internet?  The only other thing I can think of is some kind of internal setting I am unaware of.  The class works as it is supposed to assuming it gets a response from the server you are querying.

**Comment by Austinb** [comment]
Hello,

I am going to close this ticket.  Please let me know if you are still unable to make it work even with all the ports open to the outside internet.

**Comment by AmkCity** [comment]
server ports open to the outside internet, gamers incomes from internet and localnet
server work 24/7
