### ISSUE TITLE
GameQ Change Welcome Message PHP Control PANEL

### ISSUE THREAD

**Issue by grbz06** [Austinb/GameQ#250]
form action="save.php" method="post"
input type="text" value="<?php echo $results['teamspeak3']['virtualserver_welcomemessage']; ?>" name="virtualserver_welcomemessage"/  
input type="submit" class="button1" value="SAVE" /
/form

welcome here writes the message. How to change maybe, kodluyorum panel in php can you help me please save.php I couldn't do what the content is and how to file can you take a look ?

**Comment by Austinb** [comment]
Sorry but I do not support any kind of control panel system.  You will have to contact their support for help.
