### ISSUE TITLE
San Andreas Multiplayer (samp) don't work with dns olny ip (GameQ v2)

### ISSUE THREAD

**Issue by hekut146** [Austinb/GameQ#252]
how to fix this problem?

**Comment by gcphost** [comment]
http://php.net/manual/en/function.gethostbyname.php

**Comment by hekut146** [comment]
don't understand how this link does help me?

**Comment by Austinb** [comment]
What is the hostname you are using?  Host name resolution is dependent upon the dns servers being used to resolve the name.  It is possible the host you are using is unable to resolve the name to an ip address.  It is also possible something is broken in v2.

**Comment by hekut146** [comment]
this proplem only in gta samp status in gameq 2.0 in unturned status in gameq 2.0 work i use one dns in samp and unturned - no-ip - http://www.noip.com/
