### ISSUE TITLE
csgo not return players names

### ISSUE THREAD

**Issue by Supryk** [Austinb/GameQ#258]
cs go sometimes retrn players num but not players names

**Comment by Kandru** [comment]
Do you have an IP + Port for me? Or does this happen on every server? What version of GameQ are you using atm?

**Comment by Supryk** [comment]
that happen on couple server 
first I refresh information - it is ok I can see players name
after 5 minutes i refresh the page and names gone but players still play on that server

eg ips
216.52.148.47:27015 - first from gametracker list
64.74.97.225:27015 - next

**Comment by Austinb** [comment]
You should have some kind of caching layer if you are using GameQ within a web page to display server status.  Many game servers have anti ddos measures which can be triggred by querying a server too rapidly.  If it is not consistently responding it could be that.  

Also you may have your stream_timeout set too low.  Make sure that value is larger than the ping to the server you are querying from the server making the query requests.  Reopen if you have more info.
