### ISSUE TITLE
TeamSpeak 3 returns empty values

### ISSUE THREAD

**Issue by gDayZ** [Austinb/GameQ#259]
error_reporting(E_ALL);
ini_set('display_errors', 1);

include('api/gameq3/Autoloader.php');

$GameQ = new \GameQ\GameQ();
$GameQ->addServer([
    'type'    => 'teamspeak3',
    'host'    => '127.0.0.1:9987', // IP deleted 
    'options' => [
        'query_port' => 10011,
    ],
]);

$results = $GameQ->process();
print_r($results);

the output ist just:

Array ( [127.0.0.1:9987] => Array ( [gq_address] => 127.0.0.1 [gq_dedicated] => [gq_hostname] => [gq_joinlink] => ts3server://127.0.0.1?port=9987 [gq_maxplayers] => [gq_name] => Teamspeak 3 [gq_numplayers] => [gq_online] => [gq_password] => [gq_port_client] => 9987 [gq_port_query] => 10011 [gq_protocol] => teamspeak3 [gq_transport] => tcp [gq_type] => teamspeak3 [players] => Array ( ) [teams] => Array ( ) ) )

Note: IP deleted for security.

**Comment by Austinb** [comment]
Without the ip to test with I am unable to help.  Please reopen if you are still having this issue.
