### ISSUE TITLE
UTF8 and other code page

### ISSUE THREAD

**Issue by AmkCity** [Austinb/GameQ#26]
Can added choise code page in receive data

**Comment by Austinb** [comment]
Hello,

I am sorry I do not understand what you are looking for or to be added.  Can you please elaborate more?

As far as character set the data returned from a query is untouched so if the server information has non-utf8 characters in it you can convert them before you use the data in places.  Not sure I want to add any kind of character set conversions to this project, unless lots of people ask for it.

-Austin

**Comment by AmkCity** [comment]
We'll have to convert each row of result into an array

**Comment by Austinb** [comment]
Can please provide an example of what you are getting as a response and what you want to the response to look like?  I am still not completely understanding the issue or what needs to be solved.

Thanks,
Austin

**Comment by AmkCity** [comment]
my site work UTF8
data receive CP1251

russian nikname and name server is not corectly

**Comment by Austinb** [comment]
Can you provide the ip:port of the server?  I want to take a look.  You can pm it to me if you wish.

As far as changing the code to utf-8 I am not sure I want to add this as part of the core project.  Perhaps it would work as a filter, not sure.  In the mean time try something like this:

```
$data = array_map( function($t){ return is_string($t) ? utf8_encode($t) : $t; }, $data);
```

To change all of the data within the array to utf-8 where necessary.  Note that code snippet as is will probably mess up some of the other nested arrays for things like players list.

**Comment by zeagon** [comment]
It would properbly be a lot easier to just use iconv/utf_encode when you print the results. Utf can be such a pain sometimes

Ive used
[code]
iconv('', 'UTF-8', $var);
[/code]
with great success to detect server locale dates (months) and convert them. Not sure it will work on the given string from another server though. Might as well try it soon
