### ISSUE TITLE
Support for Ark Survival Evolved

### ISSUE THREAD

**Issue by Rustypredator** [Austinb/GameQ#260]
I would like to see support for Ark Surivial Evolved, if this is Possible.
http://www.playark.com/
It seems to be using Source Protocol with default port 7777 and Query Port 27015

**Comment by Verox-** [comment]
You should be able to use `'type' => 'source'` with any game using the Source protocol, unless it's doing something strange with it.

**Comment by Kandru** [comment]
Using the Source protocol works quite fine for me. But I didn't tested all things atm.

**Comment by Rustypredator** [comment]
OK, thanks!
