### ISSUE TITLE
Reign of Kings Support

### ISSUE THREAD

**Issue by xitude** [Austinb/GameQ#261]
Could you provide support for http://www.reignofkings.net/
Server port TCP/UDP: 7350

**Comment by Verox-** [comment]
There doesn't appear to be any method of querying data from a Reign of Kings server as of yet, although it may possibly be added in the future.

https://forums.gameservers.com/viewtopic.php?f=15&t=51750

**Comment by Austinb** [comment]
Until there is a way to query the server it will remain unsupported.

**Comment by xitude** [comment]
There are plenty listing sites for ROK how are they querying the servers
then?

**Comment by Verox-** [comment]
The only ROK listing sites I found had the server administrators manually add their server to the listing site and the only information it could get from it was if it was up or down (which can be achieved by a ping.)
