### ISSUE TITLE
KillingFloor 2 responds with same mapname every time

### ISSUE THREAD

**Issue by Rustypredator** [Austinb/GameQ#264]
So, every of my 3 Kf2 Servers responds with Kf-BurningParis as mapname,
even when there are other maps being played at the moment, every other variable works fine.

On Gametracker they are displayed correctly.

**Comment by Austinb** [comment]
Bug is in the server code with the detail field 'MapName'.  For the correct map name use the 'map' field. Not sure if they are aware of this bug but someone may want to file it.
