### ISSUE TITLE
How can i display a list of players (CS:GO)

### ISSUE THREAD

**Issue by muuvmuuv** [Austinb/GameQ#266]
Hey GameQ-Team,

thanks at all for this nice class. So on, in your example you wrote "Players are never displayed in this example.", but how can i display it. Is there a $server->confiq or something to tell the class it has to?

Hope u can help me soon.
Kind regards
Marvin

**Comment by Verox-** [comment]
The example it's self doesn't display players because it isn't designed to, not because the library is incapable of doing so. The library always retrieves all information the 
Players are stored as an array in `$result['players']`, assuming you are using v2, V3 is similar.
