### ISSUE TITLE
Rust Query Port

### ISSUE THREAD

**Issue by gDayZ** [Austinb/GameQ#269]
After the last patch, the game query doesn't work.

"Master server query port is now shared with game port"

My config looks now like:
$GameQ->addServer([
                'type'    => 'rust',
                'host'    => '185.62.204.109:28215',
                'options' => [
                  'query_port' => 28215 ],
            ]);

before it was:

$GameQ->addServer([
                'type'    => 'rust',
                'host'    => '185.62.204.109:28215',
                'options' => [
                  'query_port' => 28216 ],
            ]);

Both methods doesn't work at all.

**Comment by CameronHall** [comment]
I've just checked this out and confirmed it working.
On both ports 28215 & 28216.
