### ISSUE TITLE
AA3 query

### ISSUE THREAD

**Issue by Feertti** [Austinb/GameQ#27]
After new 3.2 version of AA3 GameQ stopped working.
I have tested this GameQ 2 version but so far I have not got it to work (with plain game server ip and with different query ports).
Only info what I get is that "The server did not respond within the specified time.".

I tested server ports and they should be open but before I contact to my server provider, I'd like to know if someone got this to work .

**Comment by Austinb** [comment]
Hello,

Can you provide a test server with the port for the player connecting and the query port (if different than the game port).  I will look around and see if something has changed like the crypt hash causing the response to fail.

Thanks,
Austin

**Comment by Austinb** [comment]
Ok so did some searching and according to this http://www.gametracker.com/forums/forum.php?site=1&thread=64768#post263768 3.2 changed to source so I have added a source version of aa3 class called as aa3 which uses the source protocol backend to query.  I tested this on a few servers from Gametracker and they worked fine.  I changed the older version to aa3pre32 just to keep it in case people are still running older versions, I assume you can but if not I will remove the class completely.

Also the query port by default is 27020 at game port 8777 but I believe you can change the query port in the server configuration.

Will push up the addition shortly.

Thanks for the heads up was unaware this wasnt working until now. Please let me know if you see any other issues with this specifically. 

Thanks,
Austin

**Comment by Feertti** [comment]
Thank you very much Austin,
I will test my code when I have more time, super nice

Best Regards
Feertti
