### ISSUE TITLE
Lost Heaven Multiplayer Query Protocol

### ISSUE THREAD

**Issue by rststeam** [Austinb/GameQ#270]
Could you please make new GameQ protocol based on provided examples for new LHMP Multiplayer http://lh-mp.eu/

You can download examples here: http://lh-mp.eu/downloads/queryphpexample.zip

Test IP: 178.62.156.36:27050
Thank you

**Comment by Austinb** [comment]
Built but unable to test with your server or servers with any players.  Is there a good time when these servers are busy?  I just need to capture responses so I can add them as tests.

**Comment by Austinb** [comment]
Appears this game/mod is dying or is dead.  If there any active servers that can provide some players to run tests against please reopen this ticket.  Until that time support for this game is beta a best.
