### ISSUE TITLE
Not working anymore (counter strike)

### ISSUE THREAD

**Issue by voxdesign** [Austinb/GameQ#271]
Something went wrong. I cant get any information anymore from counter strike servers.
Please help, i have a website which uses gameq for query servers.
The problem is on my site or something else with this class?
Thank you for your help!

**Comment by voxdesign** [comment]
I forgot: im using v2.
Server to test: 87.229.77.165:27135 (cs16)
Thank you

**Comment by Verox-** [comment]
If it was working and you haven't updated the library then it's 99.% likely to be a problem with your server or the gameserver.

**Comment by voxdesign** [comment]
I havent updated the library.
The gameserver is up and live. (I can see it on gametracker too)
Do you have any idea whats the problem?
I didnt get any information in the server error log file.
Its just not responding.
I downloaded the 'v3' to test. Same result.. it doestn responding.

**Comment by CameronHall** [comment]
What is your query port set to?
