### ISSUE TITLE
Feature Request: Unreal Tournament, Unreal Tournament 2004, Quake

### ISSUE THREAD

**Issue by ragnos** [Austinb/GameQ#272]
Please consider support for UT, UT2004 and Quake-based servers like Alien Arena, War§ow, and others. We are still hosting many servers for those titles, and our tools (most importantly [Easy-Wi](https://github.com/easy-wi/developer)) are depending on this.

**Comment by Austinb** [comment]
If you can provide some active servers I would appreciate it.  Would help in testing when porting the old code to the new library.

**Comment by ulrichblock** [comment]
UT-Server:
UT99: 95.156.230.70:11337, QueryPort is 11338 (+1)
UT2004: 95.156.230.70:15000, QueryPort is 15010 (+10)
UT3 95.156.230.70:30000, Queryport is 30011 (+11)

"Quake"-Server:
Alienarena: 95.156.230.73:27910
War§ow: 95.156.230.70:44400
Teeworlds: 144.76.72.214:8303

**Comment by ulrichblock** [comment]
Any update on this topic?

**Comment by Austinb** [comment]
Sorry for the very long delay.  I have added UT3 to the v3 source.  It was pretty easy given it uses GS3 as its base.  The others I will have to work on.

Please pull down the dev and test it to make sure the response is the same as in v2.  Was hard to make valid tests since the responses from ut3 are wrong more than half the time is seems.

**Comment by ragnos** [comment]
You can't change what the gameserver is reporting. In our case all we need is a valid response to check the servers state, so we can decide if the server has to reboot or shutdown.

Will check this asap. Thank you for your efforts!

**Comment by Austinb** [comment]
- Added ut2004 but was unable to ping your server.  Did it change?
- Added teeworlds
- Working on gamespy for ut
- Alienarena - any info on this protocol? Quick google search didnt reveal very much.

**Comment by ragnos** [comment]
95.156.230.70:15000 (queryport 15010) is up and running. You might try the following alternative servers, all on ip 95.156.230.70:

5555 (LowGrav iCTF)
9999 (iCTF)
18000 (iTDM)
19000 (TDM)
64000 (1on1)
65000 (AM/iDM)

I can't guarantee there are no routing issues between your PC and our servers, but atleast our current Setup with GameQv2 is able to query them, from a seperate network.

**Comment by Austinb** [comment]
It is possible there are routing issues which is why I was asking.  I was able to find some public servers to build tests against so it is not a big deal.  When you have a chance test those protocols to make sure they are behaving the same as v2 (they should as I just ported the code over).

**Comment by Austinb** [comment]
All but alien arena has been ported to v3.  Please open up individual issues for each game you wanted added/ported.  Also let me know if you have any issues.
