### ISSUE TITLE
Feature Request: Terraria TDSM server mod

### ISSUE THREAD

**Issue by skylord123** [Austinb/GameQ#273]
I am working with the devs on the new TDSM server mod for terraria (tdsm.org). The devs gave me this link to help create a protocol for it:

https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/blob/master/Core/Net/Web/ApiControllers/PublicController.cs#L24

If you need any more information let me know. I know you supported TShock in v2 but I don't know about v3. Both of these need to be distinguished between (which is probably obvious).

**Comment by skylord123** [comment]
Updated link to https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/blob/master/Core/Net/Web/ApiControllers/PublicController.cs#L24

**Comment by skylord123** [comment]
Also example output of the public API:
`{"Name":"WorldName","Port":7777,"PasswordRequired":false,"MaxPlayers":8,"Players":["Test"],"Plugins":["TDSM Core Module"],"OTA":"1.0b","Terraria":"v1.3.0.8","ServerState":6}``

And here is a link for testing:
http://showcase.tdsm.org:8448/api/public

**Comment by Austinb** [comment]
Is this tdsm site working anymore?  I can port back Terrria.  Not sure what changes are with this mod. If this mod is still working and what not please reopen with updated references.
