### ISSUE TITLE
Minecraft Query shows online but it's offline?

### ISSUE THREAD

**Issue by gaRt3n** [Austinb/GameQ#275]
As above. Server crashes. Asked Query if online. But it isn't

**Comment by Austinb** [comment]
Which version?

**Comment by FastFelix771** [comment]
I have the same problem, but instead it shows offline while the server is online!
Im on Minecraft 1.4.7, query is active etc.
Im playing on a Modpack if that information is important to you.

**Comment by Austinb** [comment]
As per the wiki the minecraft query protocol only exists in version 1.8+ and you must explicitly enable it.

**Comment by FastFelix771** [comment]
Since 1.8?? Thats crap :D And of course i have it enabled xD
And GameQ works fine with 1.8, 1.7, 1.6 versions. I dont know about 1.5, but i can test if you wish.
Maybe they changed the mechanism from 1.4 to 1.5 update, if so: Could you add an additional Minecraft Query to GameQ for older versions?
