### ISSUE TITLE
Tracking kills and deaths CS:GO ?

### ISSUE THREAD

**Issue by iDentity1337** [Austinb/GameQ#278]
Hey!
So I was wondering if it's possible to track CS:GO stats in details (kills, deaths etc.) using GameQ ?

**Comment by Verox-** [comment]
GameQ is limited by what the query protocol provides, as far as I'm aware the only information regarding that is a score, which is provided.

**Comment by iDentity1337** [comment]
Oh :/ Well, I guess I'll need to learn SourceMod to write a plugin that updates the database each second. Thanks anyways :)

**Comment by Austinb** [comment]
@Verox- is correct.  The information provided in the response is ALL of the information available via the query protocols.  They were built lightweight so a lot of interesting information is missing.  You will have to gather that information by other means such as a log parser or a database hook (be careful).
