### ISSUE TITLE
Arma 3 not showing Details on latest GameQ V2

### ISSUE THREAD

**Issue by stenley** [Austinb/GameQ#279]
It does not show any Serverdetails like Hostname usw...

It works on GameQ 3 but GameQ 3 has no Call of Duty Protocol ):

Here is the Array

https://gyazo.com/cecd9f3f0c4b7db29361e1ed565ca1e4

Use armedassault3 Protocol

**Comment by stenley** [comment]
dayzmod not working to in both gameq2 and gameq3.

**Comment by Verox-** [comment]
Still working for us, check the details are correct and the server is responding correctly.

**Comment by stenley** [comment]
Yes your are right it works. I have used the wrong Port. My Fail can close!
