### ISSUE TITLE
Composer not working

### ISSUE THREAD

**Issue by iGavrilo** [Austinb/GameQ#280]
Hello,

I have problem with your composer command on page http://austinb.github.io/GameQ/. When i type to the composer: composer require austinb/gameq:3.*@stable console type 
![index](https://cloud.githubusercontent.com/assets/16431453/12275635/721a59c6-b971-11e5-8bc7-ea565a8aea2a.png)

**Comment by Austinb** [comment]
For v3 try @dev for now.  Stable is out of date as i've not had much free time to move forward lately.

**Comment by iGavrilo** [comment]
Thank you
