### ISSUE TITLE
Undefined Index

### ISSUE THREAD

**Issue by Ne00n** [Austinb/GameQ#286]
Hey,

I am using your GameQ to determine if players are on the gameservers, but i ran into an issue, maybe you can help me.

When i get my Array back i try to verify if the Gameserver is online with:

if ($results['serv']["gq_online"] === 1) {

After that i try to pull the Data from it:

 $current_players = $results['serv']['gq_numplayers'];
 $current_maxplayers = $results['serv']['max_players'];

So, max_players has sometimes a Undefined index aka empty, how can max_players be empty when gq_numplayers gives a result and gq_online is 1?

Thanks.

**Comment by Austinb** [comment]
If the max_players is missing please provide me with ip:ports where this is not happening.  This is a bug as there should always be a gq_maxplayers key in the returned array.

**Comment by Austinb** [comment]
Please provide an example and reopen this issue if it is still a problem.
