### ISSUE TITLE
GameQ MTA:SA / How to make a beatiful players nicknames output?

### ISSUE THREAD

**Issue by icouldbez1** [Austinb/GameQ#289]
Hello, i tried to output players who are online on the server with help of `print_r($info['players']);` . I used `echo '<pre>';` . It looks better but i wanna output it without showing "Array", "(", ")", "=>". Is it possible?

**Comment by Austinb** [comment]
You can try the following:

``` php
echo '<pre>;
var_dump($info['players]);
```

This will dump the info as the type of the value along with the length (number of characters) - http://php.net/manual/en/function.var-dump.php.

**Comment by icouldbez1** [comment]
checked it,

```
Server name: [DDC] Cross DD
Gamemode: Drunk
Map: Cross ZY DD
Password: No
Players: 13/32
Nicknames:
array(13) {
  [0]=>
  array(6) {
    ["name"]=>
    string(15) "[U1tra]^Smouke."
    ["team"]=>
    string(0) ""
    ["skin"]=>
    string(0) ""
    ["score"]=>
    string(2) "UA"
    ["ping"]=>
    string(2) "71"
    ["time"]=>
    string(0) ""
  }
```

But i want it to be without constants and types. Is there another way to show nicknames only?
For example:

```
Server name: [DDC] Cross DD
Gamemode: Drunk
Map: Cross ZY DD
Password: No
Players: 13/32
Nicknames:
[U1tra]^Smouke.
```

Thanks!

**Comment by Austinb** [comment]
There is nothing in the library for output as that is beyond the scope of the project.  If you want to display the data in a particular way you will have to build it.  You can try to use array_map() or similar function to iterate over the players return and display it how you want.
