### ISSUE TITLE
America's Army 3

### ISSUE THREAD

**Issue by FranziK** [Austinb/GameQ#29]
America's Army 3 after update to version 3.2 does not work anymore!
Could you fix it?

P.S. Thank you for your good script

**Comment by Austinb** [comment]
Hello,

Please update your code for v2.  I pushed up a fix for 3.2+ servers.  For reference please see ticket #27.

If you are having specific issues with the query please feel free to reopen this ticket.  Also, make sure you have the correct port for the server you are querying.  AA3 allows you to change the query port so it may or may not be on the default port of 27020.

**Comment by FranziK** [comment]
Thank you very much, the script works! trying to get the ping player, but the result is displayed empty. How can this be solved? :(
Sorry for my bad english and thank you again! :)

**Comment by FranziK** [comment]
Array ( [my_server] => Array ( [dedicated] => d [game_descr] => America's Army 3.2 (Leased Official) [game_dir] => aa3game [gq_address] => 194.153.116.38 [gq_dedicated] => d [gq_gametype] => [gq_hostname] => [Honor Server] [GerAES] Honor Server [gq_mapname] => Impact [gq_maxplayers] => 24 [gq_mod] => aa3game [gq_numplayers] => 23 [gq_online] => 1 [gq_password] => 0 [gq_port] => 27020 [gq_protocol] => source [gq_transport] => udp [gq_type] => aa3 [hostname] => [Honor Server] [GerAES] Honor Server [map] => Impact [max_players] => 24 [num_bots] => 0 [num_players] => 23 [os] => w [password] => 0 [players] => Array ( [0] => Array ( [id] => 0 [name] => Twister [score] => 2 [time] => 8436.8642578125 [gq_name] => Twister [gq_kills] => [gq_deaths] => [gq_score] => 2 [gq_ping] => ) [1] => Array ( [id] => 0 [name] => NolekMaster [score] => 1 [time] => 6725.2412109375 [gq_name] => NolekMaster [gq_kills] => [gq_deaths] => [gq_score] => 1 [gq_ping] => ) [2] => Array ( [id] => 0 [name] => Ogorski [score] => 1 [time] => 6459.9638671875 [gq_name] => Ogorski [gq_kills] => [gq_deaths] => [gq_score] => 1 [gq_ping] => ) [3] => Array ( [id] => 0 [name] => SkinniNorris [score] => 1 [time] => 6267.1665039062 [gq_name] => SkinniNorris [gq_kills] => [gq_deaths] => [gq_score] => 1 [gq_ping] => ) [4] => Array ( [id] => 0 [name] => beornot [score] => -1 [time] => 5421.5874023438 [gq_name] => beornot [gq_kills] => [gq_deaths] => [gq_score] => -1 [gq_ping] => ) [5] => Array ( [id] => 0 [name] => GermanPunk [score] => 3 [time] => 5290.0268554688 [gq_name] => GermanPunk [gq_kills] => [gq_deaths] => [gq_score] => 3 [gq_ping] => ) [6] => Array ( [id] => 0 [name] => VonNikon [score] => 0 [time] => 5089.6806640625 [gq_name] => VonNikon [gq_kills] => [gq_deaths] => [gq_score] => 0 [gq_ping] => ) [7] => Array ( [id] => 0 [name] => drndadoo [score] => 0 [time] => 4731.8994140625 [gq_name] => drndadoo [gq_kills] => [gq_deaths] => [gq_score] => 0 [gq_ping] => ) [8] => Array ( [id] => 0 [name] => Talovej [score] => 2 [time] => 4705.25 [gq_name] => Talovej [gq_kills] => [gq_deaths] => [gq_score] => 2 [gq_ping] => ) [9] => Array ( [id] => 0 [name] => ^HeaT^Susi [score] => 10 [time] => 4238.6284179688 [gq_name] => ^HeaT^Susi [gq_kills] => [gq_deaths] => [gq_score] => 10 [gq_ping] => ) [10] => Array ( [id] => 0 [name] => skautorion_o [score] => 1 [time] => 3261.9279785156 [gq_name] => skautorion_o [gq_kills] => [gq_deaths] => [gq_score] => 1 [gq_ping] => ) [11] => Array ( [id] => 0 [name] => TheBraveBaboon [score] => 8 [time] => 2763.8830566406 [gq_name] => TheBraveBaboon [gq_kills] => [gq_deaths] => [gq_score] => 8 [gq_ping] => ) [12] => Array ( [id] => 0 [name] => DonSchufro [score] => -2 [time] => 2525.7119140625 [gq_name] => DonSchufro [gq_kills] => [gq_deaths] => [gq_score] => -2 [gq_ping] => ) [13] => Array ( [id] => 0 [name] => .stoffe [score] => -1 [time] => 1982.8968505859 [gq_name] => .stoffe [gq_kills] => [gq_deaths] => [gq_score] => -1 [gq_ping] => ) [14] => Array ( [id] => 0 [name] => rats_._mug [score] => 0 [time] => 1530.8377685547 [gq_name] => rats_._mug [gq_kills] => [gq_deaths] => [gq_score] => 0 [gq_ping] => ) [15] => Array ( [id] => 0 [name] => Restrepo [score] => 1 [time] => 1357.4569091797 [gq_name] => Restrepo [gq_kills] => [gq_deaths] => [gq_score] => 1 [gq_ping] => ) [16] => Array ( [id] => 0 [name] => ColonelMustard [score] => 1 [time] => 906.70642089844 [gq_name] => ColonelMustard [gq_kills] => [gq_deaths] => [gq_score] => 1 [gq_ping] => ) [17] => Array ( [id] => 0 [name] => B1elhen77 [score] => 1 [time] => 607.86871337891 [gq_name] => B1elhen77 [gq_kills] => [gq_deaths] => [gq_score] => 1 [gq_ping] => ) [18] => Array ( [id] => 0 [name] => Wilson [score] => -1 [time] => 506.59957885742 [gq_name] => Wilson [gq_kills] => [gq_deaths] => [gq_score] => -1 [gq_ping] => ) [19] => Array ( [id] => 0 [name] => Kobra [score] => 1 [time] => 468.66540527344 [gq_name] => Kobra [gq_kills] => [gq_deaths] => [gq_score] => 1 [gq_ping] => ) [20] => Array ( [id] => 0 [name] => _._die[+]now_._ [score] => -1 [time] => 401.94650268555 [gq_name] => _._die[+]now_._ [gq_kills] => [gq_deaths] => [gq_score] => -1 [gq_ping] => ) [21] => Array ( [id] => 0 [name] => ^JABOL [score] => 1 [time] => 298.3020324707 [gq_name] => ^JABOL [gq_kills] => [gq_deaths] => [gq_score] => 1 [gq_ping] => ) [22] => Array ( [id] => 0 [name] => CahiR [score] => 0 [time] => 71.590293884277 [gq_name] => CahiR [gq_kills] => [gq_deaths] => [gq_score] => 0 [gq_ping] => ) ) [protocol] => 7 [secure] => 1 [steamappid] => 13140 [teams] => Array ( ) [version] => 49 ) )
