### ISSUE TITLE
Please, add protocols for cod2 and cod4

### ISSUE THREAD

**Issue by yorick1989** [Austinb/GameQ#292]
Hi,

We're using GameQ v2 for years, and we would like to implement v3 of it. What I'd notice was that cod2 and cod4 aren't supported in this new version anymore. Is it possible that they both can be implemented within the current version? I've tried to use 'quake3' as protocol, but then gq_numplayers is always empty, and we'd need that value.

Let us know if this is possible, and if we maybe can do something to get it implemented. I'm not as good as you guys are with PHP code, so that's why I'd request this at you, the original developers.

Thanks for all the work you guys are doing!

Kind regards,

Yorick
FreeGameHosting.eu

**Comment by Austinb** [comment]
In the future please add one server type per issue.  Easier to keep track of this way.
