### ISSUE TITLE
Error querying TS3 server

### ISSUE THREAD

**Issue by Memphis017** [Austinb/GameQ#293]
On V3 If Teamspeak3 server is powered off "stream_socket_client" returns error 10061, this is not happening on V2.0.1

![ts3query_error](https://cloud.githubusercontent.com/assets/17451919/13285061/be5e0e9c-daf8-11e5-94d0-47561be884f5.JPG)

**Comment by Austinb** [comment]
I need a sever to test against so I can see how the handling has changed.  Please provide the ports and ip to connect.  Also what version of php?

**Comment by Memphis017** [comment]
212.83.134.164:9987 / 10011 tested on php 5.6.16. This is only happening when server is off.

**Comment by Memphis017** [comment]
You can try this one too : 195.154.38.37:9987 / 10011, it is stopped and produce above error.

**Comment by kraxarn** [comment]
Had the same issue and fixed it by removing utf8_encode on line 234 in GameQ/Protocols/Teamspeak3.php
#296

**Comment by Austinb** [comment]
@KraXarN I am not sure what you are referring to the issue is an active connection refused warning.  Needs a bit of better error handing.  utf8_encode only runs if there is actually any data being returned.

@Memphis017 I should have a fix shortly.

**Comment by Memphis017** [comment]
Fatal error is gone, still have a bunch of warnings though, thx for the fix.

![capture](https://cloud.githubusercontent.com/assets/17451919/13554623/2b305892-e3ad-11e5-81fb-fdbb61a1c307.JPG)

**Comment by Austinb** [comment]
Are you running with debug mode enabled?  What is the server information?  That appears to be related to a bad connection with the server.

**Comment by Memphis017** [comment]
nope, no debug mode (except php one of course), with debug on i get this :

![capture](https://cloud.githubusercontent.com/assets/17451919/13555666/148b37dc-e3c7-11e5-970c-02f8c364d071.JPG)

It is when querying the second server posted earlier, which is powered off. If there is no server answers (or no server at all !) script must exit silently and return minimum values like in V2, am I right ?

**Comment by Austinb** [comment]
Please pull latest @dev and let me know your result.  Thanks for the help and hopefully this fixes your issue.

**Comment by Memphis017** [comment]
No, thanks to you, this issue is resolved ! That's how you do a good library :+1:
