### ISSUE TITLE
Servers are not queried for some reason

### ISSUE THREAD

**Issue by dmitrijsmihailovs** [Austinb/GameQ#295]
This is what I get when I dump the results

"address-here:27015" => [
    "gq_address" => "address-here"
    "gq_dedicated" => null
    "gq_gametype" => null
    "gq_hostname" => null
    "gq_joinlink" => "steam://connect/address-here:27015/"
    "gq_mapname" => null
    "gq_maxplayers" => null
    "gq_mod" => null
    "gq_name" => "Counter-Strike 1.6"
    "gq_numplayers" => null
    "gq_online" => false
    "gq_password" => null
    "gq_port_client" => 27015
    "gq_port_query" => 0
    "gq_protocol" => "source"
    "gq_transport" => "udp"
    "gq_type" => "cs16"
    "players" => []
    "teams" => []
  ]

It's the same locally on my pc and on production on vps. It was working fine few months ago when I used it. Maybe it needs some php module that i have not enabled or something in configuration?

**Comment by Austinb** [comment]
Need the ip:port of the server you are trying to connect to.  I assume this is v3?  What release are you using?  Latest dev?

**Comment by dmitrijsmihailovs** [comment]
Yes, i'm using v3 latest dev, well, for example, this server cs.gign.lv:27015 (1.6) or this go.gign.lv:27015 (GO)

**Comment by Austinb** [comment]
I tested both servers and they work fine for me with 3.0.4.  

Are you using any kind of hosting provider?  If so some providers block outbound ports as a preventative measure from their servers being used to launch dos attacks.  It is possible your requests are not making it to the game servers you are attempting to query.

**Comment by dmitrijsmihailovs** [comment]
I'm not sure that it's the case, because as i said in original post, it does not work locally, nor on vps(digitalocean) and few months ago this was working fine. I'm not really sure what else could be causing this for me, maybe I am missing some php module or something in php configuration?

**Comment by Austinb** [comment]
Please post your php code you are using to query.  You shouldn't need any other modules for the two types you are querying (shouldnt even need bzip).  If something all of the sudden changed I would rollback to the previous version that worked and see if it still works.  If not then it is possible something on the network side has changed. 

May also check php's memory limit and see what it is doing.  Are there any errors if you run with debug mode enabled?

**Comment by dmitrijsmihailovs** [comment]
Looks like problem was with my code, I was getting server data from db and i had added that options query_port for ts3, now i removed it and it is working fine now.

**Comment by Austinb** [comment]
For teamspeak 3 the query_port option is required due to how teamspeak is laid out with virtual servers.  Please reopen if you are still having issues with the query_port option. Also pull down the latest dev as there were some bug fixes for uncaught exceptions (#293).
