### ISSUE TITLE
TS3 UTF8 Issue

### ISSUE THREAD

**Issue by kraxarn** [Austinb/GameQ#297]
Doesn't query TS3 server if trying to encode utf8 and just crashes.
Removing it works as a workaround.

**Comment by Austinb** [comment]
Just tested on php 5.5.9 with the following

``` php
$gq->addServer([
    'type' => 'teamspeak3',
    'host' => '213.89.41.193:9987',
    'options' => [
        'query_port' => 10011,
    ],
]);
```

And it gave me the output.  Please provide any error messages.  Check your memory limit for php: http://php.net/manual/en/ini.core.php#ini.memory-limit

**Comment by kraxarn** [comment]
Memory limit is currently set to 128M running PHP 7.0.4

EDIT: Managed to fix it, was missing the php7.0-xml package which isn't installed by default. Should be added to the list of requirements.

**Comment by Austinb** [comment]
Can anyone else verify this issue in 7.0.4? utf8_encode has been part of the core software since way back in the php 4 days.

**Comment by Austinb** [comment]
What os and version was this under?

**Comment by Austinb** [comment]
So it appears that ubuntu (and maybe other) os based php distributions have xml as not part of the core installed php package (http://php.net/manual/en/book.xml.php).  GameQ is tested using compiled versions of php not os distributed or other repository based versions.  Will add necessary checks.
