### ISSUE TITLE
Stops working after some time, then gets back if queried frequently.

### ISSUE THREAD

**Issue by zvukoper** [Austinb/GameQ#3]
Hi Austing, it's Mikhail :)

All is working good, except one tiny issue. I don't even sure it's GameQ issue.

I have TS and Arma2 server queries on one simple page showing player list.

If I reload page with my query some few times during one minute then the queries somehow stop receiving replies. I mean connection is established but nothing else. Then in some 5-10 minutes all get's back and works perfectly. If reloads happen not frequent - works fine. If too fast, seems blocked or someting.

Can you guaess what can be the cause and how to deal with it?

P.s. I have only idea of building cache system and query data once in 5 mins by cron table.

Thanks in advance!

**Comment by Austinb** [comment]
Hello,

I would highly recommend a caching layer on top of GameQ.  Most newer game servers have anti-ddos measures to help prevent servers from being attacked. My guess is that Arma2 has something like this.

I would say 5 minutes is a good expiry time.  

Please let me know if you have any other issues.

-Austin

**Comment by zvukoper** [comment]
Thanks, I did exactly what you said and now all is stable.
I'm caching it once in 5 mins.

Here's the implementation (in Russian though :) ) http://ra.velmet.org/arma2/gameq/example.php
