### ISSUE TITLE
teamspeak3 users online

### ISSUE THREAD

**Issue by Supryk** [Austinb/GameQ#300]
teamspeak3 return all server user, better show online online users

**Comment by Austinb** [comment]
I am not sure what your issue is.  Can you please provide a sample server and the output it shows and what it should be showing?  The library is built to return everything the server will return.

Also which version?

**Comment by schoerg** [comment]
I think what OP means is that the Server Query clients count to the total amount of online users.

**Comment by Austinb** [comment]
If you can provide a valid output of a server and show me which values are wrong and what they should be for the given example it would help.  I am unfamiliar with your TS3 handles online vs connected vs whatever user states.

**Comment by schoerg** [comment]
`serverlist`
`virtualserver_id=1 virtualserver_port=9987 virtualserver_status=online virtualserver_clientsonline=44 virtualserver_queryclientsonline=21 virtualserver_maxclients=200 virtualserver_uptime=1731439 virtualserver_name=someserver virtualserver_autostart=1 virtualserver_machine_id
`error id=0 msg=ok`

Queries online: 21
Real voice Clients online: 44-21=23

Output is from the ts3 telnet interface.

**Comment by Supryk** [comment]
v3.0.6

lets say [gq_numplayers] return 2 for my server and that is OK, gametracker show 2 too 

but player array show 

[players] => Array
                (
                    [0] => Array
                        (
                            [clid] => 7
                            [cid] => 22864
                            [client_database_id] => 33609
                            [client_nickname] => nesu
                            [client_type] => 0
                            [gq_id] => 7
                            [gq_team] => 22864
                            [gq_name] => nesu
                        )

```
                [1] => Array
                    (
                        [clid] => 9
                        [cid] => 22844
                        [client_database_id] => 28699
                        [client_nickname] => Unknown from x.x.x.x - IP where gameq is runed - my localhost
                        [client_type] => 1
                        [gq_id] => 9
                        [gq_team] => 22844
                        [gq_name] => Unknown from x.x.x.x - IP where gameq is runed - my localhost
                    )

                [2] => Array
                    (
                        [clid] => 10
                        [cid] => 22864
                        [client_database_id] => 33633
                        [client_nickname] => real_g33
                        [client_type] => 0
                        [gq_id] => 10
                        [gq_team] => 22864
                        [gq_name] => real_g33
                    )

                [3] => Array
                    (
                        [clid] => 39
                        [cid] => 22844
                        [client_database_id] => 1
                        [client_nickname] => Project-Games.eu [BOT]
                        [client_type] => 1
                        [gq_id] => 39
                        [gq_team] => 22844
                        [gq_name] => Project-Games.eu [BOT]
                    )

            )
```

)

[players][0] - OK
[players][1] - not OK because is gameq connect 
[players][2] - OK
[players][3] - not OK this user is on hide channel, normal guest can't see users on his channel, gamtracker dont show him

**Comment by Austinb** [comment]
@schoerg: Is this not what the response is doing now? https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Protocols/Teamspeak3.php#L269

**Comment by Austinb** [comment]
@Supryk:  The library is built to return everything the server query will return.  It is up to the consumer (you) to decide on what to show or not show when displaying results.  If you want to hide specific clients (players) from being shown you can iterate over the loop or use an anonymous function with array_filter and remove any entries with client_type == 1.

If there is a specific bug or something not being returned properly such as the client count then I will fix it. But there are other users of this library who need the full client list returned.

**Comment by schoerg** [comment]
It is, I have not looked into the source code, but merely judged by what OP was writing.
