### ISSUE TITLE
Call of Duty (both 2 and 4) bugs

### ISSUE THREAD

**Issue by Gasjki** [Austinb/GameQ#303]
Hi. Call of Duty games seems to have a little bug with query like: add ^ and some numbers where must be space. Can you check that error too ?

**Comment by Austinb** [comment]
Those ^ with numbers (i.e. ^1) are color codes allowed in quake based games.  They are part of the response from the server and not a bug.  If you wish you remove them you can use the [stripcolors](https://github.com/Austinb/GameQ/wiki/Configuration%20v3#filters) filter and it will remove all color codes from quake and unreal based games leaving just the "normal" strings.

``` php
$gq->addFilter('stripcolors');
```

**Comment by Gasjki** [comment]
Oh. I didn't know. Thank you so much !:)

**Comment by Austinb** [comment]
No worries.
