### ISSUE TITLE
Fwrite problem?

### ISSUE THREAD

**Issue by iGavrilo** [Austinb/GameQ#304]
Hello,

I have some problem with fwrite(). When i try show servers PHP begin shouting:
`fwrite(): send of 9 bytes failed with errno=1 Operation not permitted`

Server is ONLINE and other data are correct.

Thanks

**Comment by Austinb** [comment]
This means it was unable to write to the socket.  What host are you using?  Also what version?

**Comment by Austinb** [comment]
Please reopen with more information.
