### ISSUE TITLE
minecraft hostname

### ISSUE THREAD

**Issue by Supryk** [Austinb/GameQ#309]
in GameQ 3 

hostname print by gq

[gq_hostname] => Â§eÂ§lÂ§k[]Â§7Â§lÂ§k>Â§cÂ§lÂ§k> Â§eÂ§lSURVIVAL Â§aÂ§lGILDIE Â§fÂ§lBOSS Â§cÂ§lÂ§k<Â§7Â§lÂ§k<Â§eÂ§lÂ§k[]

orginal is 
[]>> SURVIVAL GILDIE BOSS <<[]'

ip
87.98.233.189:25565

**Comment by Gasjki** [comment]
I had the same problem and I solved with https://github.com/Austinb/GameQ/issues/99
