### ISSUE TITLE
num_players and most responses are returning blank (Garry's Mod)

### ISSUE THREAD

**Issue by Jerpy** [Austinb/GameQ#310]
I am creating this issue to see if this is even worth looking into, or if anyone else has had this issue. I believe that it may be gmod-specific, as I have tried sourcequery as well and it returns null on occasion. I have tried everything, and at random intervals the server will sometimes respond to the query and sometimes not respond. As far as I'm aware, this is not a server configuration issue. I'm using the latest GameQ as well.
The issue is that the server just simply doesn't return player data. It will return some data, but not all.

For example, in my case I'm querying 15 garry's mod servers. Some will return num_players, some may not even show it. Once I refresh though, it can vary. The ones that had it before may no longer have it, and the ones that didn't can either still not have it or end up with it showing up. This changes on every refresh, so you never know what you're going to get and the query is almost always unreliable. As for something like gq_maxplayers, instead of disappearing, it just returns blank or sometimes the value is given. Again, these variables vary on refresh. I don't know what makes the querying so unstable, and I do not know if it is GameQ or gmod. I also am not 100% sure if it is something on my end. Does anyone have any suggestions?
edit: I should add that I have tested them individually before, and this mostly occurs when it has to query all 15+ servers at once. I don't know if this is a helpful bit of info, but it kind of gives some insight as to when it happens. Right now on my servers page you can't get a moment where all servers were queried successfully. You have to keep refreshing and the numbers will be all over the place. This also seems to happen more the higher the playercount is, but I don't think those two correlate.

Thanks in advance.

**Comment by Austinb** [comment]
What version of the library?

The first thing I would do is make sure you can get all of the into individually from each server.  If that is working then it is possible you are hitting some kind of limit on the network requests from your hosting provider.  Also if you are pinging them over and over many servers have anti-ddos measures to prevent query flooding.  The thresholds vary by server type. 

For tweaking you can try to bump some of the settings in the advanced section of the configuration: https://github.com/Austinb/GameQ/wiki/Configuration%20v3#advanced-settings.  I would look at stream_timeout and make sure this value is larger than the largest round trip ping to the servers in the list.   If this limit is reached before there is a response it will assume the server is down and move on.

**Comment by Austinb** [comment]
Please reopen this issue if you have the ability to provide more information and example servers where this issue is occurring.  Network issues are hard to replicate without being able to test against them directly.
