### ISSUE TITLE
No server results

### ISSUE THREAD

**Issue by lococoder** [Austinb/GameQ#313]
I ran this 

`$GameQ = new \GameQ\GameQ();
   $GameQ->addServer([
               'type' => 'aapg',
               'host' => '104.243.45.229:7778',
                   ]);
       $results = $GameQ->process();`

On all i got back was this result

`<pre>Array
(
    [104.243.45.229:7778] => Array
        (
            [gq_address] => 104.243.45.229
            [gq_dedicated] => 
            [gq_gametype] => 
            [gq_hostname] => 
            [gq_joinlink] => steam://connect/104.243.45.229:7778/
            [gq_mapname] => 
            [gq_maxplayers] => 
            [gq_mod] => 
            [gq_name] => America's Army: Proving Grounds
            [gq_numplayers] => 
            [gq_online] => 
            [gq_password] => 
            [gq_port_client] => 7778
            [gq_port_query] => 26021
            [gq_protocol] => source
            [gq_transport] => udp
            [gq_type] => aapg
            [players] => Array
                (
                )

```
        [teams] => Array
            (
            )

    )
```

)
</pre>  `

no info

**Comment by lococoder** [comment]
I dont know if i am doing something wrong is there anyone who can help? how am i suppose to get the info from the game server? V3

**Comment by theChaosCoder** [comment]
I have the same broken result. Tried also aa3 as type.

**Comment by lococoder** [comment]
well i tried another aapg server ip and it works but no with my ip

**Comment by lococoder** [comment]
wow got it lol how about gametracker was showing incorrect server port of my server so i changed the port it works
