### ISSUE TITLE
Mission Type AAPG

### ISSUE THREAD

**Issue by lococoder** [Austinb/GameQ#315]
I would like to have mission type added for aapg

**Comment by Austinb** [comment]
Aapg uses the Source protocol.  All available information is returned from the server's response.  If it is not in the response now there is no way to access it via the query protocol.  

You may look at the "keywords" response as there is a comma delimited list of keys and values that may have what you are looking for. I can not tell if what you are looking for is in there as many of the keys are not very descriptive.

**Comment by Austinb** [comment]
Please reopen if you can reference documentation for the keywords pairs and I can pull those apart as part of the response to make life a little easier.
