### ISSUE TITLE
TeamSpeak 3 not working on Windows

### ISSUE THREAD

**Issue by trystek** [Austinb/GameQ#319]
I got empty results for TS3 servers.
Tested on: Windows Server 2012 / Windows 8.1, IIS / Apache, PHP 7.0.6

Also tested on V2 with debug and:

> Fatal error: Uncaught GameQ_ProtocolsException: GameQ_Protocols_Teamspeak3::verify_response: Header response was not ok.

Btw debug option not work in V3.

**Comment by Memphis017** [comment]
Working for me, can you provide a test server ?

**Comment by trystek** [comment]
Here is my code:

> <?php
> 
> require_once('../GameQ/Autoloader.php');
> 
> $servers = [
>   [
>       'type' => 'teamspeak3',
>       'host' => 'ts3.ganjaskill.eu:9987',
>       'options' => [
>           'query_port' => 10011,
>       ],
>   ]
> ];
> 
> $GameQ = new \GameQ\GameQ();
> $GameQ->setOption('timeout', 20);
> $GameQ->setOption('debug', TRUE);
> $GameQ->addServers($servers);
> $results = $GameQ->process();
> 
> echo '<pre>'; print_r($results); exit;

And result:

> Array
> (
>     [ts3.ganjaskill.eu:9987] => Array
>         (
>             [gq_address] => ts3.ganjaskill.eu
>             [gq_dedicated] => 
>             [gq_hostname] => 
>             [gq_joinlink] => ts3server://ts3.ganjaskill.eu?port=9987
>             [gq_maxplayers] => 
>             [gq_name] => Teamspeak 3
>             [gq_numplayers] => 
>             [gq_online] => 
>             [gq_password] => 
>             [gq_port_client] => 9987
>             [gq_port_query] => 10011
>             [gq_protocol] => teamspeak3
>             [gq_transport] => tcp
>             [gq_type] => teamspeak3
>             [players] => Array
>                 (
>                 )
>             [teams] => Array
>                 (
>                 )
>         )
> )

Tested with many ts3 servers, today also on Windows 7 with IIS.

**Comment by Memphis017** [comment]
Are you sure about your port ? Because on [Gametracker](https://www.gametracker.com/server_info/5.196.210.216:10194/) there is a server with the same name but port 10194 for connection, and this one is working correctly with GameQ.

With the port you gave indeed there is no response at all. I'm using Windows 2008 R2 and IIS 7.5 on my production platform and it's working flawlessly with my TS3 instance.

I think something must be wrong with your TS3 setup.

**Comment by trystek** [comment]
When I use port 10194, after some time I got:

> Fatal error: in C:\www\Default\GameQ\GameQ.php on line 492

**Comment by naurel06** [comment]
You need to set perm on your TS server to make it work : 
Settings > Options > Advanced permissions system
Permission Menu > Server Groups > Guest

Search for  : 
b_virtualserver_info_view
b_virtualserver_client_list
b_virtualserver_channel_list

And make sure they are all checked. It should work then.

It's not a GameQ bug.

**Comment by Austinb** [comment]
@naurel06 Thanks for the information on the server settings.

@trystek If you are having a specific issue please reopen this issue.
