### ISSUE TITLE
BF4 not working for unknown reason on some server

### ISSUE THREAD

**Issue by naurel06** [Austinb/GameQ#320]
Ok so here's some of my tests : 

FPSNews.net #10 : 5.101.165.172:26200
Result : 

`{"5.101.165.172:26200":{"gq_address":"5.101.165.172","gq_dedicated":null,"gq_hostname":null,"gq_joinlink":"","gq_maxplayers":null,"gq_name":"Battlefield 4","gq_numplayers":null,"gq_online":false,"gq_password":null,"gq_port_client":26200,"gq_port_query":48200,"gq_protocol":"bf3","gq_transport":"tcp","gq_type":"bf4","players":[],"teams":[]}}`

It goes the same for all FPSNews.net servers (you can find them here : https://www.gametracker.com/search/bf4/FR/?query=FPS )

Now the same code with another server is working (even if the port isn't 25200 wich is the default one). I've made tests on several servers and I've got like 50% chance of working.

Where does it come from ? Is it a banning IP issue (like my IP got banned ?) ? Is there a way for the provider to not return the query ? If so how gametracker manage to get data ?

**Comment by Austinb** [comment]
There are anti-ddos measures in a lot of games.  If you ask for too many requests in a short period of time it is possible you can be blocked by the server.  Another possibility is there is a routing issue or the host is blocking the ports required for querying.

**Comment by naurel06** [comment]
Might be the query port thank you.
