### ISSUE TITLE
~Minecraft Name not appearing

### ISSUE THREAD

**Issue by zer0sec** [Austinb/GameQ#321]
Hi, i'm using gameq with boot strap but minecraft is the only one that isn't displaying the name it's ping the ip and showing online just not showing the server name... or motd is there anyway to make it show motd as server name?

**Comment by Austinb** [comment]
Unless something has changed with the protocol what is returned is all that is available via the query protocol. 

If you are having issues with results please provide the connection information so I can test.

**Comment by zer0sec** [comment]
the ip and port is 37.59.9.124:25565
My custom server page is https://servers.gamingreborn.co.uk

**Comment by zer0sec** [comment]
Fixed it thanks anyways. for some reason if minecraft is running custom jar it won't detect server name/motd
