### ISSUE TITLE
Cod 4 - Server not found fix

### ISSUE THREAD

**Issue by SOD96** [Austinb/GameQ#323]
Hi all.

Was having an issue with what I am using GameQ for. I want to scan servers and there is a chance that someone entering in the wrong details I need to take account for this.

When you do this for cod 4 it responds in this error message:
ErrorException in Quake3.php line 113:
array_key_exists(): The first argument should be either a string or an integer

After checking this I have added in the following lines to 109-112

```
    if ($header == false)
    {
        throw new Exception(__METHOD__ . " response type '" . bin2hex($header) . "' is not valid");
    }
```

This allows me to account for the server being offline and returns null values and data that I need :)

Maybe you can patch this in or you have a better way of doing it. I would do it myself but I have no idea how to do this via git.

Many thanks..

-Sean

**Comment by Austinb** [comment]
I assume this is version 3.  Are you running in debug mode?

**Comment by SOD96** [comment]
This is version 3, I am running GameQ as it came default. If debug mode is off then it is off for me too.

**Comment by Austinb** [comment]
Can you send me an example of a bad entry that has caused this response?  I can make something up on my end but I want to make sure your case is tested as well.

**Comment by SOD96** [comment]
Issue is resolved. Thank you.
