### ISSUE TITLE
Getting information of an offline Game Server

### ISSUE THREAD

**Issue by SOD96** [Austinb/GameQ#324]
Hi there,

Back again. When scanning a server that is offline I receive the following error:

  [ErrorException]
  fwrite(): send of 7 bytes failed with errno=111 Connection refused

This happens if the game server has been shutdown. Which means that port is going to be closed.

This was a GMOD server running on port 25565.

Any tips on this? Ideally I'd like to catch this and continue running through all the servers in the list but it halts everything.

**Comment by SOD96** [comment]
Just to add. This does not happen on my local windows install. Only on my Linux Server.

**Comment by Austinb** [comment]
Are you running in debug mode? Version 3?

**Comment by SOD96** [comment]
I haven't changed any settings since setting it up, If debug mode is default off, then it's off.

Version 3 yes.

**Comment by Austinb** [comment]
Is this a local server?  Can you send an ip:port of one that throws the error for you now?  You can message me it if you wish.

**Comment by Austinb** [comment]
Pushing up changes.  Please test with dev branch and let me know how it goes.  I will tag another release with this once this is verified and some other changes/fixes are pushed up.

**Comment by SOD96** [comment]
Resolved my issue 100% Thanks mate :)
