### ISSUE TITLE
Doesn't work with latest php

### ISSUE THREAD

**Issue by zer0sec** [Austinb/GameQ#325]
It says it support latest version but for me doesn't work with php 5.6 or above :( only works on 5.5 if i go above it shows all servers offline

**Comment by Austinb** [comment]
Appears travisci does not keep up with versions very well.  I have forced all version testing to the lastest GA versions of php.  Running a build and will see what happens. 

In the mean time what version did you have before when it worked?

**Comment by zer0sec** [comment]
hmm it seems to be working now but before i enabled 5.6 it was working but next day i checked and it wasn't working so i'll keep you posted see if it stops working by tomorrow.

**Comment by Austinb** [comment]
Well let me know what version. It is possible it is something else on the server causing an issue such as a module.

I updated the tests to test the latest versions of php that it supports and they all passed - https://travis-ci.org/Austinb/GameQ/builds/147234440.  Tests cover most of the library but not all so it is possible there is something you are seeing that is not being tested.

**Comment by zer0sec** [comment]
It's still working now was strange i think it was mod security effecting it
