### ISSUE TITLE
Not displaying any information about servers

### ISSUE THREAD

**Issue by zacwebb** [Austinb/GameQ#326]
Hi there, I am using the following PHP to grab some information from a server (used Garry's Mod as an example) and for some reason (no matter what server or game I use) it is not returning any information:

``` <?php
require_once('GameQ/src/GameQ/Autoloader.php');

// Define the servers you wish you query
$servers = [
    [
    'type'    => 'gmod',
    'host'    => '108.61.251.226:27015',
    ]
];

$GameQ = new \GameQ\GameQ(); // or $GameQ = \GameQ\GameQ::factory();
$GameQ->addServers($servers);
$GameQ->setOption('timeout', 5); // seconds

$results = $GameQ->process();
print_r($results);
?>
```

This results in this being outputted to the browser:
`Array ( [108.61.251.226:27015] => Array ( [gq_address] => 108.61.251.226 [gq_dedicated] => [gq_gametype] => [gq_hostname] => [gq_joinlink] => steam://connect/108.61.251.226:27015/ [gq_mapname] => [gq_maxplayers] => [gq_mod] => [gq_name] => Garry's Mod [gq_numplayers] => [gq_online] => [gq_password] => [gq_port_client] => 27015 [gq_port_query] => 27015 [gq_protocol] => source [gq_transport] => udp [gq_type] => gmod [players] => Array ( ) [teams] => Array ( ) ) )
`

I am on the latest version (v3).
Thanks in advance

**Comment by zacwebb** [comment]
@Austinb would you be able to point me in some direction when you get a spare moment.
Thanks

**Comment by Austinb** [comment]
I am unable to connect to that server.  It is possible the query port is being blocked at the server or network level.  Unfortunately there is nothing the script can do.  If you are managing that server contact your server provider and ask them about opening up the required query ports for the server.

**Comment by Austinb** [comment]
Please reopen if you have any more info.  Unfortunately there is nothing the library can do about blocked ports.
