### ISSUE TITLE
Ace of Spades Classic

### ISSUE THREAD

**Issue by ludgart** [Austinb/GameQ#328]
Hello,

could you add the old Ace of Spades Classic game to GameQ?
Homepage: http://buildandshoot.com/

Thanks

**Comment by naXe90** [comment]
and Project Reality please :)

**Comment by Austinb** [comment]
@ludgart I need links to any server documentation available.  Please provide that and will look into adding support.  If there is no server query protocol available I will be unable to provide support.

**Comment by Austinb** [comment]
@naXe90 One game per issue.  Open a new issue if you are requesting a new game/mod to be supported.

**Comment by ludgart** [comment]
Hello, 

Sorry for the bad information about this game, but 
I found a query file:
https://github.com/learn-more/pysnip-utils/blob/master/scripts/query.py
I hope the file is helpful.
