### ISSUE TITLE
Project Reality

### ISSUE THREAD

**Issue by naXe90** [Austinb/GameQ#329]
Could you add the Project Reality game to GameQ?
Homepage: http://www.realitymod.com/

Thanks

**Comment by Austinb** [comment]
@naXe90 Does this not work with the standard BF2 query?

**Comment by naXe90** [comment]
No

**Comment by Austinb** [comment]
It appears that this does use the same protocol as BF2.  I used what servers I could find outside of http://www.realitymod.com/prspy/ because it does not show the ip on that listing.
