### ISSUE TITLE
Problems with Cyrillic

### ISSUE THREAD

**Issue by OleksandrWebLab** [Austinb/GameQ#333]
Hello! I often have a problem with the server name and maps in Cyrillic.

If the name is written in Cyrillic - in 1 of 100 servers Incorrect characters appear:
"╨С╨░╤В╤М╨║╨░ ╨Ф╨╕╨│╨╗╨╛╨▓".

I found a simple and elegant solution that works in 70% of cases, problems with the Cyrillic alphabet, the remaining 30% of cases - an empty name is written, and I'm quite satisfied:

``` php
$host_ip_old = $results['gq_hostname'];
$host_ip_new = @iconv("UTF-8", "CP866", $host_ip_old);

if (strlen($host_ip_new) < strlen($host_ip_old)/2) {
    $results['gq_hostname'] = $host_ip_new;
} else {
    $results['gq_hostname'] = $host_ip_old;
}


$host_map_name_old = $results['gq_mapname'];
$host_map_name_new = @iconv("UTF-8", "CP866", $host_map_name_old);

if (strlen($host_map_name_new) < strlen($host_map_name_old)/2) {
    $results['gq_mapname'] = $host_map_name_new;
} else {
    $results['gq_mapname'] = $host_map_name_old;
}
```

Why I sent two identical code? Just because most server problems in the server name. Today, found that in the map name of SAMP - also there is a problem

**Comment by Austinb** [comment]
@PopcornPHP can you provide some test servers?  All of the returns should be utf8 encoded but it is possible it is missing for SAMP.  

I need a list of server connect info and the game types so I can build tests.
