### ISSUE TITLE
Same IP, different ports - error

### ISSUE THREAD

**Issue by Gasjki** [Austinb/GameQ#337]
Hi. I just tried to a CS:GO server and an ARK:SE server and they have same ip, but different port. The problem is that is only query csgo everytime even if i check 10 times port and game to be write well. What's the problem ?

**Comment by Lasim** [comment]
What error message do you get?
Paste your gameq php code as well please.

**Comment by Gasjki** [comment]
I don't get any errors, only the same details...

**Comment by Austinb** [comment]
Need the code snippet you are using.  Please provide that and reopen so we can test the responses.

**Comment by Gasjki** [comment]
I used this classic version: 

```
$GameQ = new \GameQ\GameQ();
$GameQ->addServer([
    'type' => 'css',
    'host' => '127.0.0.1:27015',
]);
$results = $GameQ->process();
```

I can't remember the ip that I tested. I

First, I tested this Ip like this: game = csgo, and ip:27015 and then, game = arkse and ip:port. Everytime I've got CS:GO stats even if I checked 10 times the code I wrote.
