### ISSUE TITLE
type => arkse (doesn't work), source (works)

### ISSUE THREAD

**Issue by Exorion1er** [Austinb/GameQ#341]
Hi,

I don't know if it's intended but the code below doesn't work
`$GameQ = new \GameQ\GameQ();
        $GameQ->addServer([
            'type' => 'arkse',
            'host' => $address . ':' . $port_query
            ]);
        $final = $GameQ->process();`
but if I change 'arkse' to 'source' it works.
This doesn't happen on every server though.
Server that works with arkse as type : odyn.fr with default ports (7777 and 27015)
Server that doesn't work with arkse as type : 173.234.25.146 with ports 27039 for both query and connect.
Here's another that doesn't work :  138.201.132.151 with ports 8888 and 27020 for query.
Both those examples work with source as type.
My guess would be something to do with ports ?

If you need more information, feel free to ask.
Thanks in advance !

**Comment by Austinb** [comment]
For the servers that are not working do you know what the client connect port is?  

Arkse uses the Source protocol for the server status information.  The issue appears to be in the port math when passing the client port when adding the server to be queried.  The default is 7777 which it adds a fixed amount to get to the default port of 27015.  When you pass 8888 it does the same math but it is possible the port it is calculating it wrong. If you pass the query port directly using https://github.com/Austinb/GameQ/wiki/Examples%20v3#different-client-and-query-ports as a guide does it work properly?

Can you give me a list of the ips, client ports and query ports for servers that work as well as ones you are having issues with?  I will need to test them to see if it is the port math or something else.

**Comment by Austinb** [comment]
Please open this issue back up if you are still having problems and can provide more information to replicate the issue you are seeing.
