### ISSUE TITLE
The problem with the addition of the list of players

### ISSUE THREAD

**Issue by SeeqWeak** [Austinb/GameQ#347]
Hello, I have a problem with the addition of a list of players and their stats my code:
Please targeting me what and where, because I'm new at this.

`<?php

	require_once __DIR__ .'/GameQ/Autoloader.php';
	$servers = [
		[
			'type'   => 'csgo', 
			'host'   => '',
		],
	];
	
	$gq = new \GameQ\GameQ(); 
	$gq->addServers($servers);
	$gq->setOption('timeout', 10);
	$gq->addFilter('normalize');
	$results = $gq->process();
	
	$i = 0;
	$n = count($servers);
	
	foreach($results as $server) {
		$url[$i] = $server['gq_joinlink'];
		$icon[$i] = '/'.$servers[$i]['type'].'.png';
		$desc[$i] = $server['gq_name'];
		
		if($server['gq_hostname'] == "") {
			$hostname[$i] = 'n/a';
			$players[$i] = 'Brak Graczy';
			$players_num[$i] = 0;
			$players_max[$i] = 0;
			$status[$i] = '<span class="ipsBadge ipsBadge_negative"></i> Wyłączony</span>';
			$map[$i] = 'n/a';
			$mapimage[$i] = '<img src="http://image.www.gametracker.com/images/maps/160x120/nomap.jpg">';
			$perc[$i] = 0;
		} else {
			$hostname[$i] = $server['gq_hostname'];
			$players[$i] = $server['players'];
			$players_num[$i] = $server['gq_numplayers'];
			$players_max[$i] = $server['gq_maxplayers'];
			$status[$i] = '<span class="ipsBadge ipsBadge_positive"></i> Włączony</span>';
			$map[$i] = $server['gq_mapname'];
			$mapimage[$i] = '<img src="http://image.www.gametracker.com/images/maps/160x120/'.$servers[$i]['type'].'/'.$map[$i].'.jpg" alt="'.$map[$i].'">';
	
			$perc[$i] = round($players_num[$i]/$players_max[$i]* 100, 0);
		    }	
	    $i++;
	}
?>`

**Comment by naXe90** [comment]
Jesteś w tym nowy, przecież napisałeś "swoją" aplikację Server List pod IPS4.
Haha, żałosny jesteś ;)

**Comment by SeeqWeak** [comment]
naXe90, o czym mowa? Nigdy jeszcze nic nie napisałem. A ten kod który jest wyżej jest od Czarka.

**Comment by naXe90** [comment]
Nie ośmieszaj się, bo to nie przejdzie.

**Comment by SeeqWeak** [comment]
Ośmieszam się? Czym? Że nigdy jeszcze nic nie napisałem czy że jestem w tym nowy? Bo nie wiem co masz na myśli.

**Comment by Austinb** [comment]
So is this issue still occurring or have you resolved it?
