### ISSUE TITLE
Minecraft not working

### ISSUE THREAD

**Issue by xFlip** [Austinb/GameQ#35]
Hi,

thanks for this Library!

I have a Bug with minecraft.
I enabled the query on the server but i get this bug:

Fatal error: Uncaught exception 'GameQException' with message 'length OOB' in /var/www/web5/html/interface/system/gameq/buffer.php:106 Stack trace: #0 /var/www/web5/html/interface/system/gameq/buffer.php(282): GameQ_Buffer->read(2) #1 /var/www/web5/html/interface/system/gameq/protocols/gamespy3.php(131): GameQ_Buffer->readInt16() #2 /var/www/web5/html/interface/system/gameq/protocols/gamespy3.php(203): GameQ_Protocols_Gamespy3->preProcess_all(Array) #3 [internal function]: GameQ_Protocols_Gamespy3->process_all() #4 /var/www/web5/html/interface/system/gameq/protocols/core.php(547): call_user_func_array(Array, Array) #5 /var/www/web5/html/interface/system/GameQ.php(452): GameQ_Protocols_Core->processResponse() #6 /var/www/web5/html/interface/system/GameQ.php(434): GameQ->filterResponse(Object(GameQ_Protocols_Minecraft)) #7 /var/www/web5/html/interface/overview.php(60): GameQ->requestData() #8 /var/www/web5/html/interface/index.php(25): include('/var/www/web5/h...') #9 {main} thrown in /var/www/web5/html/interface/system/gameq/buffer.php on line 106

I am using Bukkit 1.2.5 R4

All other Games (ts3, css, tf2) are working! But when i add the Minecraft server, all is crashing.

Thank you!

**Comment by Austinb** [comment]
Can you provide the server ip:port in a private message?  I want to test against it. Also make sure you have the port open in the settings. 

```
enable-query=true
query.port=25565
```

**Comment by xFlip** [comment]
Thank you for the fast answer!

Yes the settings are right cause when i start the Server this appears in the console:

18:22:46 [INFO] Starting GS4 status listener
18:22:46 [INFO] Query running on  IP:25565

I send you now the IP:Port!
