### ISSUE TITLE
Returns empty data on production, on local everything OK

### ISSUE THREAD

**Issue by Albert221** [Austinb/GameQ#350]
Hello, I have a problem on my production server.

```
/usr/local/php/p56/bin/php -r 'require "vendor/autoload.php"; $gameq = new GameQ\GameQ();$gameq->setOption("debug",true); $gameq->addServer(["type"=>"csgo","host"=>"193.33.176.95:27015"]);var_dump($gameq->process());'
```

returns 

```php
array(1) {
  ["193.33.176.95:27015"]=>
  array(19) {
    ["gq_address"]=>
    string(13) "193.33.176.95"
    ["gq_dedicated"]=>
    NULL
    ["gq_gametype"]=>
    NULL
    ["gq_hostname"]=>
    NULL
    ["gq_joinlink"]=>
    string(36) "steam://connect/193.33.176.95:27015/"
    ["gq_mapname"]=>
    NULL
    ["gq_maxplayers"]=>
    NULL
    ["gq_mod"]=>
    NULL
    ["gq_name"]=>
    string(32) "Counter-Strike: Global Offensive"
    ["gq_numplayers"]=>
    NULL
    ["gq_online"]=>
    bool(false)
    ["gq_password"]=>
    NULL
    ["gq_port_client"]=>
    int(27015)
    ["gq_port_query"]=>
    int(27015)
    ["gq_protocol"]=>
    string(6) "source"
    ["gq_transport"]=>
    string(3) "udp"
    ["gq_type"]=>
    string(4) "csgo"
    ["players"]=>
    array(0) {
    }
    ["teams"]=>
    array(0) {
    }
  }
}
```

on my production server, while on my local server everything is ok. When I'm pinging this ip on my production server everything is OK too (~30ms). I have bzip2 extension and PHP5.6 on both servers. This problem happens with all IPs. What could be possible cause of it? Maybe it needs some php.ini settings which my hosting provider has disabled or something like that?

Regards

**Comment by Austinb** [comment]
Check your host to make sure it allows you to make outbound connects on non-standard ports.  Many hosting providers do not let you do this.  Verify you can make outbound requests on random ports with your hosting provider.

**Comment by Albert221** [comment]
Yes, it's because of their firewall. Thanks.
