### ISSUE TITLE
Squad game and/or Unreal Engine 4

### ISSUE THREAD

**Issue by naXe90** [Austinb/GameQ#354]
Could you add the Squad game and/or Unreal Engine 4 to GameQ?

Thanks

**Comment by Austinb** [comment]
@naXe90 You have any query documentation available?  Also you have a server with a known query port? Appears query ports can be customized.

**Comment by naXe90** [comment]
Server list: https://squad-servers.com/
http://forums.joinsquad.com/topic/9559-query-ports/

**Comment by Austinb** [comment]
@naXe90 Appears to just be A2S.
