### ISSUE TITLE
Add Days of War support

### ISSUE THREAD

**Issue by TacTicToe66** [Austinb/GameQ#356]
`<?php
/**
 * This file is part of GameQ.
 *
 * GameQ is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * GameQ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace GameQ\Protocols;

/**
 * Class Days of War
*/

class Dow extends Source

{

    /**
     * String name of this protocol class
     *
     * @type string
     */
    protected $name = 'dow';

    /**
     * Longer string name of this protocol class
     *
     * @type string
     */

    protected $name_long = "Days of War";

    protected $normalize = [
        // General
        'general' => [
            // target       => source
            'gametype'   => 'G_s',
            'hostname'   => 'ONM_s',
            'mapname'    => 'MPN_s',
            'maxplayers' => 'P_i',
            'numplayers' => 'N_i',
        ],
        // Individual
        'player'  => [
            'name'  => 'name',
            'score' => 'score',
            'time'  => 'time',
        ],
    ];
	
	    /**
     * query_port = client_port + 19238
     * 27015 = 7777 + 19238
     *
     * @type int
     */
    protected $port_diff = 19238;
}`

Code above did not work, which does not make sense. It is using the source query. When I use Xpaw's sourcequery it works and I get the info returned. Obviously I am missing something as my php knowledge is not on par with yours.  This is the info returned from using Xpaw Source Query at below link.

http://gameservertrack.com/xpaw/Examples/

IPs for testing

199.60.101.90:27015
31.186.250.10:27015

Sorry to have to keep bothering you, but it is a bit confusing. I am trying to learn so I dont have to bother you as much and can actually start contributing.  :)

**Comment by Austinb** [comment]
@TacTicToe66 It was close except you had the port_diff defined when it was not needed which is why you were not getting a response.  This game like most A2S games have the query port on the same port as the client connect port. The port_diff properly is only needed if the query port is different and the game follows some kind of pattern with their ports.

**Comment by Austinb** [comment]
Also there appears to be no player information response currently.  Not sure if that is an oversight or what but the response from that packet is empty from the 2 servers I was able to test.
