### ISSUE TITLE
Sometimes empty results?

### ISSUE THREAD

**Issue by thisbesonic** [Austinb/GameQ#361]
First of all: Great work on this! I appreciate it. :+1: 

Now for my problem.
How come some response values are sometimes empty for some servers?

    [85.25.100.171:28961] => Array
        (
            [gq_address] => 85.25.100.171
            [gq_gametype] => 
            [gq_hostname] => 
            [gq_joinlink] => 
            [gq_mapname] => 
            [gq_maxplayers] => 
            [gq_mod] => 
            [gq_name] => Call of Duty 4
            [gq_numplayers] => 
            [gq_online] => 
            [gq_password] => 
            [gq_port_client] => 28961
            [gq_port_query] => 28961
            [gq_protocol] => quake3
            [gq_transport] => udp
            [gq_type] => cod4
            [players] => Array
                (
                )

            [teams] => Array
                (
                )

        )

I would like GameQ to always return a full set of stats.
Using the old and outdated [phgstats](https://sourceforge.net/p/phgstats/mailman/phgstats-devel/) I always get all stats of all servers and I don't know where the problem lies when using the GameQ library.

I query one root server with 13 different ports for each gameserver. 
The server has an average response time of  8 ms. 
Either the timeout option has no effect at all, or I am 

I tried increasing value of the timeout option, but it has no effect at all, or I am using it the wrong way. 
 `$GameQ->setOption('timeout', 3600); // seconds`

I don't understand much about the UDP protocol and sockets, but I would really like to ditch phgstats and use this library instead. Anything I could have missed or something else I can try?

Greetings,
~slotty

EDIT: I just saw this is related to #360 , it says "Some checks were not successful" does it work though?

EDIT2: Increasing the stream_timeout did not help either. 
`$GameQ->setOption('stream_timeout', 2000000);`

**Comment by thisbesonic** [comment]
Okay. Removing `$streams <= 0` from [here](https://github.com/Austinb/GameQ/blob/v3.0.10/src/GameQ/Query/Native.php#L186) and wait for the response to timeout to finish as @fritzmg mentioned in #360, does actually better the result. However some servers are still empty sometimes (not always). 

[Phgstats](https://sourceforge.net/p/phgstats/mailman/phgstats-devel/) gets them all in 8 ms every time though ...
Phgstats just doesn't support as many games as this library though.

**Comment by thisbesonic** [comment]
for some odd reason everything seems to be working now. 
Maybe because of not setting the timeout option.

    require_once WCF_DIR . 'lib/system/api/gameq/src/GameQ/Autoloader.php';
    $GameQ = new \GameQ\GameQ();
    $GameQ->addServers($req_servers);
    
    // $GameQ->setOption('timeout', 3);
    // $GameQ->setOption('stream_timeout', 200000);
    // $GameQ->setOption('write_wait', 500);
    
    $GameQ->addFilter('normalize');
    $GameQ->addFilter('secondstohuman');
    $GameQ->addFilter('stripcolors');
    
    return $GameQ->process();

**Comment by Austinb** [comment]
@slottybon Is it possible to provide the list of servers you are querying?  How large is the list?

**Comment by thisbesonic** [comment]
uh, sorry for the late reply. But as I said already, it works just fine now. So no need to reopen.
If you still want to investigate though, here you go:

    $reqServers = [
        ['type' => 'cod4', 'host' => '88.99.92.218:28960'],
        ['type' => 'cod4', 'host' => '88.99.92.218:28962'],
        ['type' => 'cod4', 'host' => '88.99.92.218:28961'],
        ['type' => 'cod4', 'host' => '88.99.92.218:28963'],
        ['type' => 'cod4', 'host' => '88.99.92.218:28964'],
        ['type' => 'cod4', 'host' => '88.99.92.218:28965'],
        ['type' => 'cod4', 'host' => '88.99.92.218:28966'],
        ['type' => 'cod4', 'host' => '88.99.92.218:28967'],
        ['type' => 'cod4', 'host' => '88.99.92.218:28930'],
        ['type' => 'cod4', 'host' => '88.99.92.218:28968'],
        ['type' => 'cod4', 'host' => '88.99.92.218:28950'],
        ['type' => 'cod4', 'host' => '88.99.92.218:28940'],
        ['type' => 'cod4', 'host' => '88.99.92.218:28920'],
    ];

again, awesome work you did.
Have a nice day.
