### ISSUE TITLE
Trying to figure out how to make a query page for my servers

### ISSUE THREAD

**Issue by CoZmicShReddeR** [Austinb/GameQ#363]
Can you please explain your code by making me an example?

I want to have a page I can inframe to my Xenforo Portal page
www.cozworld.com

I want to make a block with map name, map pic, user count and player names in game  

No More Room in Hell (HL2 Deathmatch)
208.86.251.31:27055
208.86.251.32:27055
208.86.251.33:27055
208.86.251.35:27055

**Comment by Austinb** [comment]
I would start here https://github.com/Austinb/GameQ/wiki/Examples-v3 to see what data is being returned.  The server information is returned in a zero-index array and you will need to iterate over the array to get the information you are looking for.  If you have specific issues such as a server not responding or not returning any info please let me know. This library just provides the servers' responses so you will need to write the code to extract and display the returned information.

**Comment by CoZmicShReddeR** [comment]
Yeah it works I was just wondering if anyone made anything I could use? I am not a coder but would like to see something that was made that shows servers, players and map pics in one block.
