### ISSUE TITLE
If server offline => gq_online is true?!

### ISSUE THREAD

**Issue by DAThosting** [Austinb/GameQ#364]
Hi,

if a server, in my tests minecraft, is offline the gq_online parameter is still 1.
Should be 0, or am I wrong?
Is it possible to check the online status at all?
The server is at the moment offline, if you want to check that.

If offline:
`Array ( [213.202.221.200:25565] => Array ( [dedicated] => 1 [gq_address] => 213.202.221.200 [gq_dedicated] => 1 [gq_gametype] => [gq_hostname] => [gq_joinlink] => minecraft://213.202.221.200:25565/ [gq_mapname] => [gq_maxplayers] => [gq_name] => Minecraft [gq_numplayers] => [gq_online] => 1 [gq_password] => 0 [gq_port_client] => 25565 [gq_port_query] => 25565 [gq_protocol] => gamespy3 [gq_transport] => udp [gq_type] => minecraft [password] => 0 [players] => Array ( ) [teams] => Array ( ) ) )`

If online:
`Array ( [213.202.221.200:25565] => Array ( [dedicated] => 1 [game_id] => MINECRAFT [gametype] => SMP [gq_address] => 213.202.221.200 [gq_dedicated] => 1 [gq_gametype] => MINECRAFT [gq_hostname] => A Minecraft Server [gq_joinlink] => minecraft://213.202.221.200:25565/ [gq_mapname] => world [gq_maxplayers] => 12 [gq_name] => Minecraft [gq_numplayers] => 0 [gq_online] => 1 [gq_password] => 0 [gq_port_client] => 25565 [gq_port_query] => 25565 [gq_protocol] => gamespy3 [gq_transport] => udp [gq_type] => minecraft [hostip] => 213.202.221.200 [hostname] => A Minecraft Server [hostport] => 25565 [map] => world [maxplayers] => 12 [numplayers] => 0 [password] => 0 [players] => Array ( ) [plugins] => CraftBukkit on Bukkit 1.10.2-R0.1-SNAPSHOT [teams] => Array ( ) [version] => 1.10.2 ) )`

PHP: 5.6.30-0+deb8u1
GameQ: 3.0.10 (standalone)
Apache2: 2.4.10

Regards

**Comment by grohsfabian** [comment]
Hey,

**Easy fix**

Open up **GameQ/Protocols/Minecraft.php** and remove these 2 lines
`        $result['dedicated'] = 1; // All servers are dedicated as far as I can tell
        $result['password'] = 0; // Unsure if you can password servers, cant read that value
`


From the `processResponse()` function.

:)

**Comment by DAThosting** [comment]
Nice thank you :) :+1:
