### ISSUE TITLE
Conan Exiles

### ISSUE THREAD

**Issue by Gasjki** [Austinb/GameQ#366]
Hi. I made a copy of CS:GO protocol and I tested few Conan Exiles servers and everything worked fine. Now, I have this IP & Port: 212.129.8.90:27115 and all I get is an empty array. Can you help me with a solution ? Thank you !

**Comment by Gasjki** [comment]
I tested also with CS 1.6 protocol and I've got the same error.

**Comment by Austinb** [comment]
The protocol is Source (A2S).  The issue is when the server is not using the standard 27015 port for the connect you will need to pass the query port option since the query port is still 27015 by default. 

```php
$gq->addServer([
    'type' => 'conanexiles',
    'host' => '193.111.186.177:7777',
    'options' => [
        'query_port' => 27015,
    ],
]);
```

**Comment by Gasjki** [comment]
Hi,

Thank you for reply. Another question: It's possible to be the same problem with ARK: Evolve ??

**Comment by Austinb** [comment]
It is possible if the server is allowed to specify the query port.  There is a default offset for that game from the connect port but if the server is able to change the port in the configuration you will need to know the query port before you can get any information.  This also assumes the port is not blocked by a firewall.
