### ISSUE TITLE
Unreal Tournament (4) Alpha Support

### ISSUE THREAD

**Issue by hurdad** [Austinb/GameQ#368]
I have been trying to figure out how to query UT4 servers. Have you guys looked into it yet?

**Comment by Austinb** [comment]
@hurdad Is there any documentation on how to query UT4 servers?  Anyone know what protocol it is using like Source?

**Comment by hurdad** [comment]
@Austinb I have not found any documentation, just source code. It seems to be a proprietary protocol. I did some UDP sniffing with wireshark and identified 6 or 7 packets that are sent back and forth. However, the hex/binary to ascii conversion doesn't seem 'standard' like with most protocols (source). I found some perl code that supposedly works, but I couldn't get it to run.

**Comment by hurdad** [comment]
@Austinb I wonder if its similar to your Unreal2 protocol... I will give it a try on a UT4 server.

**Comment by hurdad** [comment]
so yeah, it UT4 doesn't work with Unreal2 protocol. My guess its similar.. I will see what I can figure out.

**Comment by Austinb** [comment]
@hurdad Do you have a listing or a list of servers to test against?

**Comment by hurdad** [comment]
I was running a LAN dedicated server that I was packet sniffing.

**Comment by Austinb** [comment]
I wont be able to provide any assistance without some kind of network accessible server.  May have to wait until the game is released into the public.   If you find a list of servers or more information please let me know.

**Comment by hurdad** [comment]
there should be some public servers. Iet me take a look
