### ISSUE TITLE
DayZ Standalone - No Results Returned

### ISSUE THREAD

**Issue by firefly2442** [Austinb/GameQ#370]
I'm having some trouble getting results back for DayZ standalone.  DayZ I believe follows the Arma3 development fairly closely.  Most of what I've seen online suggest using the join port + 1 for the query port.  This would be consistent with what Arma3 does.  However, I'm still not getting anything back.

**Comment by Austinb** [comment]
What is the ip:port of the server you are trying to connect to?  Are you able to get any query information from any other servers either Dayz or other server types?

**Comment by Austinb** [comment]
If you can provide any more information please reopen this issue.

**Comment by firefly2442** [comment]
64.94.95.98:2330

Also see: https://www.gametracker.com/search/dayz/

Still doesn't appear to be working.
