### ISSUE TITLE
IP.Board

### ISSUE THREAD

**Issue by kaMMi21** [Austinb/GameQ#371]
How add this to IP.Board forum?

**Comment by naXe90** [comment]
https://invisionpower.com/files/file/7456-gs-server-list/ 👍

**Comment by rststeam** [comment]
@naXe90  Do you have premission to sell this considering that you use GameQ library.  Also by people comments it looks like you just want money 

"If you are developing a plugin for anything number one you'd expect it to work out of the box, or have some easy install instructions which you may have to do. For 3.1.1 of this plugin, it didn't work at all out of the box and I had to use 3.0. The other thing I'd expect after paying 20 dollars for a plugin is I'd get a somewhat prompt response or fix. Or even "I'm looking in to it"."

**Comment by Austinb** [comment]
@rststeam This library is licensed under LGPL v3 which allows commercial use - https://github.com/Austinb/GameQ/blob/v3/LICENSE.lgpl.  As for issues with the IP board specific stuff please keep comments to their forums as I have no part or see any benefit from that addon/plugin. If you have a server or game specific issue with the standalone library please feel free to open a new issue requesting help.
