### ISSUE TITLE
Laravel Integration

### ISSUE THREAD

**Issue by ergiymeri** [Austinb/GameQ#380]
Hello everyone.
Can anyone help me how to integrate gameq v3 to laravel like a library.
I have installed it with **_composer require austinb/gameq:~3.0_** but i cant add it to the providers or config.app. Has anyone idea how to integrate it,
Thanks everyone for replying.

**Comment by Austinb** [comment]
There is no plugin for Laravel or any other framework that provides a facade.  You can access the core class for the base by calling the GameQ class under the GameQ namespace.

```php
$gq = \GameQ\GameQ::factory();
```
More examples are available at https://github.com/Austinb/GameQ/wiki/Examples-v3
