### ISSUE TITLE
[ARMA 3] New Jets DLC Support

### ISSUE THREAD

**Issue by sifex** [Austinb/GameQ#382]
### Description

Undefined Offset error for ARMA 3 servers running the "new" Jets DLC.

```
ErrorException (E_NOTICE)
Undefined offset: 32
```

Preview:
http://scarlet.australianarmedforces.org/api/armaserver/

Image Preview:
<img width="1222" alt="screen shot 2017-06-23 at 9 34 58 am" src="https://user-images.githubusercontent.com/2058557/27460444-394c48fe-57f7-11e7-8efa-4d1d69a524e2.png">

### Solution:

Add support for Jets DLC by adding JETS definition (32) at top of ARMA 3 Protocol File.

**Comment by sifex** [comment]
Should have a PR by this avo.

**Comment by Austinb** [comment]
See #383
