### ISSUE TITLE
How to get the info what I want from gameq for example only gq_name without array

### ISSUE THREAD

**Issue by ergiymeri** [Austinb/GameQ#384]
Hello everyone how to get information from server without arrays because it output only those details (shown below). For example i want to get only the name of server or the map of server how to get that ?

`Array
(
    [0] => Array
        (
            [192.168.0.104:27015] => Array
                (
                    [_tutor_bomb_viewable_check_interval] => 0.5
                    [_tutor_debug_level] => 0
                    [_tutor_examine_time] => 0.5
                    [_tutor_hint_interval_time] => 10.0
                    [_tutor_look_angle] => 10
                    [_tutor_look_distance] => 200
                    [_tutor_message_character_display_time_coefficient] => 0.07
                    [_tutor_message_minimum_display_time] => 1
                    [_tutor_message_repeats] => 5
                    [_tutor_view_distance] => 1000
                    [allow_spectators] => 1.0
                    [coop] => 0
                    [deathmatch] => 1
                    [decalfrequency] => 60
                    [dedicated] => d
                    [edgefriction] => 2
                    [game_descr] => Counter-Strike
                    [game_dir] => cstrike
                    [game_id] => 10
                    [gq_address] => 192.168.0.104
                    [gq_dedicated] => d
                    [gq_gametype] => Counter-Strike
                    [gq_hostname] => Test Game Server
                    [gq_joinlink] => steam://connect/192.168.0.104:27015/
                    [gq_mapname] => cs_havana
                    [gq_maxplayers] => 32
                    [gq_mod] => cstrike
                    [gq_name] => Counter-Strike 1.6
                    [gq_numplayers] => 0
                    [gq_online] => 1
                    [gq_password] => 0
                    [gq_port_client] => 27015
                    [gq_port_query] => 27015
                    [gq_protocol] => source
                    [gq_transport] => udp
                    [gq_type] => cs16
                    [hostage_debug] => 0
                    [hostage_stop] => 0
                    [hostname] => Test Game Server
                    [humans_join_team] => any
                    [map] => cs_havana
                    [max_players] => 32
                    [max_queries_sec] => 1
                    [max_queries_sec_global] => 1
                    [max_queries_window] => 1
                    [mp_allowmonsters] => 0
                    [mp_autokick] => 0
                    [mp_autokick_timeout] => -1
                    [mp_autoteambalance] => 0
                    [mp_buytime] => 1.5
                    [mp_c4timer] => 35
                    [mp_chattime] => 10
                    [mp_consistency] => 1
                    [mp_fadetoblack] => 0
                    [mp_flashlight] => 1
                    [mp_footsteps] => 1
                    [mp_forcecamera] => 0
                    [mp_forcechasecam] => 0
                    [mp_fragsleft] => 0
                    [mp_freezetime] => 4
                    [mp_friendlyfire] => 1
                    [mp_ghostfrequency] => 0.1
                    [mp_hostagepenalty] => 0
                    [mp_kickpercent] => 0.66
                    [mp_limitteams] => 6
                    [mp_logdetail] => 0
                    [mp_logfile] => 1
                    [mp_logmessages] => 1
                    [mp_mapvoteratio] => 0.66
                    [mp_maxrounds] => 0
                    [mp_mirrordamage] => 0
                    [mp_playerid] => 0
                    [mp_roundtime] => 3
                    [mp_startmoney] => 800
                    [mp_timeleft] => 0
                    [mp_timelimit] => 45
                    [mp_tkpunish] => 0
                    [mp_windifference] => 1
                    [mp_winlimit] => 0
                    [num_bots] => 0
                    [num_players] => 0
                    [num_rules] => 81
                    [os] => l
                    [password] => 0
                    [pausable] => 0
                    [players] => Array
                        (
                        )

                    [port] => 27015
                    [protocol] => 48
                    [secure] => 1
                    [steam_id] => -1989385641
                    [steamappid] => 10
                    [sv_accelerate] => 5
                    [sv_aim] => 1
                    [sv_airaccelerate] => 10
                    [sv_allowupload] => 1
                    [sv_alltalk] => 0
                    [sv_bounce] => 1
                    [sv_cheats] => 0
                    [sv_clienttrace] => 1
                    [sv_contact] => $WEBSITE
                    [sv_friction] => 4
                    [sv_gravity] => 800
                    [sv_logblocks] => 0
                    [sv_maxrate] => 50000
                    [sv_maxspeed] => 900
                    [sv_minrate] => 10000
                    [sv_password] => 0
                    [sv_proxies] => 1
                    [sv_restart] => 0
                    [sv_restartround] => 0
                    [sv_stepsize] => 18
                    [sv_stopspeed] => 75
                    [sv_uploadmax] => 0.5
                    [sv_voiceenable] => 1
                    [sv_wateraccelerate] => 10
                    [sv_waterfriction] => 1
                    [teams] => Array
                        (
                        )

                    [version] => 1.1.2.7/Stdio
                )

        )

)
`

**Comment by Austinb** [comment]
You have to reference the keys you are looking for in the response.  You also have an extra array around everything for some reason. 

```php
print_r($response['192.168.0.104:27015']); // Will get you the response for that server then you just need to reference the proper key
print_r($response['192.168.0.104:27015']['key_I_want']); 
```

**Comment by ergiymeri** [comment]
It doesn't work again @Austinb just an simple example give to me please. I tried what you said but again doesn't output anything :(

**Comment by ergiymeri** [comment]
It works thanks :+1:
