### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by LightSrc** [Austinb/GameQ#385]
Hello it would be nice if discord will be supported. https://discordapp.com/developers/docs/intro

**Comment by Austinb** [comment]
There doesnt seem to be any kind of simple "query" to get out server, client and channel information.  I glanced at the API docs and it has some commands via RPC but that is currently beta (https://discordapp.com/developers/docs/topics/rpc).  I would send out a message and ask if there are any plans to allow any kind of outside querying of servers to get server information similar to TS and Ventrillo.

**Comment by Austinb** [comment]
Please reopen if there is documentation made available on how to query the server similar to ventrillo or TS.
