### ISSUE TITLE
Just Cause 3

### ISSUE THREAD

**Issue by rebel24** [Austinb/GameQ#388]
We have Just Cause 2 support, can we get Just Cause 3 Support now?

Thanks! Loving the code Austin

**Comment by rebel24** [comment]
You still alive mate 👍

**Comment by Austinb** [comment]
I need a test server or two to build against.  All the ones I am trying are not responding at the /v0 path on 4200 or 4204.  Using https://github.com/md678685/justquery as a roadmap.

**Comment by rebel24** [comment]
I can provide a test server if wanted? Tell me what you need

**Comment by Austinb** [comment]
I need at least one server to test and build against.  It would be nice to have a list of online servers so that I can test a lot of servers which is normally what I do when building a new protocol class.

**Comment by rebel24** [comment]
The steam link to connect to my server is: steam://connect/
vaiken.jrnetwork.net:4201/

The query port is: 4201, the game port is 4200 and steam port is 4202.

You can use c3po.jrnetwork.net or vaiken.jrnetwork.net as I have 2 seperate
servers on 2 dedicated servers.

Thanks

**Comment by rebel24** [comment]
Do you need any more help?
How's things going?
