### ISSUE TITLE
TrackMania Canyon and shoot mania storm

### ISSUE THREAD

**Issue by ghost** [Austinb/GameQ#39]
what is the protocol of gameQ for TrackMania Canyon and shoot mania storm

thanks

**Comment by Austinb** [comment]
I am not familiar with trackmania.  Can you provide any developer resources for it?  A search in google did not yield much usable information.

**Comment by Austinb** [comment]
Lack of info.  Please reopen if there is a good resource on the query protocol for these games.

**Comment by zahgurim** [comment]
For server callbacks see:
http://server.xaseco.org/callbacks2.php

For another working stats-tool, see:
http://www.tm-forum.com/viewtopic.php?t=29435
