### ISSUE TITLE
Killing Floor 2

### ISSUE THREAD

**Issue by rebel24** [Austinb/GameQ#394]
Hey Austin,
For some reason the Killing Floor 2 protocol uses Source, It should be using the unreal engine 3. This is causing the protocol not to work. 
There isn't any Unreal3 file either, there is unreal 2. Is there any reason for this, can we add this?

Need to get this working for my website.
Thanks

**Comment by rebel24** [comment]
Think I messed this up being honest. Just found a fix.

**Comment by Austinb** [comment]
Most games switched to A2S (Source) for the query protocol when Gamespy went down a few years ago.  Please check the supported servers wiki page at https://github.com/Austinb/GameQ/wiki/Supported-servers-list-v3 for information on the specific game.  Not all game servers have the client and query ports on the same port.  KF2 is one of those games that does not.
