### ISSUE TITLE
Problem with the encoding

### ISSUE THREAD

**Issue by Ablomaro** [Austinb/GameQ#395]
How can I fix a problem with the encoding of the result? Problems with Cyrillic.
```Array
(
    [0] => Ð¿ÐÑÐÐ³(ÐÐ¸ÑÐ°Ð½Ñ)
    [1] => Miok ÐÐ¸ÑÐ°
)

**Comment by Austinb** [comment]
What game is that a response from?  All the responses are returned in utf8.  Those also could be color codes depending on the game.

**Comment by Ablomaro** [comment]
This is Teamspeak 3. 
For example this
**[channel_name] => [cspacer03]-= ÐÐ¾Ð±ÑÐ¾ ÐÐ¾Ð¶Ð°Ð»Ð¾Ð²Ð°ÑÑ=-**
Should be so
**[channel_name] => [cspacer03]-= Добро Пожаловать=-**

**Comment by Austinb** [comment]
All of the responses from TS3 among others are utf8_encoded.  You will need to decode that value and it should display correctly. See http://php.net/manual/en/function.utf8-decode.php for more info.  Please let me know if that fixes your issue.

**Comment by Ablomaro** [comment]
Thanks, that solved my problem!

**Comment by Austinb** [comment]
Glad to hear it. Please reopen the issue if you are having character set issues.

**Comment by Kamiikaze** [comment]
`utf8_decode()` helped kinda but there is a character which doesnt get decoded:

Original `KamikazeGaming | † Suicide Squad †`
Raw: `KamikazeGaming \p â  Suicide Squad â`
Decoded: `KamikazeGaming \p † Suicide Squad †`

So the  |  char isn't decoded correctly. It's the Teamspeak3 Servername (gq_hostname)
