### ISSUE TITLE
old halflife protocol

### ISSUE THREAD

**Issue by jelev** [Austinb/GameQ#40]
Please,
add the old halflife protocol for counter-strike 1.5 servers

thanks in advance

**Comment by Austinb** [comment]
Can you please provide an ip:port of a reachable cs 1.5 server so I can test against it?  It seems any server I test against does not respond.  You can pm the info to me if you wish to keep the server private.

Thanks.

**Comment by jelev** [comment]
cs14.ma3x.net:27015

**Comment by Austinb** [comment]
I have tried on a few separate occasions to get a protocol class working for this using some old resources and things but I just cant get any good response. I cant even get a challenge response from servers that are online. 

Can any else provide support for this protocol?  I currently do not have much time to devote to this project and want to spend what time I do have on support and increasing speed & usability.

**Comment by Austinb** [comment]
See pull request #217 for v2.
