### ISSUE TITLE
Left 4 Dead 2 seems not to work.

### ISSUE THREAD

**Issue by yorick1989** [Austinb/GameQ#401]
I've tried the v3 version of GameQ to get stats of multiple l4d2 gameservers, but it seems not to work. I'd also get write issues to a few gameservers. I've tried it on my own gameservers, but also a public server (example: 5.9.61.197:28315 - this one does show the stats in the HLSW program, but does get a write error from PHP).

Hopefully is it possible to solve this issue in de code, or can someone help me to debug the issue I've got with this type of gameservers (csgo does work perfectly).

PHP Code:
`<?php
error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', 1);

include 'GameQv3/Autoloader.php';

$GameQ = new \GameQ\GameQ();

$GameQ->addServer([
  'type'  => 'l4d2',
  'host'  => '5.9.61.197:28315',
]);

$GameQ->setOption('timeout', 5);

$GameQ->setOption('debug', true);

print_r( $GameQ->process() );`

URL:
[https://api.freegamehosting.eu/php/libs/test.php](https://api.freegamehosting.eu/php/libs/test.php)

Thanks!

Kind regards,

Yorick

**Comment by Austinb** [comment]
Check your hosting provider to make sure they allow you to send out queries to servers.  Many hosting services block all the non http ports (80, 443).  If you can run and query the servers locally but it will not work within your hosting provider then you know it is the provider.  

If you are unable to query the server locally please reopen this issue.

**Comment by yorick1989** [comment]
Thanks for your reply! Somehow the gameserver can't be queried while there is a password set on it. Strange behavior, but it is how it is.

Thank you for your code / project. We've been using it for years now (freegamehosting.eu); and it works perfectly!

This issue can be closed.
