### ISSUE TITLE
Text Only Output?

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#402]
How would you only output the following information as plain text?

Hostname
IP:Port
Current Player/Max Players

**Comment by Austinb** [comment]
This would be possible with a filter.

**Comment by P4InKiLL3R** [comment]
How it works, a little help would not be bad,please,,, 

Thank you  ;)

**Comment by P4InKiLL3R** [comment]
Ist keiner hier der helfen kann,bin für jeden Tip dankbar ?

Is no one here to can help, am grateful for every tip?

**Comment by Austinb** [comment]
I can probably add this pretty quick I just need to know what properties are wanted by default.  Might be able to make it sort of customize-able in terms of the values returned.

**Comment by P4InKiLL3R** [comment]
Hello thanks for help ;)

Only **Player / Max Players** would me suffice ;)

Regards

**Comment by Ruok2bu** [comment]
Hostname, IP, and players/max players would be good for me

**Comment by P4InKiLL3R** [comment]
Where I find a list of the filters, then I try myself ?! ;)

Regards

**Comment by P4InKiLL3R** [comment]
I has now come so far, how I get the left part unvisible, i need only the playerinfo on the right side [bold 9] ?

**OUTPUT:**
> Array ( [gq_numplayers] => **9** )


**CODE:**
```
$GameQ->setOption('timeout', 5); // seconds
$GameQ->addFilter('normalize');

$results = $GameQ->process();

foreach ($results as $id => $result) {
$result = array_filter($result, function ($key) {
return (preg_match('/gq_numplayers/', $key) === 1);
}, ARRAY_FILTER_USE_KEY);

$results[$id] = $result;
}
print_r($result);
?>
```


How to include a second value,any Ideas?

Here the **Example:**

> gq_maxplayers



**Finale** should then look like this:

> 9 / 28 Players

Thats Only what i need, thanks for help,,,

Regards

**Comment by P4InKiLL3R** [comment]
Its done,very hard work for me with a little bit php experience,,, :/

![server](https://user-images.githubusercontent.com/11393911/32017808-30ec8ef2-b9c8-11e7-8919-852b3ab0afe6.png)

**Comment by TacTicToe66** [comment]
@P4InKiLL3R Nice. How did you do it? Care to share your script with others?

**Comment by Kamiikaze** [comment]
```
for($i = 0; $i < count($servers); $i++) {

	foreach ($results as $k => $v) {
		unset ($results[$k]);
		$new_key =  $i;
		$results[$new_key] = $v;
	}
	
	$player =  $results[$i]["gq_numplayers"] . " / " . $results[$i]["max_players"] . "\n";
	echo "Players: " . $player;
}
```


Will Output "Players: 2 / 16" a.e.
@TacTicToe66
