### ISSUE TITLE
Not all servers in the servers list get processed

### ISSUE THREAD

**Issue by timmie124** [Austinb/GameQ#404]
I have a small list of servers
1 Minecraft server
3 CSGO servers
2 Killingfloor 2 servers

when the list gets processed it appears that it only processes 1 of each game type and on rare occasions it will process 2 of the servers but never the entire list. I played with some of the options but nothing I tried seemed to affect the list.

Here's a link to the list, if you refresh the page a couple times you'll see what I'm talking about
tscdevelopment.org/tscgaming2016/ServerList.php

I'm not sure if it matters or not, but the web server is on the same machine as the game servers. 
using PHP 5.6.31

``$servers = 

[
	[
	'type' => 'minecraft',
	'host' => '172.250.218.83:25565',
	],
	[
	'type' => 'csgo',
	'host' => '172.250.218.83:27006',
	],
	[
	'type' => 'csgo',
	'host' => '172.250.218.83:27007',
	],
	[
	'type' => 'csgo',
	'host' => '172.250.218.83:27009',
	],
	[
	'type' => 'Killingfloor2',
	'host' => '172.250.218.83:7777',
	'options' => 
		[
        'query_port' => 27015,
		]
	],
	[
	'type' => 'Killingfloor2',
	'host' => '172.250.218.83:7779',
	'options' => 
		[
        'query_port' => 27017,
		]
	],
	
	
];
	
$GameQ->setOption('debug', TRUE);
$GameQ->addServers($servers);
$r = $GameQ->process();
var_dump($r)``

**Comment by shyim** [comment]
See #400
