### ISSUE TITLE
[Ongoing Issue] ARMA 3 DLC 

### ISSUE THREAD

**Issue by sifex** [Austinb/GameQ#405]
https://github.com/Austinb/GameQ/pull/383
https://github.com/Austinb/GameQ/issues/382
https://github.com/Austinb/GameQ/pull/379

Every ~~mod~~ DLC that get's released follows a value of a power of two. I'l just going to go ahead and fix the latest mod (Laws of War) as well as a few others named `Arma DLC`. This should prevent ongoing errors with the Arma 3 GameQ Protocol.

PR to come tonight.

Edit: I was probably really ~~drunk~~ tired when I wrote this. I meant DLC, not Mods.

**Comment by sifex** [comment]
https://github.com/Austinb/GameQ/pull/406

I did some research and some of the DLCs can be assumed to come out based off of this ARMA 3 Roadmap: https://arma3.com/news/scanning-the-horizon-arma-3-in-2017, so we don't have to name them just `Arma DLC`.

**Comment by Austinb** [comment]
Merged in.  Thanks @sifex

**Comment by sifex** [comment]
No worries at all 😊, thanks for that @Austinb
