### ISSUE TITLE
[QUESTION/REQUEST]CS1.6

### ISSUE THREAD

**Issue by ish12321** [Austinb/GameQ#409]
In CS1.6 does this suppose ReUnion? 

# ServerInfoAnswerType (0/1/2) 
# Sets server answer type for query requests
# 0 = New style (Source Engine) 
# 1 = Old Style (Fix favorites list for p.47 clients) 
# 2 = Hybrid mode - Server is visible anywhere, but there are 3 packets generated for every serverinfo request 
ServerInfoAnswerType = 0 

In this setting 2 usually gives error ... Could you fix if it aint..

A reference for you : http://www.dedicated-server.ru/vbb/showthread.php?t=26486

**Comment by Austinb** [comment]
Cam you provide some test servers that are online and have players?  Is there a list of these somewhere I can use for testing?

**Comment by SHaenk** [comment]
It work's with Renioun and ServerInfoAnswerType 2 :)

**Comment by ish12321** [comment]
Cool then. Thanks shaenk

**Comment by Austinb** [comment]
Going to close this issue.  If you have any other issues with this specifically please reopen this issue.
