### ISSUE TITLE
KillingFloor

### ISSUE THREAD

**Issue by tonyay163** [Austinb/GameQ#41]
1. The killingfloor protocol seems to be having some problems. I'm not sure what it is, but running from example.php (and replacing the server info) gives me some weird values for ping, maxplayers and playercount.
   maxplayers  1415933281
   ping    6647929
   playercount 1195789067
   Any idea what it is? Does the protocol need to be updated? Did I do something wrong?
2. Fatal error: Uncaught exception 'GameQException' with message 'length OOB' in C:\xampp\htdocs\gameq\gameq\buffer.php:106 Stack trace: #0 C:\xampp\htdocs\gameq\gameq\buffer.php(223): GameQ_Buffer->read(114) # 1 C:\xampp\htdocs\gameq\gameq\protocols\unreal2.php(127): GameQ_Buffer->readPascalString(1) # 2 [internal function]: GameQ_Protocols_Unreal2->process_details() # 3 C:\xampp\htdocs\gameq\gameq\protocols\core.php(547): call_user_func_array(Array, Array) # 4 C:\xampp\htdocs\gameq\GameQ.php(452): GameQ_Protocols_Core->processResponse() # 5 C:\xampp\htdocs\gameq\GameQ.php(434): GameQ->filterResponse(Object(GameQ_Protocols_Killingfloor)) # 6 C:\xampp\htdocs\gameq\examples\index.php(39): GameQ->requestData() # 7 {main} thrown in C:\xampp\htdocs\gameq\gameq\buffer.php on line 106
   This only happens when querying the following server: 198.143.169.182:7708. The querying worked fine for this in v1.
3. Warning: Invalid CRT parameters detected in C:\xampp\htdocs\gameq\GameQ.php on line 771
   This happens when querying anything.

**Comment by Austinb** [comment]
It seems the killing floor has changed or is a little bit different from the regular unreal2 query response. I am not 100% this protocol worked when I ported it from v1. Any other information you can send will be helpful.  

At first glance I will have to go through the unreal2 methods and see what is going on with the response data. I will check into this as soon as I have time. 

As for problem 3 it is something with windows I believe. What version of PHP are you running?

**Comment by Austinb** [comment]
More info on problem 3.  Not sure what can be done to resolve it. 

https://bugs.php.net/bug.php?id=54563, https://bugs.php.net/bug.php?id=49948

**Comment by tonyay163** [comment]
I'm running PHP 5.3.8, I guess it'll be fine since I'll be running this on Centos in the end so I guess it's no big deal. The first issue hasn't been working since v1 and the second issue was working fine in v1, but not anymore.

**Comment by tonyay163** [comment]
Any updates for this?

**Comment by Austinb** [comment]
I have not had a chance to debug this one yet, sorry.

**Comment by Austinb** [comment]
I have had a chance to look at this.  It seems that some servers of killing floor work and some dont.  The only common thread I have found is the hostname of the server.  Some servers like 79.98.27.87:7708 work fine where as the server 64.94.101.48:7708 does not.  I am not sure but some character is causing an issue I think.  I will look into it more.

if you could provide the ip and query port of the server you are having trouble with so I can verify a fix, if/when I find one.  You can pm it to me if you do not wish to post it publicly.

Thanks

**Comment by tonyay163** [comment]
198.143.169.180:7708
198.143.169.181:7708
198.143.169.182:7708

The first issue affects all three servers.

The second issue affects only the last server.

**Comment by Austinb** [comment]
Please reopen if this does not fix your issue(s).

**Comment by belkaaa** [comment]
Unfortunately, the problem remained. And very strange behavior ...

For example, the real server addresses:

<pre><code>Address: 88.84.222.135 Port: 7707
Address: 88.84.222.135 Port: 7709
Address: 95.31.20.232 Port: 7707
Address: 95.31.20.232 Port: 7711
Address: 95.31.20.232 Port: 7709</code></pre>

On such requests is not receiving data.

But if you replace the port at 7708:

<pre><code>Address: 88.84.222.135 Port: 7708
Address: 95.31.20.232 Port: 7708</code></pre>

It receives data.

//////////////////////////////////////////////////////////////////
And another problem with "gq_hostname":

<pre><code>?? @@ZOMBIE?@ @MANIYA? @@#2|?  @TOTAL?@ @LINE?@@ |?  @0?@ @-? @@255? @ lvl?@@ |? @@>>>?@ @===========? @@>></code></pre>

And it should be:

<pre><code>ZOMBIEMANIYA # 2 | V.1058 | TOTALLINE | 0-255lvl</code></pre>
