### ISSUE TITLE
Cannot get players info

### ISSUE THREAD

**Issue by luutruong** [Austinb/GameQ#411]
Hi there, i have tried add new server then fetch information but i cannot get the players info. The sever there are no blacklist to prevent it

**Comment by jljr222** [comment]
Hi,

Just to give some clarification too. The server we've been testing on is a CSGO server. The IP and port is:

ze.bor3dgaming.com:27015

The information about the server is displayed just fine, but the array for the player list is empty. I've also added:

host_name_store 1
host_info_show 2
host_players_show 2

To my server config so it should be working fine. Unfortunately, it's still empty. Any ideas?

**Comment by JoaoReis98** [comment]
Same problem here, players array comes empty.

**Comment by Austinb** [comment]
What version are you both running?

**Comment by jljr222** [comment]
Your latest release/commit.

**Comment by naXe90** [comment]
Same problem with latest release

**Comment by Austinb** [comment]
Sorry for the delay, busy busy.  I am not having an issue with that server running v3.0.12 using the following code:
```php
$gq = \GameQ\GameQ::factory();
$gq->setOption('debug', false);

$gq->addServer([
    'type' => 'csgo',
    'host' => 'ze.bor3dgaming.com:27015',
]);
```

What hosting provider are you using to run the library on?  Also do you have this issue with other servers and/or game types?

**Comment by jljr222** [comment]
This issue was present on any game server we tested. I have my web server hosted on KnownHost with CentOS and cPanel/WHM. Standard web hosting VPS environment, nothing out of the ordinary. Everything pulls in, just not the players.

**Comment by JoaoReis98** [comment]
I can get players with others classes.. Only this one isnt working correctly

**Comment by Austinb** [comment]
I see the issue with all source games it appears.  I think a change in v3.0.12 caused the issue. If you roll back to v3.0.11 does it work as expected?

**Comment by Austinb** [comment]
Apparently the merge from 385cfb2 broke this.  Will rollback and push a new version out.  Sorry about that.

**Comment by luutruong** [comment]
Look like it's fixed in the latest commit.
