### ISSUE TITLE
The Forrest

### ISSUE THREAD

**Issue by P4InKiLL3R** [Austinb/GameQ#414]
Hello Austin,

which Game Protocol can i use from You for the Game **The Forrest**?

Regards an a Happy New Year from Germany ;)

Steam: http://store.steampowered.com/app/242760/The_Forest/

**Comment by shyim** [comment]
I would try source protocol

**Comment by P4InKiLL3R** [comment]
Can I take a game protocol query from the games list here or does not work?

https://github.com/Austinb/GameQ/wiki/Supported-servers-list-v3

**Comment by Austinb** [comment]
The query port is the client port + 1.

**Comment by Hembi** [comment]
Please correct the name of the game from 'The Forrest' to 'The Forest'.
