### ISSUE TITLE
GameQ not working

### ISSUE THREAD

**Issue by CrACK000** [Austinb/GameQ#415]
Hi ! 
I do not want to work GameQ. I installed it through the composer.I did everything right but did not want to go.

Forgive my bad english... I am Slovak

Thank you for your reply

This is my test page with GameQ : [https://ricsi.pallax.systems/test](https://ricsi.pallax.systems/test)

PS: My version PHP is 7.2 ... and i testing on 7.1 and 5.4+

PHP file test.php

`<?php

require 'vendor/autoload.php';

use GameQ\GameQ;

$servers = [
    [
        'type'    => 'csgo',
        'host'    => '109.74.146.22:27448',
    ]
];

$GameQ = new GameQ();
$GameQ->addServers($servers);
$GameQ->setOption('timeout', 5);

$results = $GameQ->process();
print_r($results);`

**Comment by Austinb** [comment]
Check your ports.  Also check to make sure your host allows you to send out query requests. Many hosting companies block outbound connections to prevent abuse by bots.

**Comment by CrACK000** [comment]
this server has allowed share info... look page - [http://www.mix-arena.eu/servery/server.php?id=12](http://www.mix-arena.eu/servery/server.php?id=12)

i am testing more server and nothing works.

**Comment by CrACK000** [comment]
it's okay now. ports should be enabled
