### ISSUE TITLE
Add Support for Empyrion

### ISSUE THREAD

**Issue by Mulano77** [Austinb/GameQ#417]
pls add support for Empyrion Galactic Survival (Source)

**Comment by TacTicToe66** [comment]
Default PORT is 30000 

Result:

`Array( [192.223.28.130:30000] => Array ( [AntiGriefDist] => 30 [AntiGriefPvE] => 30 [AntiGriefPvP] => 300 [DecayTime] => 2 [Dedicated] => True [EACActive] => True [EnabledTrading] => 1 [GameModeId] => 1 [GameName] => [Host] => The Killing Crew - US East [IP] => 192.223.28.130 [IsPublic] => True [MaxPlayers] => 8 [MaxStructures] => 200 [NumPlayfields] => 37 [NumStartPlanets] => 4 [NumericalVersion] => -1 [OfflProtDelay] => 300 [OfflProtTime] => 48 [PasswordNeeded] => False [Ping] => -1 [Players] => 0 [Port] => 30000 [Product] => EGS [ServerInfo] => [SteamID] => 90113325717127170 [StopPeriod] => 0 [Version] => Alpha 7.6.0 [WipeTime] => 0 [dedicated] => d [game_descr] => Empyrion - Galactic Survival [game_dir] => EGS [game_id] => 383120 [gq_address] => 192.223.28.130 [gq_dedicated] => d [gq_gametype] => Empyrion - Galactic Survival [gq_hostname] => The Killing Crew - US East [gq_joinlink] => steam://connect/192.223.28.130:30000/ [gq_mapname] => [gq_maxplayers] => 8 [gq_mod] => EGS [gq_name] => Empyrion - Galactic Survival [gq_numplayers] => 0 [gq_online] => 1 [gq_password] => 0 [gq_port_client] => 30000 [gq_port_query] => 30001 [gq_protocol] => source [gq_transport] => udp [gq_type] => empyrion [hostname] => The Killing Crew - US East [keywords] => 1;1;0 [map] => [max_players] => 8 [num_bots] => 0 [num_players] => 0 [num_rules] => 29 [os] => w [password] => 0 [players] => Array ( ) [port] => 30000 [protocol] => 17 [secure] => 0 [steam_id] => 90113325717127170 [steamappid] => 0 [teams] => Array ( ) [version] => 34014720 ) ) `

[Egs.zip](https://github.com/Austinb/GameQ/files/1714230/Egs.zip)

This should work for you. If so, could you close this? We will just have to wait for it to be merged then.

**Comment by Austinb** [comment]
@TacTicToe66 You should add this as a PR

**Comment by ghost** [comment]
Is it possible that also player names are output? Because currently it shows only the playing time of the player but no name
