### ISSUE TITLE
Add support Battalion 1944

### ISSUE THREAD

**Issue by SHaenk** [Austinb/GameQ#419]
Hey!
There is a new popular game with community server.
test server: 164.132.205.131:7777
I dunno about the query protocol but I asked for it in the official forum: http://forums.battaliongame.com/topic/4792-linux-dedicated-server-support/
Article about the game servers: http://35.189.104.46/Community_Servers

Thanks a lot!
Alex
@Austinb

**Comment by TacTicToe66** [comment]
Not sure how to add the file, but this is what I made and it works. Cut and paste the code below. Save it as 'Bat1944.php' in the Protocols directory. 

`<?php
/**
 * This file is part of GameQ.
 *
 * GameQ is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * GameQ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace GameQ\Protocols; 


use GameQ\Buffer;

/**
 * Class Battalion 1944
 *
 * @package GameQ\Protocols
 */
class Bat1944 extends Source
{
    /**
     * String name of this protocol class
     *
     * @type string
     */
    protected $name = 'bat1944';

    /**
     * Longer string name of this protocol class
     *
     * @type string
     */
    protected $name_long = "Battalion 1944";
	protected $port_diff = 3;

    /**
     * Normalize main fields
     *
     * @var array
     */
    protected $normalize = [
        // General
        'general' => [
            // target    => source
            'gametype'   => 'bat_gamemode_s',
            'hostname'   => 'bat_name_s',
            'mapname'    => 'bat_map_s',
            'maxplayers' => 'bat_max_players_i',
            'numplayers' => 'bat_player_count_s',
	    'password'   => 'bat_has_password_s',
        ],
    ];
}
`

**Comment by TacTicToe66** [comment]
Out put from our server test.

`Array( [104.153.104.203:7777] => Array ( [GameMode_s] => TDM [OWNINGID] => 90113234879102979 [OWNINGNAME] => 90113234879102979 [P2PADDR] => 90113234879102979 [P2PPORT] => 7777 [SESSIONFLAGS] => 683 [bat_gamemode_s] => TDM [bat_has_password_s] => N [bat_map_s] => Coastal [bat_max_players_i] => 24 [bat_name_s] => www.TheKillingCrew.com #1 [TDM] Noob Server (RELEASE-10820) [bat_player_count_s] => 0 [dedicated] => d [game_descr] => Unreal Test! [game_dir] => TDM [game_id] => 489940 [gq_address] => 104.153.104.203 [gq_gametype] => TDM [gq_hostname] => www.TheKillingCrew.com #1 [TDM] Noob Server (RELEASE-10820) [gq_joinlink] => steam://connect/104.153.104.203:7777/ [gq_mapname] => Coastal [gq_maxplayers] => 24 [gq_name] => Battalion 1944 [gq_numplayers] => 0 [gq_online] => 1 [gq_password] => N [gq_port_client] => 7777 [gq_port_query] => 7780 [gq_protocol] => source [gq_transport] => udp [gq_type] => bat1944 [hostname] => 90113234879102979 [keywords] => BUILDID:558161692,OWNINGID:90113234879102979,OWNINGNAME:90113234879102979,P2PADDR:90113234879102979,P2PPORT:7777,GameMode_s:TDM [map] => Coastal [max_players] => 100 [num_bots] => 0 [num_players] => 0 [num_rules] => 12 [os] => w [password] => 0 [players] => Array ( ) [port] => 7777 [protocol] => 17 [secure] => 1 [steam_id] => 90113234879102979 [steamappid] => 0 [teams] => Array ( ) [version] => 1.0.0.0 ) ) `

**Comment by SHaenk** [comment]
![image](https://user-images.githubusercontent.com/13860339/35879890-0d72685c-0b85-11e8-9acc-0408336e8759.png)
@TacTicToe66  Is the file needs to look like this?

**Comment by TacTicToe66** [comment]
Mostly.  You need to remove the first ' mark and the last ' mark at the end. Also it needs to be named Bat1944.php and saved to the Protocols directory. I tried to upload it but it would not let me attach the file.

**Comment by TacTicToe66** [comment]
[Bat1944.zip](https://github.com/Austinb/GameQ/files/1702238/Bat1944.zip)

Ok so apparently it works if it is a zip file, so here you go.

**Comment by SHaenk** [comment]
@TacTicToe66 
Thank you a lot dude!!

**Comment by mk-1001** [comment]
Used @TacTicToe66's script, thank you, but we're experiencing a few issues. (I'm using GameQ 3.0.12.0 with Composer).

Also wondering if any specific server configuration is required - although these servers listed below are working correctly with the Discord JS server query.

Sample servers:
213.32.98.194 (port 7777, query port 7780) - returning hostname: "hostname":"90113399616009222"

Sample server (139.99.168.223, query port 7780:
Several gq details returning null (gq_gametype, gq_hostname, etc.)

`{"success":true,"online":true,"data":{"dedicated":"d","game_descr":"Unreal Test!","game_dir":"TDM","game_id":489940,"gq_address":"139.99.168.223","gq_gametype":null,"gq_hostname":null,"gq_joinlink":"steam:\/\/connect\/139.99.168.223:7780\/","gq_mapname":null,"gq_maxplayers":null,"gq_name":"Battalion 1944","gq_numplayers":null,"gq_online":true,"gq_password":null,"gq_port_client":7780,"gq_port_query":7780,"gq_protocol":"source","gq_transport":"udp","gq_type":"bat1944","hostname":"90113301119333382","keywords":"BUILDID:558161692,OWNINGID:90113301119333382,OWNINGNAME:90113301119333382,P2PADDR:90113301119333382,P2PPORT:7777","map":"Liberation","max_players":100,"num_bots":0,"num_players":0,"os":"l","password":0,"players":[],"port":7777,"protocol":17,"secure":1,"steam_id":90113301119333382,"steamappid":0,"teams":[],"version":"1.0.0.0"}}`
