### ISSUE TITLE
GameQ will not correctly query ARK.

### ISSUE THREAD

**Issue by robbiek** [Austinb/GameQ#422]
Hi, 

I have tried to get GameQ to query ark but it will not work. tried a number of different servers and the only data returned is 

`Array ( [31.214.160.156:27019] => Array ( [gq_address] => 31.214.160.156 [gq_dedicated] => [gq_gametype] => [gq_hostname] => [gq_joinlink] => steam://connect/31.214.160.156:27019/ [gq_mapname] => [gq_maxplayers] => [gq_mod] => [gq_name] => ARK: Survival Evolved [gq_numplayers] => [gq_online] => [gq_password] => [gq_port_client] => 27019 [gq_port_query] => 46257 [gq_protocol] => source [gq_transport] => udp [gq_type] => arkse [players] => Array ( ) [teams] => Array ( ) ) )`

Any ideas on fixing this. Used to work. 

The code i use is the example code.

**Comment by TacTicToe66** [comment]
`Array( [31.214.160.156:27019] => Array ( [ALLOWDOWNLOADCHARS_i] => 1 [ALLOWDOWNLOADITEMS_i] => 1 [CUSTOMSERVERNAME_s] => eu-pve-ragnarok-primpluscrossark2 [ClusterId_s] => NewPVEPrimPlusCrossArk2 [DayTime_s] => 3906 [GameMode_s] => GameMode_PrimitivePlus_C [LEGACY_i] => 0 [MATCHTIMEOUT_f] => 120.000000 [MOD0_s] => 111111111:ECAAD94649A68277D7485FA369C5E00E [ModId_l] => 0 [NUMOPENPUBCONN] => 60 [Networking_i] => 0 [OFFICIALSERVER_i] => 1 [OWNINGID] => 90113320838364166 [OWNINGNAME] => 90113320838364166 [P2PADDR] => 90113320838364166 [P2PPORT] => 7781 [SEARCHKEYWORDS_s] => Custom [SERVERUSESBATTLEYE_b] => true [SESSIONFLAGS] => 683 [SESSIONISPVE_i] => 1 [ServerPassword_b] => false [TC_l] => 111111111 [TC_s] => ECAAD94649A68277D7485FA369C5E00E [dedicated] => d [game_descr] => ARK: Survival Evolved [game_dir] => ark_survival_evolved [game_id] => 346110 [gq_address] => 31.214.160.156 [gq_dedicated] => d [gq_gametype] => ARK: Survival Evolved [gq_hostname] => EU-PVE-Ragnarok-PrimPlusCrossArk2 - (v278.1) [gq_joinlink] => steam://connect/31.214.160.156:27019/ [gq_mapname] => Ragnarok [gq_maxplayers] => 70 [gq_mod] => ark_survival_evolved [gq_name] => ARK: Survival Evolved [gq_numplayers] => 20 [gq_online] => 1 [gq_password] => 0 [gq_port_client] => 27019 [gq_port_query] => 27019 [gq_protocol] => source [gq_transport] => udp [gq_type] => arkse [hostname] => EU-PVE-Ragnarok-PrimPlusCrossArk2 - (v278.1) [keywords] => ,OWNINGID:90113320838364166,OWNINGNAME:90113320838364166,NUMOPENPUBCONN:60,P2PADDR:90113320838364166,P2PPORT:7781,LEGACY_i:0 [map] => Ragnarok [max_players] => 70 [num_bots] => 0 [num_players] => 20 [num_rules] => 24 [os] => w [password] => 0 [players] => Array ( [0] => Array ( [id] => 0 [name] => [score] => 0 [time] => 28495.4765625 [gq_name] => [gq_score] => 0 [gq_time] => 28495.4765625 ) [1] => Array ( [id] => 0 [name] => FrankyFourFinger... [score] => 0 [time] => 22091.080078125 [gq_name] => FrankyFourFinger... [gq_score] => 0 [gq_time] => 22091.080078125 ) [2] => Array ( [id] => 0 [name] => [score] => 0 [time] => 19152.0703125 [gq_name] => [gq_score] => 0 [gq_time] => 19152.0703125 ) [3] => Array ( [id] => 0 [name] => [score] => 0 [time] => 19151.240234375 [gq_name] => [gq_score] => 0 [gq_time] => 19151.240234375 ) [4] => Array ( [id] => 0 [name] => [score] => 0 [time] => 18302.21875 [gq_name] => [gq_score] => 0 [gq_time] => 18302.21875 ) [5] => Array ( [id] => 0 [name] => [score] => 0 [time] => 14234.178710938 [gq_name] => [gq_score] => 0 [gq_time] => 14234.178710938 ) [6] => Array ( [id] => 0 [name] => [score] => 0 [time] => 8578.3642578125 [gq_name] => [gq_score] => 0 [gq_time] => 8578.3642578125 ) [7] => Array ( [id] => 0 [name] => TomsLV [score] => 0 [time] => 7731.2333984375 [gq_name] => TomsLV [gq_score] => 0 [gq_time] => 7731.2333984375 ) [8] => Array ( [id] => 0 [name] => [score] => 0 [time] => 5673.583984375 [gq_name] => [gq_score] => 0 [gq_time] => 5673.583984375 ) [9] => Array ( [id] => 0 [name] => [score] => 0 [time] => 5241.814453125 [gq_name] => [gq_score] => 0 [gq_time] => 5241.814453125 ) [10] => Array ( [id] => 0 [name] => 666 [score] => 0 [time] => 3043.5717773438 [gq_name] => 666 [gq_score] => 0 [gq_time] => 3043.5717773438 ) [11] => Array ( [id] => 0 [name] => [score] => 0 [time] => 2116.6127929688 [gq_name] => [gq_score] => 0 [gq_time] => 2116.6127929688 ) [12] => Array ( [id] => 0 [name] => LadyMietzeKatze [score] => 0 [time] => 1564.1511230469 [gq_name] => LadyMietzeKatze [gq_score] => 0 [gq_time] => 1564.1511230469 ) [13] => Array ( [id] => 0 [name] => [score] => 0 [time] => 1481.7481689453 [gq_name] => [gq_score] => 0 [gq_time] => 1481.7481689453 ) [14] => Array ( [id] => 0 [name] => Iron Lord [score] => 0 [time] => 1478.4049072266 [gq_name] => Iron Lord [gq_score] => 0 [gq_time] => 1478.4049072266 ) [15] => Array ( [id] => 0 [name] => 382707954 [score] => 0 [time] => 1267.4445800781 [gq_name] => 382707954 [gq_score] => 0 [gq_time] => 1267.4445800781 ) [16] => Array ( [id] => 0 [name] => Tauricio [score] => 0 [time] => 999.41247558594 [gq_name] => Tauricio [gq_score] => 0 [gq_time] => 999.41247558594 ) [17] => Array ( [id] => 0 [name] => Sesimas [score] => 0 [time] => 427.73220825195 [gq_name] => Sesimas [gq_score] => 0 [gq_time] => 427.73220825195 ) [18] => Array ( [id] => 0 [name] => [score] => 0 [time] => 258.69100952148 [gq_name] => [gq_score] => 0 [gq_time] => 258.69100952148 ) [19] => Array ( [id] => 0 [name] => [score] => 0 [time] => 229.79574584961 [gq_name] => [gq_score] => 0 [gq_time] => 229.79574584961 ) ) [port] => 7781 [protocol] => 17 [secure] => 1 [steam_id] => 90113320838364166 [steamappid] => 0 [teams] => Array ( ) [version] => 1.0.0.0 ) ) `

Looks like it is working to me.

**Comment by Rystan01** [comment]
@robbiek 

I have 6 ark servers working off the following (obviously i truncated the other 5 out of my example)

`$servers = array(
    array(
        'type' => 'source',
        'host' => '10.2xx.xxx.xxx:27020',
        'id' => 'arkab',
        ),
);

$gq = new \GameQ\GameQ();
$gq->setOption('timeout', 5);
$gq->addServers($servers);

$results = $gq->process();`

From there its just pulling the results I need from the array.     Let me know if this helps.

**Comment by Austinb** [comment]
Are you using the latest release?  There was an issue in a previous version preventing some of the other information from returning.  Make sure you are running v3.0.12.

**Comment by Austinb** [comment]
Please reopen if you have any other information.
