### ISSUE TITLE
Cant get MOHAA data

### ISSUE THREAD

**Issue by ddelbasto** [Austinb/GameQ#426]
Hello,
Is it possible that you can add support for MOHAA?, I tried but cant get it. It uses gamespy if I'm right. But, somehow it is not working for me.

I have a server for testing and its working on gametracker so I suppose there's a way to get it working.

Thanks

**Comment by TacTicToe66** [comment]
Already implemented. 

https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Protocols/Mohaa.php

**Comment by ddelbasto** [comment]
I know it's there, but it doesn't work as expected, it doesn't retrieve data.

**Comment by Austinb** [comment]
Please provide the ip and port of the server you are trying to get data from so we can check.  It is possible the server may not allow incoming query connections or your host where you are running the script may not allow you to make outbound requests.

**Comment by ddelbasto** [comment]
I tested your api on other games and it works very well.
Here's mohaa server IP 131.221.32.23:34024

Btw, on gametraker its working that's why im confused, I dont get it.

**Comment by ddelbasto** [comment]
so what's going on ? have you found something?. I'm very interested in it.

**Comment by Austinb** [comment]
Please check the port is correct and the firewall on the machine running the game server.  I was unable to get a response from it.  Other servers from gametracker work as expected (i.e. 162.248.91.229:12203).

**Comment by ddelbasto** [comment]
Could you give me a php example about how did you get it working on IP 162.248.91.229:12203 ?? Maybe I'm doing something wrong. 

Thank you.

**Comment by Austinb** [comment]
```php
$gq = \GameQ\GameQ::factory();
$gq->setOption('debug', true);
$gq->setOption('timeout', 8);

$gq->addServer([
    'type' => 'mohaa',
    'host' => '162.248.91.229:12203',
]);
```

Please verify the host you are using allows these types of queries.  Many server hosting companies do not allow outbound queries on non-standard ports (i.e. 80, 443). 

Please open this issue back up if you have an issue with an actual server response.
