### ISSUE TITLE
Eco Survival

### ISSUE THREAD

**Issue by onekintaro** [Austinb/GameQ#427]
I have copied this file https://github.com/asniper/GameQ/commit/22b80c9194ccf6893a76d5435de4ce104acd3319#diff-f242af5156c87be6361033452491129f to my Installation of GameQ. my eco server is running but the script returns ["gq_online"]=> bool(false).

**Comment by Austinb** [comment]
I am unable to find any information about the game specifically but it based on Source so the source protocol should work but you need to know the query port. I have tried connect port +1 on many servers but none of them work. 

If you can provide and IP:port for a server that works I can add this to the library.

**Comment by onekintaro** [comment]
yes i can provide you the needed Data but i have currently no active Eco server. When the server are Back online i can post the IP and the ports here. :) actual i have reinstalled my complete root for switching from Windows to debian, i think in 1 or 2 weeks are the server back.

**Comment by onekintaro** [comment]
Ok i was faster as i thinking :) Thats the Eco Server Data:
play.swisscrafting.ch:3000 game
play.swisscrafting.ch:3001 web
