### ISSUE TITLE
Feature Request - Kerbal Space Program

### ISSUE THREAD

**Issue by rebel24** [Austinb/GameQ#429]
Hey Austin,
Could you please add KSP support?
https://www.kerbalspaceprogram.com/en/

Thanks!

**Comment by Austinb** [comment]
If you can provide instructions on how to get the information from the servers.  I found an example from game dig which uses the ip:port of the server but all the servers I tested did not respond with any information.  If you have a test server that will respond I can build the protocol pretty quick.

**Comment by Austinb** [comment]
In order to build this out I need an ip and port of a working server that is open to accepting queries.  The protocol appears to be http only but I am unable to get any servers from the listing http://d-mp.org/?p=serverlist to respond.  Please reopen the issue if you can provide the needed items.
