### ISSUE TITLE
RuneScape

### ISSUE THREAD

**Issue by IanWONeill** [Austinb/GameQ#430]
RuneScape private servers!!
https://rune-status.net/

**Comment by IanWONeill** [comment]
What I mean is is it possible to have RuneScape Private Servers added to GameQ.
And the RSPS Scene is pretty big but excluded.

**Comment by Austinb** [comment]
Unable to find any information about a query protocol or if it is even possible to query one of these servers.  Please reopen this issue if you find information on how to query one of these servers as well as a test ip and ports so it can be built.  Perhaps when the game is further along they will add query support if it does not exist yet.
