### ISSUE TITLE
Rust Experimental incorrect mapping of players online

### ISSUE THREAD

**Issue by ProroK680** [Austinb/GameQ#431]
Hello, I noticed that some servers do not display real online. How can this be corrected?
[players] => 3 (real online on the server)
AND 
[gq_numplayers] => 0

ORDER CODE PHP test.zip:
Array
(
    [name] => Premium Rust
    [status] => 1
    [max_players] => 100
    [players] => 3
    [map] => rust_island_2013
    [type] => rust
    [game] => Rust Server
    [app_id] => 0
    [bots] => 0
    [server_type] => l
    [environment] => w
    [visibility] => 0
    [VAC] => 1
    [version] => 1069
    [flags] => rust,extended,oxide,modded
)

GameQ:

Array
(
    [dedicated] => l
    [game_descr] => Rust Server
    [game_dir] => rust
    [game_id] => 252490
    [gq_address] => 185.211.247.42
    [gq_dedicated] => l
    [gq_gametype] => Rust Server
    [gq_hostname] => Premium Rust
    [gq_joinlink] => steam://connect/185.211.247.42:29515/
    [gq_mapname] => rust_island_2013
    [gq_maxplayers] => 100
    [gq_mod] => rust
    [gq_name] => Rust
    [gq_numplayers] => 0
    [gq_online] => 1
    [gq_password] => 0
    [gq_port_client] => 29515
    [gq_port_query] => 29516
    [gq_protocol] => source
    [gq_transport] => udp
    [gq_type] => rust
    [hostname] => Premium Rust
    [keywords] => rust,extended,oxide,modded,cp3,mp100,v1069
    [map] => rust_island_2013
    [max_players] => 100
    [num_bots] => 0
    [num_players] => 0
    [os] => w
    [password] => 0
    [players] => Array
        (
        )

    [port] => 29515
    [protocol] => 17
    [secure] => 1
    [steam_id] => 90114595929552897
    [steamappid] => 0
    [teams] => Array
        (
        )

    [version] => 1069
)

[test.zip](https://github.com/Austinb/GameQ/files/1998321/test.zip)

**Comment by Austinb** [comment]
I am unable to connect to that server to test.  Checking other rust servers from gametracker shows the correct number of players.  

Please open this issue back up if you have a server that is not showing the proper response for the number of players.

**Comment by IP-GAMES** [comment]
https://pp.userapi.com/c845021/v845021059/e3234/Hr5fxdxPdG8.jpg

NO Steam
