### ISSUE TITLE
Time for some protocols not showing?

### ISSUE THREAD

**Issue by rebel24** [Austinb/GameQ#432]
Hey Austin,
Just wondered, within Minecraft + Just Cause 3 it seem's like there isn't time online for players being pulled from the servers. Is it that the server doesn't support this or is it due to the script not supporting it?
Also is their a reason that player names on Just Cause 3 are not being gathered?

And another issue I found, with ARK querying, sometimes there is stuck sessions with a null player name. The user isn't logged in but the server still shows someone signed in. This can happen at the menu of ARK when you connect to the server and then you have to download mods. If you disconnect from the server or it times out it keeps the session active on the server but no player details can be retrieved from that session. Can we stop empty player names from showing on the ARK protocol?

Thanks

**Comment by rebel24** [comment]
Is this project still somewhat active?

**Comment by Austinb** [comment]
When there is time I do updates. 

Minecraft does not return the connected time for the clients. 

Just cause should be returning player's connected time with the response.  Can you provide the query code you are using?  Please include the Ip:port of the server so I may test as well. 

As for ghost players if a player entry shows up in the response from the server's query GameQ returns it as part of the response.  This is how the Source (A2S) protocol behaves. If you want to remove specific items you will need to iterate through the list of players returned and remove any empty entries and update the related item count accordingly.  It maybe possible to build a filter for empty players to do this automatically but that would be its own issue/feature.

**Comment by rebel24** [comment]
Apologies I should have said Just Cause 3 it's mainly a problem where it shows no player names for users in the player list. It does seem to track time. 
IP for our JC3 Server: steam://connect/vaiken.jrnetwork.net:4200/

Thanks for the response.

**Comment by Austinb** [comment]
I did a check on your server and the player names are empty but the response coming back from the server does not have the player names either.  Not sure if this is an error with the server or something else.  JC3 uses the basic A2S (Source) query protocol and the packet response beginning with "D" has the player info but as you can see the response does not contain any strings for names and that server had 3 players when I queried it. The response packet is `<FF><FF><FF><FF>D^C^@^@^@^@^@^@=ĮE^@^@^@^@^@^@<9B>v&E^@^@^@^@^@^@<E7><A9>jD` which converts into a player array 
```php
[players] => Array
                (
                    [0] => Array
                        (
                            [id] => 0
                            [name] =>
                            [score] => 0
                            [time] => 5592.5297851562
                            [gq_name] =>
                            [gq_score] => 0
                            [gq_time] => 5592.5297851562
                        )

                    [1] => Array
                        (
                            [id] => 0
                            [name] =>
                            [score] => 0
                            [time] => 2663.4128417969
                            [gq_name] =>
                            [gq_score] => 0
                            [gq_time] => 2663.4128417969
                        )

                    [2] => Array
                        (
                            [id] => 0
                            [name] =>
                            [score] => 0
                            [time] => 938.65472412109
                            [gq_name] =>
                            [gq_score] => 0
                            [gq_time] => 938.65472412109
                        )

                )

```

I looked for a list of JC3MP servers but did not find any.  Is there a list of available servers?  I would like to query some other servers to see.  Having looked at the tests for the protocol neither of them have any player info either.  Without more info I am unable to debug to try to narrow down the issue.

**Comment by rebel24** [comment]
Literally just saw this reply as of today.
Apologies being out due to issues. The server list is only accessible on
the actual game multiplayer.

I can send you more IP's later on just not available currently as at work
