### ISSUE TITLE
Just Cause 2 Bug

### ISSUE THREAD

**Issue by rebel24** [Austinb/GameQ#434]
Recently I noticed that after upgrading to the latest build of Game Q my Just Cause 2 Servers havent been querying.
All I get back in the logs is this:
array (
  'dedicated' => 'true',
  'gq_address' => 'dagobah.jrnetwork.net',
  'gq_dedicated' => 'true',
  'gq_gametype' => NULL,
  'gq_hostname' => NULL,
  'gq_joinlink' => 'steam://connect/dagobah.jrnetwork.net:7779/',
  'gq_mapname' => 'Panau',
  'gq_maxplayers' => NULL,
  'gq_name' => 'Just Cause 2 Multiplayer',
  'gq_numplayers' => NULL,
  'gq_online' => true,
  'gq_password' => NULL,
  'gq_port_client' => 7779,
  'gq_port_query' => 7779,
  'gq_protocol' => 'gamespy3',
  'gq_transport' => 'udp',
  'gq_type' => 'justcause2',
  'mapname' => 'Panau',
  'players' => 
  array (
  ),
  'teams' => 
  array (
  ),
)

Doesn't seem to get the hostname or any other information, the server is online and working. All other queries are working fine apart from JC2, Has something changed with the JC2 protocol?

Hope you can help,
Jamie

**Comment by Austinb** [comment]
Is the 7779 port the port that is the client connect port?  What version did you update from?
