### ISSUE TITLE
ScumGame

### ISSUE THREAD

**Issue by HellBz** [Austinb/GameQ#437]
Add SCUM Server-Query

**Comment by Austinb** [comment]
Spent a little bit of time searching but I am unable to find any information on a query protocol for this game.  I tried the known ports on some random servers but no luck get a response using the A2S (Source) packets.  If you find more information on the query protocol (if it is not A2S/Source) please comment and reopen this issue.  For now this game looks like it is in the early development stages so I would guess that query support is down the line in terms of their priorities.

**Comment by CodingByHarry** [comment]
Hello

I'm the administrator of http://scumservers.net. I've been emailed asking if I'm able to provide where I receive my Query Information. I'm happy to help the creator(s) of this project. Send me an email - harry@codingbyharry.com

Cheers

**Comment by Angrygargamel** [comment]
any progress on this so far?
its been a while and since Harry has a working solution already i guess it could be solved shortly

**Comment by MrFallen** [comment]
https://scumservers.net/api.html - maybe we can use this?

**Comment by HellBz** [comment]
@MrFallen @Angrygargamel @Austinb

This is my Work: 
https://hellbz.de/scum-server

This is SCUM-Server-JSON
https://api.hellbz.de/scum/

This is my Chart-CSV
https://api.hellbz.de/scum/csv.php

All direct from Masterservers only




You Can use this:
https://gist.github.com/HellBz/88dbe8dfe7d20f94fe1b7afdaf07eb7f

Is in Combination with my API:
https://scumservers.net/api.php?ip=176.57.153.23&port=28200

**Comment by simon-dev** [comment]
When? :(
