### ISSUE TITLE
Conan Exiles server is displayed as offline even he is online

### ISSUE THREAD

**Issue by DopeEx** [Austinb/GameQ#439]
Could you please fix the protocol for Conan Exiles.
The server is definitely online but I always get displayed offline, unfortunately I don't get through enough to fix it myself.

PS: The conanexiles.php is basically empty as far as I can see. Here is the api doku of Conan Exiles. pls fix it.
https://docs.gameapis.net/docs/conanexiles#status

**Comment by Gasjki** [comment]
Can you give me us more information? Like IP and client port?
