### ISSUE TITLE
Port?

### ISSUE THREAD

**Issue by GabriellPrado** [Austinb/GameQ#440]
on my local server the GameQ works perfectly, but when I host it does not return the players online, does anyone know what it can be?

**Comment by GabriellPrado** [comment]
Print: https://imgur.com/a/MaeNm67

**Comment by GabriellPrado** [comment]
[Mon Oct 01 18:48:32.215594 2018] [proxy_fcgi:error] [pid 283045:tid 140223400097536] [client 187.66.200.104:60528] AH01071: Got error 'PHP message: PHP Notice:  fwrite(): send of 1 bytes failed with errno=1 Operation not permitted in /home/--.com/public/site/GameQ/Communicate.php on line 138\nPHP message: PHP Stack trace:\nPHP message: PHP   1. {main}() /home/--.com/public/site/example.php:0\nPHP message: PHP   2. GameQ->requestData() /home/--.com/public/site/example.php:30\nPHP message: PHP   3. GameQ_Communicate->query() /home/--.com/public/site/GameQ.php:230\nPHP message: PHP   4. GameQ_Communicate->write() /home/--.com/public/site/GameQ/Communicate.php:55\nPHP message: PHP   5. fwrite() /home/--.com/public/site/GameQ/Communicate.php:138\n'

**Comment by Austinb** [comment]
The answer is in your error post.  It cant write to the port to send out the data.  This means something at the OS level is blocking access to the port like a firewall.  

Also check the version/branch you are using.  You appear to be using master.  The only active version is v3.  `git checkout v3`
