### ISSUE TITLE
Error | secondstohuman | PHP 7.1

### ISSUE THREAD

**Issue by ViperAix** [Austinb/GameQ#441]
> A non-numeric value encountered

>             [players] => Array
                (
                    [0] => Array
                        (
                            [name] => PeY
                            [team] => 
                            [skin] => 
                            [score] => 
                            [ping] => 16
                            [time] => 
                            [gq_name] => PeY
                            [gq_score] => 
                            [gq_team] => 
                            [gq_ping] => 16
                            [gq_time] => 
                        )

I got the error if [time] / [gq_time] is empty. There are no errors on PHP 7.0

**Comment by Austinb** [comment]
Can you provide the example code you are using to generate this error?  Would like to build a test for this issue as well.

**Comment by ViperAix** [comment]
See on http://gameq.havenith.nrw/

```
require_once('GameQ/Autoloader.php');`

$GameQ = new \GameQ\GameQ();

$GameQ->setOption('debug', false);
$GameQ->setOption('timeout', 3);

$GameQ->addFilter('stripcolors');
$GameQ->addFilter('normalize');

if($_GET['secondstohuman'] == 1) {
	$GameQ->addFilter('secondstohuman');
}

$GameQ->addServer([
	'type' => 'mta',
	'host' => '88.198.41.242:22003'
]);

$result = $GameQ->process();

echo '<pre>';
print_r($result);
echo '</pre>';
```

You see the error on: http://gameq.havenith.nrw/?secondstohuman=1

**Comment by Austinb** [comment]
This is a warning level issue so not a big deal.  To be honest you should disable display_errors() on anything in production as a security measure - `ini_set('display_errors', 0);`. 

Will push a fix since it is a change in
