### ISSUE TITLE
104 or +  = Offline

### ISSUE THREAD

**Issue by GabriellPrado** [Austinb/GameQ#449]
It works perfectly, but when the server gets 104 or more players online on the site gets offline, does anyone know how to solve this?

Site: [http://inftplay.com/](http://inftplay.com/)
`require_once 'GameQ.php';

                    error_reporting(-1);
                    ini_set('display_errors', 1);

                    $server['mtasa'] = array ('mta', 'xx.xxx.xx.xxx', 22003+123);
                    $query = new GameQ; 
                    $query -> addServers ($server); 
                    $data = $query->requestData(); 
            
                    foreach ($server AS $server_id => $values) { 
                        $info = $data[$server_id]; 
                                
                        $st = 'Offline';
            
                        if ($info["gq_online"] == '1') { 
                            $st = 'Online';

                            if ($info["password"] == '1') { 
                                $st = "Trancado"; 
                            } else { 
                                $st = "Online"; 
                            } 
                        }  
                                                        
                        echo '<div class="h4"><i class="fas fa-desktop"></i> Servidor</div>';
                        echo '<div class="serverName">INFINITY PLAY • RP/RPG [BETA]</div>';

                        echo '<div class="serverInfo">IP: <span class="pin1">jogar.inftplay.com</span></div>';
                        echo '<hr class="serverInfo">';

						if ($st == 'Offline') {
							echo '<div class="serverInfo">Jogadores: <span class="pin2">0/0</span></div>';
							echo '<hr class="serverInfo">';
						}else{
							echo '<div class="serverInfo">Jogadores: <span class="pin2">'.$info["num_players"].'/'.$info["max_players"].'</span></div>';
							echo '<hr class="serverInfo">';
						}

                        echo '<div class="serverInfo">Status: <span class="pin-'.$st.'">'.$st.'</span></div>';
                        echo '<hr class="serverInfo">';
                    } 
                ?>	`

**Comment by Austinb** [comment]
It is probably due to the packet size required to hold the information for 100+ players. The packet size is just too large so the server doesnt send a response. MTA uses the All seeing eye protocol ASE which probably has limits to packet sizes. It has been so long since that protocol was added and it is so old I am unable to find documentation on that specific issue.

**Comment by StrixG** [comment]
I have a similar problem. But the server goes offline not constantly, every second time.
https://yamamichi.me
