### ISSUE TITLE
Print List of Players?

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#45]
How do i print the list of connected players?

**Comment by Austinb** [comment]
I would do a print_r() on your results while building your script.  It should be the array key of 'players' in the actual server response information.

``` php
$results = $gameq->getData();

print_r($results['server_id']['players']);
```

Note server_id is whatever you specified or the host parameter if no id was specified.

**Comment by Ruok2bu** [comment]
Where do i put that code (at which line in examples/index.php)?

**Comment by Austinb** [comment]
In the example it would be print_r($data['players']); somewhere on lines 40-42.  If you are using a web script to test add 

``` php
echo '<pre>';
```

so it shows the structure of the array in a better format.

**Comment by Ruok2bu** [comment]
Ah, thanks
