### ISSUE TITLE
Minecraft (TCP )

### ISSUE THREAD

**Issue by IP-GAMES** [Austinb/GameQ#453]
Hi. Not running the monitor minecraft servers by using the TCP Protocol. Can you tell me how to make it work?
Working example: https://github.com/xPaw/PHP-Minecraft-Query

Thanks.

**Comment by Gasjki** [comment]
Hi! Can you give us IP and port address? We'd like to test your server using this library in order to find a solution faster.

**Comment by Austinb** [comment]
@IP-GAMES You have to enable the following settings in your config on the Minecraft server in order to be able to query it for information.  

```
    enable-query=true
    query.port=25565
```

As @Gasjki has asked please provide the ip and port information for the server so it can be tested.

**Comment by IP-GAMES** [comment]
Popular servers disable UDP check so often such servers as "81.176.176: 25565" do not work through GameQ

IP:PORT - 81.176.176.176:25565 and qport 25565
Game - Minecraft

**Comment by Austinb** [comment]
Pretty sure the servers only listen on UDP but it maybe possible to get the info over tcp as well if it is enabled.  Also the xPaw system uses UDP as well https://github.com/xPaw/PHP-Minecraft-Query/blob/master/src/MinecraftQuery.php

I guess you are talking about the "Ping" action from that xPaw library?  Requests need to be as specific as possible please.

**Comment by IP-GAMES** [comment]
Yes https://github.com/xPaw/PHP-Minecraft-Query/blob/master/src/MinecraftPing.php

**Comment by Gasjki** [comment]
@IP-GAMES I tested your server with multiple query library, including script made by xPaw and a custom library made by me and I can't get any response from server. As @Austinb said, check if you have configured your server to accept queries. Also, I have to say that the only library that worked for me was GameDig, a node js module. 

I think something was changed in Minecraft protocol in the last year.

**Comment by silent001** [comment]
@Austinb and @Gasjki could you share with me the custom library you made for minecraft over TCP please? I have a few minecraft servers I play on that block UDP query and using the ping method described above with xPaw/PHP-Minecraft-Query does allow you to get very minimal information such as:
`[ip] => brawl.com
[port] => 
[status] => online
[info] => Array
	(
		[HostName] => 
		[Players] => 0
		[MaxPlayers] => 20
		[Version] => 1.16.1
	)
[players] => Array()
[rules] => Array()`

I changed some of the names myself to normalize between the source query and the minecarft query. I am in the process of migrating from xPaw to GameQ but noticed to have the same issue as the OP.
