### ISSUE TITLE
Support for Soldier of Fortune 2

### ISSUE THREAD

**Issue by Krutok** [Austinb/GameQ#456]
The old gameq version 1.12 supports Soldier of Fortune 2, but the new Version here dont support 100% this Game. Can you back the Game sof2 on this gameq version?

SoF2 used the Quake3 Protokol.
here is the Link: https://sourceforge.net/projects/gameq/

this supports Soldier of Fortune 2, but this Gameq not :(
Problem is GameQ v3 can't show the activ player on the Server. Ping and frags is fine.

**Comment by Austinb** [comment]
Added class but player parsing is broke in Q3 here it appears.  Added new issue for the player names not being returned.
