### ISSUE TITLE
Game server status

### ISSUE THREAD

**Issue by ponasromas** [Austinb/GameQ#457]
Is it possible to query only game server status? Only 'Online/Offline'. I have function for this, but it would be nice to integrate it into GameQ. Added here:

```
function isCsServerOnline($server, $port = 27015)
{
    $socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);

    // timeout 1.5 seconds
    $timeout = array('sec' => 1, 'usec' => 500000);
    socket_set_option($socket, SOL_SOCKET, SO_SNDTIMEO, $timeout);
    socket_set_option($socket, SOL_SOCKET, SO_RCVTIMEO, $timeout);

    @socket_connect($socket, $server, $port);
    @socket_write($socket, "\xFF\xFF\xFF\xFF\x69");

    $isOnline = @socket_read($socket, 5) == "\xFF\xFF\xFF\xFF\x6A";
    @socket_close($socket);

    return $isOnline;
}
```

**Comment by Gasjki** [comment]
Honestly, I don't see why would you need this code inside the library. You can create your custom function, apart from library and you can send query response to this function. 

```php
function getStatus(array $servers) {
   $statuses = [];
    foreach($server as $address => $data) {
       $statuses[$address] = $data['gq_online'] ? 'Online' : 'Offline';
    }

    return $statuses;
}
```

**Comment by ponasromas** [comment]
Code above is faster than GameQ library. But, in other hand it's not universal as GameQ. Thank you for the function, anyway!

**Comment by Austinb** [comment]
You can tweak the timeouts in GameQ to make it wait as long as short as you wish before "giving up" on waiting for responses.  If you are querying a server on the same switch you probably only need a timeout of a few ms versus querying a server on a different continent.  The code you have is concise and does not do any other packet processing, merging or decoding so it will be faster for sure. 

If you have any issues with the actual GameQ library or if you find a way to speed things up without causing an increase in false positives for offline servers please let me know.  Do not have the time to mess with the query internals much and PHP does not really provide great socket/stream control out of the box.
