### ISSUE TITLE
Support for Minecraft?

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#46]
Any plans to add minecraft support?  Information on the minecraft protocol is at http://wiki.vg/Query

One major caveat you'll hit though (and most status scripts for minecraft suffer from this), when there's over 100 players on a server- the script times out when querying for the player list.

Gametracker was able get around this, but i have no idea how they did it.

**Comment by Austinb** [comment]
I did notice a bug in Minecraft when updating the query to the built in protocol in the server any server with more than 100 ish players never responded properly.  I will take a new look at this and see if there is something specific causing this or if this is something with the Minecraft engine itself.

**Comment by Ruok2bu** [comment]
I asked on gametracker how they display the player list and they said its with Minecraft's built-in query protocol.

If you set up a minecraft server, add it to gametracker and then use a packet sniffer, you might be able to figure out how they're doing it.

**Comment by Austinb** [comment]
That is what GameQ uses but the protocol is Gamespy 3.  I tested a couple of servers off Gametracker and they all showed up correctly even the ones over 100 players.

If you have specific servers giving you issues please post or send me the ip:port info so I can look at them. Also what info is missing, if any. My guess might be some weird outlier with the server name or something, wont know until I can look at the raw responses.

**Comment by Ruok2bu** [comment]
I was originally trying the query with another server status script (since this one doesnt have minecraft support), but the developer for that one is very busy and hasnt had the time to fix his script.

Here's the server i was testing against: http://www.gametracker.com/server_info/68.233.235.26:25565/

**Comment by Austinb** [comment]
I am confused: https://github.com/Austinb/GameQ/blob/v2/gameq/protocols/minecraft.php

Is there something wrong with this protocol?  If so please provide some servers where the info is not appearing properly.  Also note that the server has to have the query enabled in the server config.

**Comment by Ruok2bu** [comment]
Oh, i didnt realize gameq supports minecraft :S I had to dig around on the wiki to find the supported game list.

Sorry :X

**Comment by Austinb** [comment]
I tried that server  68.233.235.26 on the default port but no response.  My guess is the query port is set to something other than the default or it is being blocked by a firewall somewhere along the way.

Other servers from the gametracker list work, some don't.  Cant really pinpoint it from my end very easily.

**Comment by Ruok2bu** [comment]
Ah, i didnt think of that :X

I haven't hosted a server with the new built-in query and didnt realize it could be changed to another port.
