### ISSUE TITLE
New Game Request: Contagion

### ISSUE THREAD

**Issue by ponasromas** [Austinb/GameQ#461]
Server: 
109.248.59.164:27016

Maybe csgo query would suffice, but anyway, this is popular game.

**Comment by rostov114** [comment]
Hello.

The server you provide is Counter-Strike 1.6 with a Zombie modification.

This is not a separate game.

**Comment by rostov114** [comment]
Created Pull request https://github.com/Austinb/GameQ/pull/462

**Comment by Austinb** [comment]
Added in 2895a81
