### ISSUE TITLE
Hello, Player and Server Name Issue

### ISSUE THREAD

**Issue by iyzee** [Austinb/GameQ#464]
213.238.173.x , 185.198.75.6:27015 , 185.198.75.x , 93.123.18.17 , 95.173.173.x	

CS: GO and CS 1.6 does not attract players on the servers mentioned above.

I'd appreciate it if you could help. Thanks.

**Comment by ponasromas** [comment]
What are you talking about? Please provide your code and clear explanation in English. I use this library and it shows players as it is suppose to be.

**Comment by Austinb** [comment]
Please open this issue with more information if you are having issues getting responses from your server(s).
