### ISSUE TITLE
New Game Request: ATLAS

### ISSUE THREAD

**Issue by ponasromas** [Austinb/GameQ#465]
Popular game server. Example address: 

81.53.174.163:10521

**Comment by iShotFT** [comment]
You can use the ARK server type to poll ATLAS servers.

**Comment by Austinb** [comment]
I am unable to get a response from that test server.  Atlas is Source which is the same thing Arkse extends.  Is there an odd port offset?  I need the connect port and the query port so I can build it and have some servers to test against.

**Comment by Austinb** [comment]
Merged.
