### ISSUE TITLE
Hy help me plz

### ISSUE THREAD

**Issue by Takanashi-Rikka1** [Austinb/GameQ#467]
Hey guy
i have website

gametracker.co.il

I need change Query for GameQ

I wnat Which extracts data game server into a  GameQ folder

Now i have Source Query and i want cahnge.

If yoy want help and i pay you for job.

Email: talnaim2323@gmail.com

Discord: Mangekyou Sharingan#2309

**Comment by Gasjki** [comment]
This is an issue tracker. @Austinb has created a documentation for his library which is easily to use and you can find it here: https://github.com/Austinb/GameQ/wiki/Version-3 

Please, spent some time updating your code manually. No one is gonna do it for you! Good luck!

**Comment by Takanashi-Rikka1** [comment]
@gasjki

I pay for eho can do it so...

**Comment by naXe90** [comment]
@talnaim2323 i can try ;)
