### ISSUE TITLE
Questions about supported games

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#47]
I noticed a few things on the supported games list.

It says GameQ supports America's Army and America's Army 3, but what about America's Army 2 ?

What about Battlefield Bad Company 1, Call of Duty 4: Modern Warfare 1 and 2 and the other F.E.A.R versions (2, etc.)  ?

Also, can you add a generic named query for "source".  Makes it less confusing when dealing with multiple source servers.

P.S. Your script has totally saved me.  I was looking for something that supported certain games and i not only found it in your script but got a lot more than i was planning on supporting.  So i'll be donating once these issues are answered.

**Comment by Ruok2bu** [comment]
I also tested the following games and they return an error when i try querying (its got to be the script because when i add the server to HLSW i can query it fine and its not a port issue as i disabled my firewall to test it):

Arma 2 (Armed Assault 2)

The following games do query, but the player list doesnt display (player list displays on GameTracker though):

Call of Duty 4: Modern Warefare 3

**Comment by Austinb** [comment]
Please added each game issue as a separate issue in github.  Also any games you want added add a new issue for each of those as well.  Helps me stay a bit more organized.   Also for any new games try to include links to the manuals or any other relevant info.
