### ISSUE TITLE
Arma3 not working partially in Dev Version while v3.0.14  works fine

### ISSUE THREAD

**Issue by Angrygargamel** [Austinb/GameQ#479]
hey there...
we just encountered a problem with showing our arma3 servers...
while 3 servers were shown correctly it wouldnt show the 4. server online at all

changed to the arma3.php file from previous version and it works again
so its no port problem or serverissue...

please check again
this is the server it couldnt parse correctly/at all
136.243.148.87:2402

**Comment by Austinb** [comment]
Paging @Memphis017 - Did they change something again and revert it back?  The difference he is seeing is your merge from #433 which is in dev and was slated for v3.0.15.

**Comment by Austinb** [comment]
Wanted to circle back on this and see if this issue remains or if something else has changed.  @Angrygargamel do you have the same issues as your original post?  Have any other updates for the server come out or any updates to the API docs?

**Comment by Memphis017** [comment]
Sorry I missed this one, in fact it looks they scrambled mod order when they added more DLCs along the way. Created a new pull which should resolves this issue : https://github.com/Austinb/GameQ/pull/493

@Angrygargamel : Do you have any specific mod on this server (which are not on the others) ? If yes are they signed ? What signature verification mode are you using ?

@Austinb : There is something wrong with the signature part of the script with this server, this explains why it is working in 3.0.14, they are not processed in this version.

**Comment by Memphis017** [comment]
Ok Nailed it, I reworked the signature part a bit, now it seems to work properly. Updated my pull request for it.

**Comment by Austinb** [comment]
@Memphis017 I commented in the PR but you may have not seen it.  The tests are failing with unknown mod.  Do I need to pull new tests due to the changes?

**Comment by Austinb** [comment]
Updated the PR #493 to update the tests.  

@Angrygargamel Sorry for the delay.  Please try latest dev and let us know if it is not working properly.  If everything looks good please close this issue.

**Comment by Angrygargamel** [comment]
sorry for the delay...
it works so far with the latest changes
