### ISSUE TITLE
IPV6 Support?

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#48]
Are you going to add IPV6 support to GameQ?

With the recent news that Europe has hit the address limit - most countries aren't far off and the forced change might happen sooner than later.

**Comment by Austinb** [comment]
I added this as a feature request.  Not sure which newer games even support ipv6.

**Comment by Austinb** [comment]
Is it possible for someone to provide a ipv6 address to a source server?  I would like to add this feature as it is pretty simple just need to make sure it works so I need a server's ipv6 address to test against.

Also include the ipv4 equivalent for verification.  Thanks
