### ISSUE TITLE
Issue with 7dtd

### ISSUE THREAD

**Issue by NothingTV** [Austinb/GameQ#481]
I justed added a 7 days to die server to my list and tried "7d2d" and "sevendaystodie" as type, first results a error but the second doesnt show any game related information.

What do I have to add to get game related informations?

My current try:
{
	"id": "7dtd",
    "type": "sevendaystodie",
    "host": "46.4.37.182:26900",
	"options": {
		"query_port": "26901"
	}
  }

**Comment by NothingTV** [comment]
I guess the problem is solved now. I dont know why, but the query now shows server details (I didnt changed a thing)..

**Comment by Austinb** [comment]
Check your ports and make sure your game server host allows incoming udp requests to that port.  Many server hosting companies block requests to prevent ddos attacks.  Please reopen if you have more information.
