### ISSUE TITLE
GameSpy Server "does not respond within specfied time", a css server works

### ISSUE THREAD

**Issue by johnicepick** [Austinb/GameQ#483]
Hello dear developers,

I tried to use GameQ for an old game that uses the gamespy protocol, called "No one lives forever" or "nolf" in short. 
All I get is _"The server did not respond within the specified time."_. I also entered a random counterstrikesource server, that one works. 

A piece from example.php
```
// Define your servers,
// see list.php for all supported games and identifiers.
$servers = array(
    'server 1' => array('nolf', '212.201.73.154', 50000),
    'server 2' => array('nolf', 'egoicepick.ddns.net', 50001),
    'server 2' => array('nolf', '74.77.99.136', 10950),
    'server 3' => array('nolf', 'localhost', 50000),
    'server 4' => array('cssource', '151.80.111.130', 27045),
//	'server 5' => array('ts3', 'nolfserver.ego-clan.com' , 50005)
);
```

My IP changes weekly therefore I'd like to use "egoicepick.ddns.net" but even the direct IP doesn't work. I run it on XAMPP, the local IP or localhost do not work. All I get is "The server did not respond within the specified time." another nolf server does not work either - while a CSS server shows the correct data.
Current nolf servers can be seen here: https://www.qtracker.com/server_list_details.php?game=noonelivesforever

Edit: the result of GameQ Query can be seen here http://egoicepick.ddns.net/nolfserverfeed/example.php

Where is my mistake?

**Comment by naXe90** [comment]
Nolf server response works fine for me

`►	NetArmorHealthPercent	(String, 3 characters)	100
►	NetAudioTaunts	(String, 1 characters)	1
►	NetDMGameEnd	(String, 1 characters)	0
►	NetDefaultWeapon	(String, 2 characters)	33
►	NetEndFrags	(String, 2 characters)	15
►	NetEndTime	(String, 2 characters)	15
►	NetFallDamageScale	(String, 1 characters)	0
►	NetHitLocation	(String, 1 characters)	1
►	NetMaxPlayers	(String, 2 characters)	16
►	NetRespawnScale	(String, 3 characters)	250
►	NetRunSpeed	(String, 3 characters)	145
►	NetWeaponsStay	(String, 1 characters)	1
►	dedicated	(Integer)	1
►	final	(String, 0 characters)
►	gamename	(String, 4 characters)	nolf
►	gametype	(String, 10 characters)	deathmatch
►	gamever	(String, 5 characters)	1.004
►	gq_address	(String, 14 characters)	212.201.73.154
►	gq_dedicated	(Integer)	1
►	gq_gametype	(NULL)
►	gq_hostname	(NULL)
►	gq_joinlink	(String, 0 characters)
►	gq_mapname	(NULL)
►	gq_maxplayers	(NULL)
►	gq_mod	(NULL)
►	gq_name	(String, 14 characters)	GameSpy Server
►	gq_numplayers	(Integer)	0
►	gq_online	(Boolean)	TRUE
►	gq_password	(NULL)
►	gq_platform	(String, 6 characters)	unknow
►	gq_port_client	(Integer)	50000
►	gq_port_query	(Integer)	50000
►	gq_protocol	(String, 7 characters)	gamespy
►	gq_secure	(Integer)	0
►	gq_transport	(String, 3 characters)	udp
►	gq_type	(String, 7 characters)	gamespy
►	gq_version	(String, 5 characters)	1.004
►	hostname	(String, 22 characters)	|eGo| www.ego-clan.com
►	hostport	(String, 5 characters)	50000
►	location	(String, 1 characters)	0
►	mapname	(String, 12 characters)	001THEPAD_DM
►	maxplayers	(String, 2 characters)	16
►	num_players	(Integer)	0
►	num_teams	(Integer)	0
►	numplayers	(String, 1 characters)	0
►	players	(Array, 0 elements)
►	teams	(Array, 0 elements)`

**Comment by johnicepick** [comment]
Oh! Okay that's really weird you can query the nolf server, I can't, but I can query a random css server! The results that you post are exactly the settings of the nolf server, exactly how I entered them - so the data checks out!

Since you can query the server it can't be a firewall/port error. Could it be differences in PHP versions? XAMPP is running on php 5.6.40 - all php settings are here: http://egoicepick.ddns.net/nolfserverfeed/phpinfo.php . On which php version and machine (linux? windows?) did you test it? Are you able to upload the php.ini file ? Thank you for response!


#Edit 3 days later:
After days trying different things I gave up on GameQ. The links I posted above will be alive for some time, in case you want to test/check yourself for troubleshoot. 

Current status:
Webhoster: can't query nolf servers, can't query css servers
Local XAMPP: can't query nolf servers, can query css servers. 
Nolf servers are query-able according to NaXe90's post.

I use now QTracker to generate a php file with variables - I wrote a nice frontend to show the results. (http://egoicepick.ddns.net/nolfserverlivestatus/index.php)
