### ISSUE TITLE
New Game Request: Mordhau

### ISSUE THREAD

**Issue by devu4** [Austinb/GameQ#485]
Could you please try test this game, it uses the A2S protocol but when I tried with csgo I get a response but with an error of "Unable to read length=4 from buffer. Bad protocol format or return?". 

TEST IP: 208.103.169.146:7780, Query Port: 27168

**Comment by Austinb** [comment]
Unable to query that server.  Please provide another to test with.  Thanks.

**Comment by uilson** [comment]
@Austinb this can also be closed, as the protocol has been added in last pull request.

**Comment by uilson** [comment]
@Austinb, this can also be closed, as the protocol has been added in last pull request.
