### ISSUE TITLE
New game request: CS2D

### ISSUE THREAD

**Issue by berdancanyet** [Austinb/GameQ#489]
Can you add this game please?
www.cs2d.com

A working server ip: 37.187.178.247:36966

**Comment by uilson** [comment]
[http://www.cs2d.com/serverhosting.php](cs2d site)

for further help if implemented

**Comment by uilson** [comment]
[http://www.cs2d.com/serverhosting.php](http://www.cs2d.com/serverhosting.php)

[Some hosted servers](http://www.unrealsoftware.de/usgn.php?s=cs2d)

for further help if implemented

**Comment by uilson** [comment]
@Austinb I also, just noticed that this protocol is present in v1, so probably even easier to port?!
[v1/GameQ/Protocol/cs2d.php](https://github.com/Austinb/GameQ/blob/v1/GameQ/Protocol/cs2d.php)
