### ISSUE TITLE
Support for TeeWorlds and Phase Shift

### ISSUE THREAD

**Issue by Th3BiSh0p** [Austinb/GameQ#49]
Hello,

thanks for your good work, it's a real pleasure to use this library ;)

Is it possible to add support for this 2 indie games ?

https://www.teeworlds.com/
and
http://www.dwsk.co.uk/index_phase_shift.html

I have found some query class for teeworlds but they don't seem to work anymore, furthermore, it would be way easier to use only GameQ to query all the game server we are running in our community!!

Thanks again ;)

**Comment by Austinb** [comment]
It would be no problem when I have some time to give.  Please make a new issue for each game you want to request being added.  Please include all information you can such as other scripts, server manuals, etc... will make my life a bit easier when doing research.
