### ISSUE TITLE
 Protocol request: Port Gamespy2 from old gameq version to the v3.

### ISSUE THREAD

**Issue by uilson** [Austinb/GameQ#490]
Hi @Austinb , first of all thank you for your work in developing this.

I would like to request for you to port the Gamespy2 protocol from the old gameq (v2) to the master, as I have tried but cant get it working. And to query Swat4 servers this is the protocol needed, since it wont work with gamespy1 or gamespy3.

Thank you in advance and regards,
Wilson

**Comment by Austinb** [comment]
@uilson Please send some test ips and ports for a game so the updated protocol can be tested.

**Comment by uilson** [comment]
Hey, here are some IPs for testing (in version v2 it is working) 

ArmA Armed Assault Server:
IP: 83.142.84.214
Query port: 2302

swat4 server:
IP: 213.239.209.233
Host Port: 10480
Query port: 10481


gameq v2 result for swat4:

> GameQ_Buffer Object
(
    [data:GameQ_Buffer:private] => PoNGplayer_score_ping_|WM|Gumias044JimLiout050GordonDurie0158|WN|Sinaas329DarthMisha086|MYT|Jonny_Quest>M<�0103snajper027Jericho136|MYT|Zardes071oRg|Attila037KiLLeR029t00elitte048bubbles032Maverick065
    [length:GameQ_Buffer:private] => 251
    [index:GameQ_Buffer:private] => 0
)
GameQ_Buffer Object
(
    [data:GameQ_Buffer:private] => PiNGhostname-==MYT Team Svr==-numplayers14maxplayers16gametypeVIP EscortgamevariantSWAT 4mapnameQwik Fuel Convenience Storehostport10480password0gamever1.1
    [length:GameQ_Buffer:private] => 175
    [index:GameQ_Buffer:private] => 0
)

> Array
(
    [server 1] => Array
        (
            [num_players] => 14
            [players] => Array
                (
                    [0] => Array
                        (
                            [player] => DarthMisha
                            [score] => -4
                            [ping] => 84
                        )
                    [1] => Array
                        (
                            [player] => GordonDurie
                            [score] => 0
                            [ping] => 158
                        )
                    [2] => Array
                        (
                            [player] => Jericho
                            [score] => 24
                            [ping] => 36
                        )
                    [3] => Array
                        (
                            [player] => JimLiout
                            [score] => 6
                            [ping] => 48
                        )
                    [4] => Array
                        (
                            [player] => KiLLeR
                            [score] => 2
                            [ping] => 28
                        )          
                )
            [num_teams] => 0
            [hostname] => -==MYT Team Svr==-
            [numplayers] => 5
            [maxplayers] => 16
            [gametype] => VIP Escort
            [gamevariant] => SWAT 4
            [mapname] => Qwik Fuel Convenience Store
            [hostport] => 10480
            [password] => 0
            [gamever] => 1.1
            [gq_online] => 1
            [gq_address] => 213.239.209.233
            [gq_port] => 10481
            [gq_prot] => gamespy2
            [gq_type] => gamespy2
        )
)

**Comment by Austinb** [comment]
Fixing tests shortly.

**Comment by Austinb** [comment]
#494 fixes test issues and coverage for Gamespy 2.
