### ISSUE TITLE
player list?

### ISSUE THREAD

**Issue by BETLOG** [Austinb/GameQ#495]
Are player name lists possible? Documented? or not implemented?
Same question as: https://sourceforge.net/p/gameq/discussion/291208/thread/c9a6ab65/

**Comment by uilson** [comment]
GameQ shows the name of players if there's players. returned in the query to the server.

do you even tried to run an example?

**Comment by Austinb** [comment]
Please run an example and reopen if you are having issues.  If the server supports returning player information it will be returned but not all servers return player data.

**Comment by BETLOG** [comment]
The way the example is worded "Players are never displayed in this example." Does seem counterintuitive given that you say it does. Hence the confusion and the questions.
I did run an example, on a known local BF:BC2 (bf2) server, it was displaying a numplayers of 6 with no name list.... however when I checked later there were actually 0 players (and displaying numplayers 6). 
Presumably numplayers was not the variable to use in my chopped down version of the example.php
...again: hence the confusion.

**Comment by Austinb** [comment]
This project is separate from the project hosted on Sourceforge so any documentation, examples, etc you get from that site are probably incorrect for this library.  The old version 1 of this library does have an example.php with that wording (https://github.com/Austinb/GameQ/blob/v1/example.php) but it is very out of date as the current branch is v3.   If you are going to use this library I recommend you start here https://github.com/Austinb/GameQ/wiki/Version-3.  Anything older than v3 is unsupported.
