### ISSUE TITLE
Quakelive

### ISSUE THREAD

**Issue by byman64** [Austinb/GameQ#496]
I am trying to read status from quakelive servers but some info are missing or wrong
- ID always 0
- Ping is missing

Here an example with 3 servers
https://www.quakearea.com/mon/exampleQL.php

and here in the QooL Monitor
https://www.quakearea.com/mon/#q=QooL-QL.txt

Any idea?

**Comment by Austinb** [comment]
No idea as to why player id is always 0.  My guess is either they removed it for privacy reasons or didn't need it when the game was released on Steam.  

Ping is not returned by the server query response.  Off the top of my head I don't think any server that uses the Source (A2S) query protocol returns ping information for players.  Player ping is also not in the query response specification for player info at https://developer.valvesoftware.com/wiki/Server_queries#Response_Format_2.
