### ISSUE TITLE
Call of Duty 4: Modern Warefare 3 Broken

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#50]
Call of Duty 4: Modern Warefare 3 doesnt display the player list.  It looks like it is possible though since GameTracker is able to do it.

**Comment by Austinb** [comment]
If you have a server with players on it that is open let me know.  All the servers with players when I just tried do not respond.  In my notes on https://github.com/Austinb/GameQ/wiki/Supported-servers-list-v2 you can change the query port in the cmd line so it is possible the query port is different.

**Comment by Austinb** [comment]
Please reopen if you find a query-able server that is not responding properly.

**Comment by Ruok2bu** [comment]
I couldnt find any.  I even tried looking into hosting my own, but it looks like the server component is only included with the game itself and i dont have the game.

**Comment by Austinb** [comment]
Yea its one of those weird games.  I was able to make the query work at one point in the past so it did work then, it may not work now but I am unable to test it.  Also, I am not sure how much this game is played on the pc now.

**Comment by Ruok2bu** [comment]
Hmm, still looks very popular.  When i looked on gametracker, there were a few hundred players online playing and that was at 4AM which is a low traffic time.

What ill do if i can't find any servers without wierd ports, ill rent a cheap server and try and get my money back before the end of the billing cycle.

**Comment by Ruok2bu** [comment]
I've got some good news.  I figured out the query port by going to a GSP's forum and the port number was there.

Try: 216.155.146.109:27017

With that IP, you can see all the info of the server except for the player list.

**Comment by Ruok2bu** [comment]
Doh, that server was empty.  It wasnt empty when i first got the IP.

Anyways's the protocol works.  I tested it against a busy server (173.199.94.73) and the player list displays.  It looks like the default query port is 27017.

**Comment by Austinb** [comment]
Ok good news!  Thanks for the update.
