### ISSUE TITLE
Quake3 Player parsing broken

### ISSUE THREAD

**Issue by Austinb** [Austinb/GameQ#501]
It appears the Quake 3 protocol is not returning the player names properly.  This seems to be a larger issue and will affect all the tests for any protocol using Quake 3.

**Comment by uilson** [comment]
you sure this is a problem? 
in my previous tests, on the cod and coduo protocols, that also extends the quake3 protocol, it returned names, as you can see in the [pull request](https://github.com/Austinb/GameQ/pull/494/commits/387e9fb2eaa1f0bc158d6d847c5062f032146f24).


---EDIT

redid the tests with coduo (expands quake3) with the latest fork, and also added 2 more tests, all of them returned the player names fine.

**Comment by Austinb** [comment]
@uilson It only affected games with 4 items in the player response (team) and not 3.  So if the server did not return the team the player was on there should be no change.  The change affects sof2 which is why I noticed that the player information was empty after I pushed up the changes.  Pushing fix now that _should_ not break anything else. 

Thanks for the feedback!
