### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by topg-org** [Austinb/GameQ#502]
PHP Warning:  Invalid argument supplied for foreach() in .../gameq3/Protocols/Tshock.php on line 132
PHP Warning:  Invalid argument supplied for foreach() in .../gameq3/Protocols/Tshock.php on line 145

I think we should do a check to avoid this like:
if(is_array($json->players)) 
if(is_array($json->rules))

**Comment by Austinb** [comment]
Can you give me a server or two that you have this issue with?  Would like to make sure it is just the properties missing and not something more.

**Comment by topg-org** [comment]
Hi Austin, I will enable debugger to be able to get you the server(s) that give this error and I will update this.
