### ISSUE TITLE
TF2 Bug

### ISSUE THREAD

**Issue by topg-org** [Austinb/GameQ#506]
Fatal error: Uncaught Error: [] operator not supported for strings in .../Protocols/Source.php:186 

Test with host: 77.95.36.158:27015

**Comment by topg-org** [comment]
It seems like the $packets return a String instead of array.
Simple fix to temp patch this would be if(is_array($packets[$packet_id]))

**Comment by Austinb** [comment]
What version of PHP?

`$packets` is defined as an array at https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Protocols/Source.php#L161.  The only way it wouldnt be an array is if there is a PHP change by version or you have modified that file manually.

**Comment by Austinb** [comment]
Just tested this server and it returns without any issues.  Please reopen if you are still having the issue on a vanilla GameQ install on a supported version of PHP.
