### ISSUE TITLE
Wrong $buffer->readString()?

### ISSUE THREAD

**Issue by topg-org** [Austinb/GameQ#508]
To test:
Game: Killing Floor
Host: 188.165.201.32:7907
Query_port: 7708

Another weird one: 54.65.61.155:7707

Seems like the readString() is not working right for this server and a few more like:
188.165.201.32:8307, 188.165.201.32:11007, 188.165.201.32:11207, 188.165.201.32:8507

**Comment by Austinb** [comment]
I tried all of the servers listed and there was no issue. It maybe related to an issue with the players return as there are currently 0 players on these servers.  Closing the issue.  If it happens again please open a new issue with the server and the error being returned so I can dig into it more.
