### ISSUE TITLE
Arma 2 (Armed Assault 2) is broken

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#51]
All arma 2 servers time out.  I'm not sure if its a server issue (im testing against random gametracker servers) but ive tried around 20 and they all dont respond.

**Comment by Austinb** [comment]
Try using armedassault2oa as the game type.  Not sure if armedassault 2 and armed assault: operation arrowhead are indeed different or not.  Arma2 uses gs2 while arma2 oa uses gs3.  If you can find any info on regular arma 2 please link it so I can make sure that the classes are correct.

The original gameq had them both using gs2 but it didnt work properly.  Not sure when the game implemented gs3.

**Comment by Ruok2bu** [comment]
Ah that fixed it!

Now it works, but the player list isint being displayed (player lists display on gametracker though so it should be possible to pull it)

**Comment by Austinb** [comment]
72.20.13.73:2302 shows me a player list.  Need a specific server with the issue so I can debug.  Could be any number of issues since it is GS3 protocol.

**Comment by Ruok2bu** [comment]
I tested with 85.159.42.196:2302

**Comment by Austinb** [comment]
Server at 85.159.42.196:2302 currently has 1 player according to the raw response from the gs3 query.  When I use the GameQ processing it shows me 1 player in the players array. 

Here is a sample

``` php
numplayers1numteams0maxplayers40
```

Each of those represents a key:value pair.

**Comment by Ruok2bu** [comment]
Ah, hmm must be some type of fake player thing because i dont see any playername in the array, gq_online     is 1 though.

Anways, are you going to update the arma2 protocol to match the oa protocol?

**Comment by Austinb** [comment]
Yes I can change it assuming arma 2 uses it.  I think the original arma 2 was gs2 but operation arrowhead switched to gs3.

**Comment by Ruok2bu** [comment]
Ah, but the odd thing is even when i query arma 2 servers, it doesnt work.  It works only when i query with ao protocol.

**Comment by Austinb** [comment]
Ok I will change it.
