### ISSUE TITLE
New Game Request: Onset

### ISSUE THREAD

**Issue by ju-ce** [Austinb/GameQ#512]
Hello, i hope someone can create a request for **Onset** Game.

Clientport _UDP_ = 7777
QueryPort (- Clientport) _UDP_ = 7776
Fileport (-Queryport) _TCP_ = 7775

Response on HLSW is **SERVERIP**:**PORT**:**QUERYPORT**

**Comment by IamDontNoob** [comment]
Hello.

If game server needed for test, here is running server details

188.124.36.235
UDP (game) 7777
UDP (query) 7776
TCP (file) 7775

**Comment by Austinb** [comment]
Appears to be OGP based - https://github.com/mTxServ/php-open-game-protocol-client

**Comment by IamDontNoob** [comment]
@Austinb hello, yes i saw it but im using Open Game Panel and they said Open game panel support only GameQ and LGSL protocols
