### ISSUE TITLE
New Game Request: SCP:SL

### ISSUE THREAD

**Issue by ju-ce** [Austinb/GameQ#513]
Hello, i hope someone can create a request for **SCP: Secret Laboratory** Game.

Clientport _UDP_ = 27015
_no more informations_

Log Reguest is, idk:
`[NM] DataReceived: bad! 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)`

**Comment by Austinb** [comment]
From what I can find it looks like it does not support querying in the traditional sense - https://steamcommunity.com/app/700330/discussions/0/1697167355229575012/

If you can provide documentation on the query protocol or another querying library that supports this game please provide that information. Without that information this game will not be added.
