### ISSUE TITLE
Array problem

### ISSUE THREAD

**Issue by RealStr** [Austinb/GameQ#515]
`$GameQ->addServers($servers);

    $servers = [
		    [
			    'type' => 'rust', 
			    'host' => '136.243.95.38:28015', 
		    ],
		    [
			    'type' => 'csgo', 
			    'host' => '92.119.148.31:27015', 
		    ],
	    ];`

Notice: Undefined variable: servers in E:\XAMPP\htdocs\home\GameQ-3.0.14\src\demo.php on line 6

Fatal error: Uncaught TypeError: Argument 1 passed to GameQ\GameQ::addServers() must be of the type array, null given, called in E:\XAMPP\htdocs\home\GameQ-3.0.14\src\demo.php on line 6 and defined in E:\XAMPP\htdocs\home\GameQ-3.0.14\src\GameQ\GameQ.php:201 Stack trace: #0 E:\XAMPP\htdocs\home\GameQ-3.0.14\src\demo.php(6): GameQ\GameQ->addServers(NULL) #1 {main} thrown in E:\XAMPP\htdocs\home\GameQ-3.0.14\src\GameQ\GameQ.php on line 201

**Comment by Austinb** [comment]
You have your order messed up.  Array `$servers` must be defined before you try to pass it to `addServers()`.

**Comment by RealStr** [comment]
oh.. thanks
