### ISSUE TITLE
New Game Request: Farming Simulator 19

### ISSUE THREAD

**Issue by Martin-Rider** [Austinb/GameQ#516]
Hello,

Can somebody create an Protocol for the game Farming Simulator 19/20?

Clientport TCP: 10823
Clientport UDP: 10823

**Comment by IamDontNoob** [comment]
Farming simulator has his own Control panel included in to dedicated server.

**Comment by Austinb** [comment]
If you can provide documentation on the query protocol or another querying library that supports this game please provide that information. Without that information this game will not be added.

**Comment by Martin-Rider** [comment]
https://gdn.giants-software.com/documentation.php

Is that enough?

**Comment by Austinb** [comment]
That link does not appear to have any documentation on remotely querying a Farming simulator server.  Looking for specific documentation or if there is another query program that can query that information we can use that to build our own version.
