### ISSUE TITLE
New Game Request: RageMP 

### ISSUE THREAD

**Issue by Hembi** [Austinb/GameQ#517]
Hello,

Please add support to RageMP:
https://wiki.rage.mp/index.php?title=Server_settings

**Comment by Austinb** [comment]
If you can provide documentation on the query protocol or another querying library that supports this game please provide that information. Without that information this game will not be added.

**Comment by Hembi** [comment]
Which information do you need to implement a game?

**Comment by Austinb** [comment]
Need some kind of example or documenation that shows how you can query a RageMP server for server information.  What kind of protocol would help as well such as Source (A2S), GameSpy, Quake, etc...

**Comment by SugarD-x** [comment]
I'm not sure if this helps, but the only third-party source I could find that provided query services for RAGE MP besides the developers themselves was gs4u.net. I'm not sure how they are doing it, though. If you are able to add this, I would be more than happy to use GameQ.

**Comment by IamDontNoob** [comment]
Not found any information, but asked support on their forums
https://rage.mp/forums/topic/7519-querying-rage-mp-server/?tab=comments#comment-27287

**Comment by IamDontNoob** [comment]
@Austinb admin said

> By default servers don't expose any query mechanism, you could use masterlist API though: https://cdn.rage.mp/master/

so, as i understand, it is impossible to add query?

**Comment by Austinb** [comment]
No its easy to add the query using that list.  Just have to find the server in the list, assuming it is listed there.

**Comment by IamDontNoob** [comment]
Here is server details
name in that list: RageMP - GameQ Testing (https://rage.mp/masterlist/)
IP: 95.217.87.12
Ports used by server:
UPD 22005
TCP 22006
UDP 53814
