### ISSUE TITLE
Generic Source Protocol

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#52]
Source's A2S query system is used by every valve game/mod.  Can you add a generic query called "source"?  Using gmod or tf2, etc. is confusing for other games/mods.

**Comment by Austinb** [comment]
https://github.com/Austinb/GameQ/blob/v2/gameq/protocols/source.php

Note not all games use source properly hence why most of them have their own class which extends the source base class.  (e.g https://github.com/Austinb/GameQ/blob/v2/gameq/protocols/cscz.php)  Also to allow for different default ports and so the result has the proper name in the response.

**Comment by Ruok2bu** [comment]
Ah, so which class should i use for unlisted valve games/mods?  TF2 class?

**Comment by Austinb** [comment]
Source should work for all games in a general sense.  The issues comes in with specific mods that are older.  The default should be source for any steam based games assuming it uses the source query protocol (A2S).  There are some games on steam that use Gamespy3 for example.

**Comment by Ruok2bu** [comment]
There's no identifier called "source" though.  It's all game specific.

**Comment by Austinb** [comment]
You can specify source as the type instead of say tf2.  It should work, if not I will make an issue and fix it.  Did the same thing with the quake/gamespy classes a while ago.

**Comment by Ruok2bu** [comment]
Ah, i was wondering cause its not listed on the list.php page.

**Comment by Ruok2bu** [comment]
I just tried source as the identifier and i got this:

Fatal error: Cannot instantiate abstract class GameQ_Protocols_Source in W:\XAMPP\htdocs\gameq-v2\GameQ.php on line 324

**Comment by Austinb** [comment]
I will fix that
