### ISSUE TITLE
Eco

### ISSUE THREAD

**Issue by Knriykas** [Austinb/GameQ#521]
Had a question if you could add the game Eco?

Steam Link: https://store.steampowered.com/app/382310/Eco/

**Comment by ju-ce** [comment]
https://github.com/Austinb/GameQ/issues/427

**Comment by uilson** [comment]
The game Eco is already present on GameQ since 2018. 

https://github.com/Austinb/GameQ/commit/6bfed5d6216e3c0183b778c79919114d5da6aa81

Next time, please, at least search the protocols folder before open an issue. 

@Austinb I believe this can be closed.
