### ISSUE TITLE
List of all supported Games

### ISSUE THREAD

**Issue by MDMAN** [Austinb/GameQ#523]
Can I have a list of all supported Games? 

I want do see also the name and longname - Variable and also the Name of the .php-File.

Is here a list?

**Comment by uilson** [comment]
If you want all the games supported, OPEN THE PROTOCOLS FOLDER.
https://github.com/Austinb/GameQ/tree/v3/src/GameQ/Protocols

all the supported games are there. Each file has the full game name inside, open the files.

@Austinb this can be closed..

**Comment by Austinb** [comment]
Also https://github.com/Austinb/GameQ/wiki/Supported-servers-list-v3 but it is probably out of date a bit. 

There is also this https://github.com/Austinb/GameQ/blob/v3/examples/list.php
