### ISSUE TITLE
New Game Request: Terraria

### ISSUE THREAD

**Issue by MDMAN** [Austinb/GameQ#524]
Here are a new Game Request. Can someone make a protocoll for these Game:

https://store.steampowered.com/app/105600/Terraria/

Terraria.

Thank you.

**Comment by Martin-Rider** [comment]
Terraria has already been implemented.

https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Protocols/Terraria.php

**Comment by uilson** [comment]
> Here are a new Game Request. Can someone make a protocoll for these Game:
> 
> https://store.steampowered.com/app/105600/Terraria/
> 
> Terraria.
> 
> Thank you.

Did you even checked the protocols before open an issue?

@Austinb this can also be closed.
