### ISSUE TITLE
Version-Informations

### ISSUE THREAD

**Issue by MDMAN** [Austinb/GameQ#525]
Would it be possible to display the currently used version in the comments, for example? So that in all files you can see exactly which version is currently being used.

It would be nice to include the version numbers in at least one of the main PHP classes.

**Comment by uilson** [comment]
> Would it be possible to display the currently used version in the comments, for example? So that in all files you can see exactly which version is currently being used.
> 
> It would be nice to include the version numbers in at least one of the main PHP classes.

Version of what?
How about, be more specific.. give more details about what you are speaking of, search the protocols files before opening issues.. and so on?

Do you even know how to work with github?
https://github.com/Austinb/GameQ/releases

@Austinb once again this can be closed.

**Comment by Austinb** [comment]
As @uilson stated you can run this library via versions using the @3.0.x tag via composer or download the files in from the releases section of the repo at https://github.com/Austinb/GameQ/releases.

There are no version tags in the actual .php files and other files available in the library as they are bundled together in releases using Github to manage that.   You can download any version of the files you wish from any point in time when they were commited but I would stick with the released version to prevent any odd issues from cropping up. 

If you wish to display a version number for this library somewhere it is up to you to set a variable somewhere or pull the version property from the composer.json in the root of this project.  I used to tag the main GameQ.php class with a version but more often than not it got skipped when a version was released so I removed it.
