### ISSUE TITLE
New Game Request: rFactor2

### ISSUE THREAD

**Issue by Maximilian-Rupp** [Austinb/GameQ#528]
I wish that the game rFactor2 will be implemented.

**Comment by Austinb** [comment]
If you can provide documentation on the query protocol or another querying library that supports this game please provide that information.  Without that information this game will not be added.

**Comment by Martin-Rider** [comment]
In this case you just have to make a protocol and extend it with Source. It's source-based.

**Comment by Austinb** [comment]
Server list for building and testing - https://gamemonitoring.net/en/servers?game=365960

**Comment by uilson** [comment]
@Austinb support for this game will be included on my next pull request.
