### ISSUE TITLE
Support for Natural Selection 2

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#53]
Can you add support for Natural Selection 2?

I asked what protocol it uses and someone said its A2S, but i tested with A2S and i couldnt get it to work.  My question thread is over at http://www.unknownworlds.com/ns2/forums/index.php?showtopic=121224

Website: http://www.naturalselection2.com/
Forums: http://www.unknownworlds.com/ns2/forums/
Wiki: http://www.unknownworlds.com/ns2/wiki/index.php/Main_Page

P.S. When is the next code push?  Do you have a set schedule or do you commit changes whenever you get them finished?

P.S.S. I sent you a $25 donation ;)

**Comment by Ruok2bu** [comment]
I just emailed one of the devs and he said this to me:

It uses Steamworks so it should just be the standard protocols that Steam games use. I don't know what that protocol is called however.

**Comment by Austinb** [comment]
Do you have a working version of NS2 up and running?  All the servers I can find are either not responding or they are something other than ns2.  Seems that the game doesnt release until next month sometime. 

You can pm it to me if you dont want to give out the info.

**Comment by Ruok2bu** [comment]
Here's a random NS2 server i found: 74.117.239.162:27015

The game does officially release in a month, but its been in playable beta for the past year.

**Comment by Austinb** [comment]
It appears that NS2 does not behave the same as other steam based games.  Most notably the query port is server port + 1.

Reference: http://www.naturalselection.com/forums/index.php?showtopic=118559&st=0&p=1938266&#entry1938266

Will push up a new game class in a couple of minutes.

Thanks for the donation, much appreciated.

**Comment by Ruok2bu** [comment]
:D

**Comment by Ruok2bu** [comment]
If query port is set to something other than 27015, wont that class break? (i noticed it's hard coded to 27016)

**Comment by Austinb** [comment]
The coded port is the default in case you do not specify one when you add the server to be queried.  For example if you add a NS2 server at 127.0.0.1 but do not specify the port it will set the server as 127.0.0.1:27016 when it is added (via addServer() or addServers()).  In all cases if a ip:port combination is given when adding the server that port will override the default one defined by the class (27016 for NS2, 27015 for other source games).

The default is there as a fail safe because all queries require the port to be defined because the connection has to have a port to connect to the server on.  I could change it to ignore servers without ports but this is a bit friendlier I think.

**Comment by Ruok2bu** [comment]
Ah oops :X i didnt think of that.

**Comment by Hellcube** [comment]
I cant make my Natural Selection 2 server to showup :/ something changed?

<?php
// Include the main class file
require '../GameQ.php';

$gq = new GameQ();
$gq->addServer(array(
    'id' => 'Natural Selection 2',
    'type' => 'ns2', 
    'host' => '91.121.64.194:27015',
));

// Request the data, and display it
try {
    $data = $gq->requestData();
    print_r($data);
}

// Catch any errors that might have occurred
catch (GameQ_Exception $e) {
    echo 'An error occurred.';
}

?>

RESULT:

Array ( [Natural Selection 2] => Array ( [gq_online] => [gq_address] => 91.121.64.194 [gq_port] => 27015 [gq_protocol] => source [gq_type] => ns2 [gq_transport] => udp ) )

**Comment by sdieunidou** [comment]
Same problem

array(6) { ["gq_online"]=> bool(false) ["gq_address"]=> string(14) "X.X.X.X" ["gq_port"]=> string(5) "27030" ["gq_protocol"]=> string(6) "source" ["gq_type"]=> string(3) "ns2" ["gq_transport"]=> string(3) "udp" }

My server NS2 is online.

**Comment by Hellcube** [comment]
It's host problem. I moved my script from OHV server to new host and it works. I think it has something to do with bzip2 commpresor not supported.

**Comment by Austinb** [comment]
Yes please check that you have at least bzip2 compiled into php if you are doing Steam based games.  A lot of the steam games used a compressed response for player info and some use it for all server info. If you do not have bzip2 the scripts will just silently skip the information it cant decompress and might explain the behavior you are seeing.

**Comment by sdieunidou** [comment]
I'm sorry, we just forget to used the port + 1 for natural selection 2.

So .. no problem, sorry !
