### ISSUE TITLE
Output player array to comma list?

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#531]
The last few days ive been trying to get the player array to display as a comma separated list of player names. Everything i do results in errors.

My latest failed attempt is this:
`$playerarray = $results[$i]["players"];
$playerlist = implode(', ', array($playerarray));
echo "$playerlist";`

What's the correct way of displaying the players in a server as a list of player names on the same line separated by comma's?

**Comment by uilson** [comment]
You are doing it wrong because in the example you posted, you are trying to get the array of players from the $results, but the $results is an array (check the example response quote below), so if you don't say the id of the array (the IP:PORT) it will give you an error.

them you are trying to [implode](https://www.php.net/manual/en/function.implode.php) a list of arrays (assuming you get the players after you use the ip:port like I said) while trying to put the results inside an array, this does not work, because implode does not work that way, and you cant throw an [array inside another array](https://www.php.net/manual/en/book.array.php) that way.

 I suggest you to consult the [php.net](https://www.php.net/), and get familiar with some of the things you are trying to use.

```
[85.93.88.202:6003] => Array
        (
            [hostname] => ~IsR~GTChamp_Phillip
            [map] => PhillipIsland
            [max_players] => 46
            [num_bots] => 5
            [num_players] => 3
            [os] => w
            [password] => 0
            [players] => Array
                (
                    [0] => Array
                        (
                            [id] => 0
                            [name] => Toni Vilander
                            [score] => 0
                            [time] => 417026.03125
                            [gq_name] => Toni Vilander
                            [gq_score] => 0
                            [gq_time] => 417026.03125
                        )

                    [1] => Array
                        (
                            [id] => 0
                            [name] => Marco Holzer
                            [score] => 0
                            [time] => 417026.03125
                            [gq_name] => Marco Holzer
                            [gq_score] => 0
                            [gq_time] => 417026.03125
                        )

                    [2] => Array
                        (
                            [id] => 0
                            [name] => Johnny O'Connell
                            [score] => 0
                            [time] => 417026.03125
                            [gq_name] => Johnny O'Connell
                            [gq_score] => 0
                            [gq_time] => 417026.03125
                        )

                )
)
```

You can do it this way:
```
$totalPlayers = $results['IP:PORT']['gq_numplayers']-1; //get the num of players on the server
$list ="";
for($i = 0; $i <= $totalPlayers; $i++){ //runs for the number total players the players array, example: for 5 players it runs 5 times
    if(empty($results['IP:PORT']['players'][$i]['name'])){//checks if the player has name, if not adds  "Unknown" to the list, in place of the empty name.
        $name = "Unknown";
    } else {
        $name = $results['IP:PORT']['players'][$i]['name'];//adds the name off the player to the list
    }
    $playerList[$i] = $name; //this adds them to an array
    $list.=$name."; "; //this creates a list of names separated by ;
}

print_r($playerList);
echo $list;

/*
Result of "print_r($playerList);":
Array
(
    [0] => Toni Vilander
    [1] => Marco Holzer
    [2] => Johnny O'Connell
)

Result of "echo $list;":
Toni Vilander; Marco Holzer; Johnny O'Connell; 
*/
```

**Comment by Austinb** [comment]
Another option that is a cleaner (for me anyway) is to use [array_map](https://www.php.net/manual/en/function.array-map.php) or something similar that allows you to use a callback function to pull out and return only the values you care about from the list of player arrays. 

You could do something like:
```php
$playersOnly = array_map(function($player) {
    return $player['gq_name'];
}, $results['your_server_id']['players']);
print_r($playersOnly);
```
Code above may not work.  Writing it from memory and did not test it :\.

**Comment by uilson** [comment]
> Another option that is a cleaner (for me anyway) is to use [array_map](https://www.php.net/manual/en/function.array-map.php) or something similar that allows you to use a callback function to pull out and return only the values you care about from the list of player arrays.
> 
> You could do something like:
> 
> ```
> $playersOnly = array_map(function($player) {
>     return $player['gq_name'];
> }, $results['your_server_id']['players']);
> print_r($playersOnly);
> ```
> 
> Code above may not work. Writing it from memory and did not test it :.

yes that way also works.
Using my previous response example for the code Austin wrote the result would be:
```
Array
(
    [1] => Toni Vilander
    [2] => Marco Holzer
    [3] => Johnny O'Connell
)
```

To show a list of players separated by the comma's you should also do this:
`echo implode(',', $playersOnly);`

for the result to be:
`Toni Vilander,Marco Holzer,Johnny O'Connell`

**Note** that this will also show:
`,Toni Vilander,Marco Holzer,Johnny O'Connell`

if a player name is empty in a list of players, like:
```
Array
(
    [0] => 
    [1] => Toni Vilander
    [2] => Marco Holzer
    [3] => Johnny O'Connell
)
```

**Comment by Ruok2bu** [comment]
OMG, THANK YOU!

I was consulting everything i could find (stackoverflow, php.net) and im a beginner at php.  Tried dozens of different examples i found online and they all failed :(
