### ISSUE TITLE
Post Scriptum Support

### ISSUE THREAD

**Issue by imLiaMxo** [Austinb/GameQ#532]
Be able to query Post Scriptum servers!

**Comment by uilson** [comment]
Will take a look.
But please update your post with required/helpfull info. 

Check other requests made before yours.

**Comment by imLiaMxo** [comment]
Hi!
So using the game 'squad' works perfectly for Post Scriptum!

**Comment by uilson** [comment]
@Austinb support for this game will be included on my next pull request.
