### ISSUE TITLE
Add back Hidden & Dangerous 2

### ISSUE THREAD

**Issue by ehylla93** [Austinb/GameQ#538]
Hello,

in the new version of GameQ had2 is not present anymore.

HD2 is using gamespy2 protocol. For testing purpose IP and ports:

IP: 88.198.6.71
Port: 3001
Query: 3004

It's callable via:

$GameQ = new \GameQ\GameQ();
$GameQ->addServer([
'type' => 'gamespy2',
'host' => '88.198.6.71:3004',
]);
$results = $GameQ->process();
print_r($results);

But gq_name print **Gamespy2 Server**.

Regards

**Comment by ehylla93** [comment]
It's callable via:

$GameQ = new \GameQ\GameQ();
    $GameQ->addServer([
        'type' => 'gamespy2',
        'host' => '88.198.6.71:3004',
    ]);
    $results = $GameQ->process();
    print_r($results);

**Comment by uilson** [comment]
Took a look at previous GameQ versions, that game does not appear to have ever been in GameQ.

Please make sure you are not mistaken.
If you have the file from a previous version, please add it here so that I can take a look.

Also add another server IP:Port to query during the need tests, when/if this gets implemented.

@Austinb since I'm gonna be pushing a new batch of protocols and a few updates some time soon, I will also take a look at this,  and incorporate it on the batch for my next pull request.

**Comment by ehylla93** [comment]
Strange.. I attached my current running version of GameQ ( $Id: GameQ.php,v 1.13 2009/03/05 13:17:38 tombuskens Exp $  ) here. I'm just using it only for had2 at the moment.
[gameq.zip](https://github.com/Austinb/GameQ/files/4474323/gameq.zip)

88.198.6.71:3008
79.143.187.92:11004
79.143.187.92:11008

**Comment by uilson** [comment]
@ehylla93 Thank you for the file and the IPs.

I took a look at your file and it in fact its there, strange that I could not get the revision 1.41 (gameq v1.13) anywhere on the repository.

Anyway, I will look into adding it now.

**Comment by Austinb** [comment]
I forked GameQ back at version 1.12 way back when because they were not keeping it updated for a project I was working on.  You will have to go to the old sourceforge site to find any releases after 1.12.

**Comment by uilson** [comment]
> I forked GameQ back at version 1.12 way back when because they were not keeping it updated for a project I was working on. You will have to go to the old sourceforge site to find any releases after 1.12.

I got that, the part that confused me here was that your forked v1.12 has the "revision 1.42" of the "games.ini" and the original v1.13 has the "revision 1.41" with other protocols, like had2, guess they updated the file and not the revision.
___
Anyway, 
@ehylla93  I leave you the file here, before I commit the changes, as I'm waiting to catch a server full or almost with players, to run the tests to make sure it parses all ok. 
I've done tests and it came back good, just want o be sure for a full server.

Just copy this to your GameQ v3 protocol folder, and use **had2** as a protocol when adding servers.

[Had2.zip](https://github.com/Austinb/GameQ/files/4482833/Had2.zip)

**Comment by ehylla93** [comment]
Thank you! Well, to find a full server is pretty impossible. But I will implement this version tomorrow to in serverlist website

**Comment by ehylla93** [comment]
Had time today, implemented it here: https://avmg.eu/hd2_viewer/

**Comment by uilson** [comment]
Glad you can confirm it works nice.
I have tested it in a server that had a limit of 32 players and 20 players online, and it returned them fine, so next pull request I make will include this.
