### ISSUE TITLE
Cs Go Team support

### ISSUE THREAD

**Issue by Blackfire499** [Austinb/GameQ#539]
Hey guys i'm trying to print Player and Teams but the output says there are no Teams 
maybe its just me but i can only get a list of players

**Comment by Austinb** [comment]
No team information according to https://developer.valvesoftware.com/wiki/Server_queries#Response_Format_2  See note at the end of the section

` Warning: CS:GO Server by default returns only max players and server uptime. You have to change server cvar "host_players_show" in server.cfg to value "2" if you want to revert to old format with players list. `

**Comment by Blackfire499** [comment]
Oh didn't know that to bad but thanks for the quick answer
