### ISSUE TITLE
Very slowly

### ISSUE THREAD

**Issue by Takanashi-Rikka1** [Austinb/GameQ#540]
i have quection
GAMEQ its good for publish game servers like "GameTracker"?
or 
https://github.com/xPaw/PHP-Source-Query

its better ?

im ask because im use GAMEQ
in GameTracker.co.il

and i have some problem and i put function its take info every 1min

because every 1 sec its load pages 10-20 sec

so if someone can told me what better and maybe its my developer do some wrong..

**Comment by Austinb** [comment]
Whatever you use the library for or if you use a different library it is highly recommend you cache that data returned from querying servers for at least 30 seconds.  Many game servers will start to drop your traffic if you query them too often. 

You should **never** rely on the visting client to do query work for you.  There should always be running processes in the background that do the heavy lifting on a known list of servers.  The client interface should just display whatever cached data you have stored.   Doing anything less and you are asking for all kinds of issues. 

Best of luck.

**Comment by Takanashi-Rikka1** [comment]
Tanks for ur answer

Sorry but im dont understand u
Im use in ur GAMEQ to take info from games servers
I add link for my website..

If u can send me ur email / discord or something 
My :
Talnaim2323@gmail.com

and we can talk in PM
Maybe u can help me (For payment)
its ur libarly so i think u can get the best service for me.

Ty anyway Austinb 
Very appreciate
