### ISSUE TITLE
ARMA 3 tests causing PHP 7.4 to fail

### ISSUE THREAD

**Issue by Austinb** [Austinb/GameQ#546]
The issue is the `hexdec()` call at https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Protocols/Arma3.php#L156.  This is new in PHP 7.4 (https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.invalid-base-characters) but is causing PHP Unit to fail out thus causing the build to fail in PHP 7.4.  Not sure if the tests are bad or if something else is going on.   It is data sets 2_ & 4_.

Also the tests for #382 are failing for the same reason.

**Comment by bumbummen99** [comment]
It is also no longer working for me, failing on the mentioned line. Server is 138.201.20.99:2302. It will fail parsing the mods.
