### ISSUE TITLE
Fail to query other servers

### ISSUE THREAD

**Issue by SamuelGold** [Austinb/GameQ#547]
Hello,
I found a strange result, if one of Team Speak servers sends an empty answer or refuses connection, then the GameQ does not query others. I turned on the debug option, and got an exception:
`Error creating socket to server xx.xx.xx.xx:10011. Error: Connection refused`
If to pass throw this exception and to go further, then an another one appears:
`GameQ\Protocols\Teamspeak3::processResponse Expected header '' does not match expected 'TS3'.`
After this QameQ stops asking other servers by break on line 520 in GameQ.php.
Commenting this line helps to solve this problem, but I'm not sure it a right way or not.

**Comment by Austinb** [comment]
The break was added as part of #293 which oddly enough was an issue with TS3.  Not sure why that break was added it was changed over 4 years ago.  Could probably just be a continue instead.

**Comment by SamuelGold** [comment]
Maybe just to remove this break, otherwise socketCleanse will not be executed. Hope it will not cause another bug, which was fixed by break adding 4 years ago:)

**Comment by Austinb** [comment]
Pushed a change to swap the break to a continue. Please pull down v3 and see if that fixes your issue.  I do not have a TS server to test against.

**Comment by SamuelGold** [comment]
I've checked fix with two TS3 servers, seems to work fine, thank you. But shouldn't we do also socketCleanse before continuing?
