### ISSUE TITLE
Last Oasis Support

### ISSUE THREAD

**Issue by HellBz** [Austinb/GameQ#549]
I figured Out Last Oasis is a Part of Source Game for Query Server.

There a Example:
https://api.hellbz.de/tests/gameq/

there is "my" Script ...

https://gist.github.com/HellBz/f4b575962e952c96948b94f05171a56e

**Comment by bumbummen99** [comment]
The api endpoint does seem available tho it does not seem to work anymore. Are your servers still running?

**Comment by Austinb** [comment]
Closing.  If this still needs to be added please create a new issue with updated server information to test against.
