### ISSUE TITLE
Supporf for Call of Duty: Black Ops

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#55]
Can you add support for Call of Duty: Black Ops ?

I wasnt able to find any protocol information.  I tried using the codwaw protocol (since it precedes this game).  I only found this for ports: http://findports.com/article/call-of-duty-black-ops

**Comment by Austinb** [comment]
From the wiki page of supported servers:

"Call of Duty: Black Ops - Requires server login to get info, need server to test with."

**Comment by Ruok2bu** [comment]
Ah, nevermind then.  Im using gameq against 3rd party servers so i wouldnt be able to get that info anyways.

**Comment by Austinb** [comment]
Yea that's why I didn't add it.  Most places wont know the server login info to even get into.

**Comment by Ruok2bu** [comment]
Looks like server login is no longer required as GameTracker.com can track servers without this information.  I'm not sure how they did it though.

**Comment by Austinb** [comment]
Unless you have more information such as a forum thread, release notes or any other kind of information about the query protocol and how to access it I will not be able to do much.  Just from looking at the info on gametracker.com it appears it could be Source based but any source query I send does not give me a response which makes me think it is a different port or that is not the correct protocol.

**Comment by Austinb** [comment]
Please reopen if you have any other information.  I am still not able to find anything about the protocol it uses or ports.

**Comment by TacTicToe66** [comment]
I have the protocol info for Black Ops, if you are still willing to add it? You will need to add a way for the web admin to add the rcon password to get all the info.
