### ISSUE TITLE
Unable to locate Protocols class for 'killing floor 2' Issue

### ISSUE THREAD

**Issue by Wesley21** [Austinb/GameQ#552]
Hello,

I'm having a weird issue which I can not seem to get fixed.

I'm getting the following error:

`PHP Fatal error:  Uncaught GameQ\Exception\Server: Unable to locate Protocols class for 'killing floor 2'! in /xx/xx/xx/Server.php:146`

Anyone that can help me fixing this? Would be great!

**Comment by Gasjki** [comment]
It's **killingfloor2**, not `killing floor 2`. This library is using a slug instead of game full name. Please have a look on Wiki page.

**Comment by Austinb** [comment]
@Gasjki Is correct.
