### ISSUE TITLE
The server did not respond within the specified time

### ISSUE THREAD

**Issue by Uncommonly** [Austinb/GameQ#554]
Hi.

No matter what server I'm trying to add, it's always showing as offline and returns same "The server did not respond within the specified time." message

Yes, the server that I'm trying to Q is Online :)

Server is running on php 7.2.0

No php erros. Nohing.

[Link to example](https://simracing.bg/gameq/example.php)

` './configure' '--prefix=/usr/local/php72' '--with-config-file-path=/usr/local/php72/lib' '--with-config-file-scan-dir=/usr/local/php72/etc' '--with-pear=/usr/local/php72/pear' '--mandir=/usr/man' '--enable-ipv6' '--enable-mysqlnd' '--enable-bcmath' '--enable-calendar' '--enable-exif' '--enable-ftp' '--enable-intl' '--enable-mbstring' '--enable-opcache' '--enable-opcache-file' '--disable-huge-code-pages' '--enable-pcntl' '--enable-sysvmsg' '--enable-sysvsem' '--enable-shmop' '--enable-soap' '--enable-sockets' '--enable-wddx' '--enable-zip' '--with-bz2' '--with-curl' '--with-db4' '--with-dbm' '--with-enchant' '--with-freetype-dir' '--with-gd' '--with-gettext' '--with-iconv' '--with-icu-dir=/usr/local/icu4c' '--with-imap' '--with-imap-ssl' '--with-jpeg-dir' '--with-kerberos' '--with-libdir=lib64' '--with-libedit' '--with-libxml-dir=/usr/local/libxml2' '--with-mhash' '--with-mysqli=/usr/bin/mysql_config' '--with-mysql-sock=/var/lib/mysql/mysql.sock' '--with-openssl=/usr/local/openssl' '--with-pcre-regex' '--with-pdo-mysql=/usr' '--with-pdo-pgsql' '--with-pgsql' '--with-png-dir' '--with-pspell' '--with-readline' '--with-snmp=shared' '--with-tidy' '--with-xmlrpc' '--with-xpm-dir' '--with-xsl=/usr/local/libxslt' '--with-zlib' '--with-zlib-dir' `

`Registered Stream Socket Transports | tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2`

`UNIX_SOCKETS | Yes`

`Sockets Support | enabled`

Please help. Thank you.

**Comment by Austinb** [comment]
Need an example PHP call you are running to query against the server.  This error is due to the timeout limit to prevent the script from running forever if a server that is being queried never responds.  It's possible the server you are trying to query will not respond to query requests (i.e. port traffic is being blackholed).

**Comment by Uncommonly** [comment]
It's not just the server that I'm hosting. Any random working server picked from gametracker, it's shows as offline.

**Comment by Austinb** [comment]
Please open this back up if there is still an issue.  Also please provide the exact php code you are using when making the calls to remove that variable.
