### ISSUE TITLE
Internal Error 500: Unable to resolve the host...

### ISSUE THREAD

**Issue by byman64** [Austinb/GameQ#556]
I am getting the following error. It could be a temporary problem, I don't know. Btw how I can manage the error in order to fix error 500?

I found the "class Server extends \Exception" but it is empty.
Please give me a suggest or an example.

thanks in advance
QooL

// ERROR
 [Sat Sep 19 10:18:24.856117 2020] [proxy_fcgi:error] [pid 1701] [client 79.56.40.49:49190] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught GameQ\\Exception\\Server: t 'quakeum.com' to an IP address. in /var/www/clients/client1/web2/web/q3statusbot/monitorv3/GameQ/Server.php:212\nStack trace:\n#0 /var/www/clients/client1/web2/web/q3statusbot/monitorv3/GameQ/Server.php(121): GameQ\\Server->checkAndSetIpPort('quakeum.com:279...')\n#1 /var/www/clients/client1/web2/web/q3statusbot/monitorv3/GameQ/GameQ.php(191): GameQ\\Server->__construct(Array)\n#2 /var/www/clients/client1/web2/web/q3statusbot/monitorv3/GameQ/GameQ.php(208): GameQ\\GameQ->addServer(Array)\n#3 /var/www/clients/client1/web2/web/q3statusbot/monitorv3/index_gameq_ajax.php(77): GameQ\\GameQ->addServers(Array)\n#4 {main}\n  thrown in /var/www/clients/client1/web2/web/q3statusbot/monitorv3/GameQ/Server.php on line 212\n', referer: https://www.quakearea.com/mon/

**Comment by Austinb** [comment]
The solution is in the error.  The actual error is Unable to resolve host.  This is a DNS level issue where the domain/hostname `quakeum.com` is not being resolved to an IP address by the DNS resolver used on whatever server/host you are tying to run the library on.  You can test by trying to `ping quakeum.com` on the server and see if you get an IP address.

Basically if the host is unable to resolve the domain name to an IP the script will give up with an error. I do not believe I can provide any further assistance.
