### ISSUE TITLE
rfactor dedicated server

### ISSUE THREAD

**Issue by SimonTek27** [Austinb/GameQ#562]
Hello,
Is it possible to interface gameq to rfactor 1 ?

thanks in advance
best regards.

**Comment by peppe56** [comment]
Yes, it would be useful for me too, please.

**Comment by peppe56** [comment]
Hello, any New?

**Comment by bumbummen99** [comment]
@SimonTek27 @peppe56 Can you plese provide a server list to work with?

**Comment by Erani0** [comment]
Which version of rfactor?
@peppe56 @SimonTek27

**Comment by peppe56** [comment]
Hello, rfactor1.

Il mar 30 ago 2022 16:04 Erani0 ***@***.***> ha scritto:

**Comment by Erani0** [comment]
@peppe56 Do you happen to have a new server or server list to test?

**Comment by Erani0** [comment]
PR is Open for rfactor and rfactor2
After Accept u can use it @peppe56 & @SimonTek27

**Comment by peppe56** [comment]
Hi, private server.


Il mer 31 ago 2022 14:30 Erani0 ***@***.***> ha scritto:

**Comment by Erani0** [comment]
What do you mean?
I wrote a Protocoll file to query servers, just as you asked.
@peppe56

**Comment by Erani0** [comment]
Can be closed PR has been added
