### ISSUE TITLE
Minecraft Bedrock Edition

### ISSUE THREAD

**Issue by Erani0** [Austinb/GameQ#566]
Any Option to make request to Bedrock Server? 
The Minecraftpe protocol not Work

**Comment by Austinb** [comment]
Need documentation on how to query the server type.  Do not have time to really spend on this project currently so want to use what time I do have for fixes and not hunting for documentation.  Thanks.

**Comment by Austinb** [comment]
Please reopen if you have more information.

**Comment by Erani0** [comment]
I use the Gameviewer from @TitusKirch  https://tkirch.dev/product/gameserver-viewer/#general

and he use your libary

**Comment by TitusKirch** [comment]
You contacted me in my support area 4 hours ago, I'll give you a call right there.
