### ISSUE TITLE
Valheim dedicated Server

### ISSUE THREAD

**Issue by TheFrodo** [Austinb/GameQ#569]
Is it possible to interface gameq to Valheim ?

Game port | 2456
Query port | 2457

https://store.steampowered.com/app/892970/Valheim/

**Comment by crtxz** [comment]
Looking for this as well

**Comment by Bradler26** [comment]
I would love this as well

**Comment by R3miiTV** [comment]
please add

**Comment by bumbummen99** [comment]
Fixed by #619
