### ISSUE TITLE
Five m players list

### ISSUE THREAD

**Issue by Supryk** [Austinb/GameQ#572]
Any chance to add  players list to five m?

https://github.com/citizenfx/fivem

thay give orginal servers list and thay have players list

**Comment by Erani0** [comment]
With the new protocol file it is now also possible to display the players 
Link to PR https://github.com/Austinb/GameQ/pull/656

Edit Fresh PR now is Open

**Comment by Austinb** [comment]
Since #656 has been merged I am going to close this issue.
