### ISSUE TITLE
PHP 8.x support

### ISSUE THREAD

**Issue by ZekyWolf** [Austinb/GameQ#579]
Can be added support for PHP 8.x?

**Comment by gOOvER** [comment]
Please. PHP 8 is stable since a long time and old Versions are EOL like 7.3

**Comment by ZekyWolf** [comment]
> Please. PHP 8 is stable since a long time and old Versions are EOL like 7.3

Well, i tested and after i add 3rd server to list, its start causing problems (if i remember right, something with bad parsing name).

**Comment by gOOvER** [comment]
> > Please. PHP 8 is stable since a long time and old Versions are EOL like 7.3
> 
> Well, i tested and after i add 3rd server to list, its start causing problems (if i remember right, something with bad parsing name).

I test it too, and no Server Query working
