### ISSUE TITLE
Unusually Slow?

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#58]
I have GameQ set to query 26 servers and its taking over 4 minutes just to query those servers.  Is that normal?

HLSW can query 6 servers in under 2 seconds (for the same info).  Why is GameQ so slow?

**Comment by Austinb** [comment]
Without knowing more information I am unable to help.  What is your timeout set to?  Are the servers located all over the world or in one specific region?

**Comment by Ruok2bu** [comment]
Ah, i found out that the reason why its so slow is it uses Round Robin on a single connection.
