### ISSUE TITLE
Source protocol changes

### ISSUE THREAD

**Issue by Meathoook** [Austinb/GameQ#581]
Changes info here: https://steamcommunity.com/discussions/forum/14/2974028351344359625
It appears there is some new changes to the source protocol that I think is starting to roll out if you read the latest comments. 

There is also some info under A2S_INFO on https://developer.valvesoftware.com/wiki/Server_queries

When I try TF2 I sometimes get `GameQ\Protocols\Source::processResponse response type 'A' is not valid` in the source protocol and for Valheim I get it all the time (it worked with source protocol before the latest update).

Dunno if this is the cause for the problems I get but as the response is 'A' it might be.

Testing on servers:
TF2: 87.117.217.32:27018
Valheim: 134.195.42.216:2457

**Comment by bumbummen99** [comment]
@Meathoook  Can you provide more information under what circumstances you got that exception? I just queried the top 50 valheim servers on Battle Metrics 25 times each without reproducing this a single time.

**Comment by Meathoook** [comment]
Think this problem was solved with #591 with adding %s last in PACKET_DETAILS for the Source protocol.
Dunno if it's the correct solution for the changes they made but querying with GameQ started working again for these games after adding it when I tested earlier.

**Comment by bumbummen99** [comment]
> Think this problem was solved with #591 with adding %s last in PACKET_DETAILS for the Source protocol. Dunno if it's the correct solution for the changes they made but querying with GameQ started working again for these games after adding it when I tested earlier.

You are right, i reverted the changes and the issue started to surface. Therefore i am going to close this ticket, please respont to this ticket or create a new one and reference this one if the issue does resurface.
