### ISSUE TITLE
Is  this Project now dead?

### ISSUE THREAD

**Issue by gOOvER** [Austinb/GameQ#587]
Is this Project now really dead? No Updates, no php 8 Support, not really support.

MB some can Fork this and let GameQ stay alive

**Comment by ZekyTheWolf** [comment]
Looks like yes, it will be nice if someone from community will take it under wings :D

**Comment by Austinb** [comment]
It is not dead per se but I can not spend time anymore debugging connection issues or tracking down changes/documentation for game protocols to keep them correct (i.e. ARMA 3) or to add new ones.   I am happy to merge in any pull requests but they MUST have tests to prove the protocol class is doing its job and those tests MUST pass CI (assuming CI is still setup properly). 

I may have some time to spend on PHP8 but that is no guarantee.  If there is anyone else who wants to help take over managing this please let me know.

**Comment by bumbummen99** [comment]
> It is not dead per se but I can not spend time anymore debugging connection issues or tracking down changes/documentation for game protocols to keep them correct (i.e. ARMA 3) or to add new ones. I am happy to merge in any pull requests but they MUST have tests to prove the protocol class is doing its job and those tests MUST pass CI (assuming CI is still setup properly).
> 
> I may have some time to spend on PHP8 but that is no guarantee. If there is anyone else who wants to help take over managing this please let me know.

Id be happy to contribute :+1:. I already did some testing for PHP8 in my fork and it does work tho we have to consider #592

**Comment by ZekyTheWolf** [comment]
> It is not dead per se but I can not spend time anymore debugging connection issues or tracking down changes/documentation for game protocols to keep them correct (i.e. ARMA 3) or to add new ones.   I am happy to merge in any pull requests but they MUST have tests to prove the protocol class is doing its job and those tests MUST pass CI (assuming CI is still setup properly). 
> 
> I may have some time to spend on PHP8 but that is no guarantee.  If there is anyone else who wants to help take over managing this please let me know. 

Currently dont run in to any issue, just missing Discord support :D

**Comment by TitusKirch** [comment]
@Austinb get a few people on board to help you manage the project here, give support, prioritise issues if necessary, etc.

You could also offer additional GitHub disscusions or a Discord for the project in order to further expand the project here.


Greetings
Titus

**Comment by Austinb** [comment]
If anyone else is interested in helping out please feel free to message me via github or make a new discussion.  Closing since there a couple more people working on this project now.  Thank you for your support @bumbummen99

**Comment by bumbummen99** [comment]
Happy to help out! Thanks for the great project 👍
