### ISSUE TITLE
heeeeeeeeeeeeelp!!!!!

### ISSUE THREAD

**Issue by mo7-theif** [Austinb/GameQ#590]
guys I put teknogods in my mw3 but it's not work and I cannot update my teknogods because they tell me unable to check for updates. the server file failed to load. help me pls 😢😢
![Screenshot (1)](https://user-images.githubusercontent.com/98395390/150971750-b5069e8b-0c8c-4ebd-a0a6-a7f92e3a2561.png)

**Comment by ZekyWolf** [comment]
Not related to GameQ.

**Comment by mo7-theif** [comment]
> Not related to GameQ.
]عيث 
]عيث

**Comment by mo7-theif** [comment]
> Not related to GameQ.

Dude can you solve that problem
