### ISSUE TITLE
Upgrade PHPUnit

### ISSUE THREAD

**Issue by bumbummen99** [Austinb/GameQ#592]
PHPUnit removed support for dirty hacks which are being used quite a LOT in the tests, espicially the Query/Core. If we add the necessary getters instead of hacking the access to these properties we could also support PHP8. What is your opinion on this?

**Comment by Austinb** [comment]
Yes it needs to be rebuilt anyway as most of the 7.x series is now EOL or on security only updates.  Would like to keep support but can set the tests to failing for the older versions if it becomes an issue.

**Comment by bumbummen99** [comment]
> Yes it needs to be rebuilt anyway as most of the 7.x series is now EOL or on security only updates. Would like to keep support but can set the tests to failing for the older versions if it becomes an issue.

I have got it working with tests from 5.8-8.1 in my fork thought we will have to replace all hacks with genious getters. Also i would like to get rid of mocking if it is possible so we can monkey patch host resolution and fake DNS results for the tests.

**Comment by bumbummen99** [comment]
Fixed by #613
