### ISSUE TITLE
DNS mocking

### ISSUE THREAD

**Issue by bumbummen99** [Austinb/GameQ#604]
We need to mock hostname resolution for tests. Right now `game.mythmoor.com` changed its IP so the test for Wurm is failing.

Strategies:

1) Monkey patch - this will require to get rid of **all** mocking in tests as we will have to override the global function IN namespace (PHPUnit Mocks are global namespace with unique name)

2) DNSResolver class - Just abstract host resolution, this will decrease code coverage but overall is "better style"

**Comment by bumbummen99** [comment]
Monkey patch example: https://github.com/symfony/phpunit-bridge/blob/5.3/DnsMock.php

**Comment by Austinb** [comment]
Looks good.  One note is I had this issue in the past and the solution was to make sure all tests had ip addresses.  The testing never did any remote connections to the specified IP addresses in the tests. They were just there for completeness and to verify the response data was still correct for the protocol (i.e. IP address is returned and matches the test data).  

However you guys want to make this work with DNS entries should be fine so long as the tests still run if the DNS entry is taken down.

**Comment by bumbummen99** [comment]
> Looks good. One note is I had this issue in the past and the solution was to make sure all tests had ip addresses. The testing never did any remote connections to the specified IP addresses in the tests. They were just there for completeness and to verify the response data was still correct for the protocol (i.e. IP address is returned and matches the test data).
> 
> However you guys want to make this work with DNS entries should be fine so long as the tests still run if the DNS entry is taken down.

Yeah now it is possible to mock the DNS. This is so that we keep coverage for the gethostbyname line (for those that use it) but at the same time no connection is actually made.
