### ISSUE TITLE
Detect Actual Players Instead of Players & Bots

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#63]
In GoldSource, Source and Orangebox its possible to detect the true number of players on a server (excluding bots).  Can you add this functionality to GameQ ?

The sourcebans query protocol is able to do this.  You can get it at http://code.google.com/p/sourcebans/downloads/list

The query file is in: includes/CServerInfo.php

**Comment by Ruok2bu** [comment]
_Bump_

**Comment by Austinb** [comment]
The parameter you are looking for is num_bots.  It is already available for source games, will push fix for goldsource.
