### ISSUE TITLE
New Game: Satisfactory

### ISSUE THREAD

**Issue by Kaphalor** [Austinb/GameQ#635]
Please add Satisfactory:
https://satisfactory.fandom.com/wiki/Dedicated_servers#Command_line_options

**Comment by Erani0** [comment]
Satisfactory is currently not supported, even for the Steam favorites, so it may take a while before support is provided

**Comment by Austinb** [comment]
Best I could find about query support - https://questions.satisfactorygame.com/post/61834537831c852052359e9c.  Since this game is Early Release it is probably the last thing on the list for them.  May be they will add it to source (A2S) at a later date.
