### ISSUE TITLE
New Game: V Rising

### ISSUE THREAD

**Issue by Kaphalor** [Austinb/GameQ#636]
Please add V Rising:
https://vrising.fandom.com/wiki/V_Rising_Dedicated_Server#Server_Configuration

**Comment by byluz** [comment]
Yes, @Austinb please add a new game called V Rising. Thanks

**Comment by Erani0** [comment]
I'll make a pull request later

**Comment by Erani0** [comment]
PR is Open https://github.com/Austinb/GameQ/pull/652
