### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by TitusKirch** [Austinb/GameQ#639]
@Austinb and @bumbummen99 what do you think about creating a new release (version 3.1.0). The last version (3.0.15) is still from 26 Feb 2020. Furthermore, I would suggest that we stick to [Semantic Versioning 2.0.0](https://semver.org/) when naming versions from then on.

ToDos I can think of right now:
- [x] Write changelog
- [x] Adapt composer.json
- [x] Create release

In addition, I would suggest renaming milestone 3.0.16 to 3.2.0 (if we stick to semver) and removing milestone 3.0.17 or renaming it to 3.3.0.

**Comment by bumbummen99** [comment]
Yes, Semver all the way. We will need to manually write the Changelog this time tought 
https://github.com/Austinb/GameQ/blob/v3/.github/release.yml
will do it from the next release on (if we properly tag & format PRs ofc).

**Comment by bumbummen99** [comment]
I re-tagged all the old PRs so Changelog can now just be generated by a click

**Comment by bumbummen99** [comment]
Want to maybe get this one done before a 3.1.0 release
https://github.com/Austinb/GameQ/issues/641

**Comment by MrFallen** [comment]
Create new release please :(

**Comment by bumbummen99** [comment]
Created release v3.1.0
https://github.com/Austinb/GameQ/releases/tag/v3.1.0
