### ISSUE TITLE
[Bug] BF3 + Password server

### ISSUE THREAD

**Issue by A973C** [Austinb/GameQ#64]
When I query a BF3 server, the password info is always defined as '1' even if server is not password protected.

Example: 
8.6.193.230:25220 => Password set
173.199.103.80:25200 => Password unset

Thank you for your help Austinb!

**Comment by A973C** [comment]
Any help to solve this problem,please?

**Comment by Austinb** [comment]
Sorry for the delay was away and couldnt really work on the project.

**Comment by A973C** [comment]
Thank you so much Austin for your fix : it's working like a charm!

Have a nice day!
