### ISSUE TITLE
Minecraft

### ISSUE THREAD

**Issue by yaany** [Austinb/GameQ#641]
CS:GO, Minecraft servers is not working. No player count, or online status :(

Fix ?
WEB: https://gamebot.lv/
MTA works, cs:go not, mc not

**Comment by bumbummen99** [comment]
Your CSGO server is working on my end using dev-master, make sure you do use the correct port.

Minecraft indeed seems broken. It does seem to not have any streams (?) on the following line with value 0:
https://github.com/Austinb/GameQ/blob/97aa7e0579da74c430c7faaae630029979207827/src/GameQ/Query/Native.php#L194


References:
https://wiki.unrealadmin.org/UT3_query_protocol
https://wiki.vg/Query
https://github.com/xPaw/PHP-Minecraft-Query/blob/master/src/MinecraftQuery.php

**Comment by Austinb** [comment]
Just to bump this.  If you look at the readme for the xPaw version, which this protocol is based off of, certain items need to be enabled for the query to work.  This is also listed in the wiki at https://github.com/Austinb/GameQ/wiki/Supported-servers-list-v3

`Minecraft (Gamespy v3) - Requires Minecraft 1.8+ Reference. Requires server settings: enable-query=true & query.port=25565`

Is this enabled on the Minecraft server in question?

**Comment by bumbummen99** [comment]
> Just to bump this. If you look at the readme for the xPaw version, which this protocol is based off of, certain items need to be enabled for the query to work. This is also listed in the wiki at https://github.com/Austinb/GameQ/wiki/Supported-servers-list-v3
> 
> `Minecraft (Gamespy v3) - Requires Minecraft 1.8+ Reference. Requires server settings: enable-query=true & query.port=25565`
> 
> Is this enabled on the Minecraft server in question?

Tested it on mine, the public Nitrado and the Hypixel one - all broke. Hypixel should be properly configured since it does work with the xPaw package (https://skycraft.skyraptor.eu/).

Also checked the inital message against the xPaw version but it is the same so it *should* work

**Comment by Erani0** [comment]
Minecraft java version works without problems
Here are two examples: Minecraft Vanilla and Modded Minecraft 

![Screenshot_20220823-012130_Chrome.jpg](https://user-images.githubusercontent.com/76605008/186036505-bbd8c3f9-8e1e-4e0b-8e0e-e5568889860b.jpg)
![Screenshot_20220823-011953_Chrome.jpg](https://user-images.githubusercontent.com/76605008/186036513-d01c0326-36bf-4a5f-b0a3-2648d8381907.jpg)

CS:GO also works without problems.

**Comment by bumbummen99** [comment]
> Minecraft java version works without problems Here are two examples: Minecraft Vanilla and Modded Minecraft
> CS:GO also works without problems.

Wanna share the cfg for these servers? Also what version of GameQ are you on (`composer show Austinb\GameQ`)?

**Comment by Erani0** [comment]
I use the normal version that you can download. I don't have a special version

**Comment by Erani0** [comment]
@yaany To read the status of your Minecraft server you have to enable enable-query=true in your gameconfig otherwise it won't work 
you can also see this here https://mcsrvstat.us/server/mc.side.lv
and before you ask the readout on the website does not work with GameQ


Here a Simple PHP script to test  

```
<?php
require_once('GameQ/Autoloader.php');
//Please adjust path to Autoloader.php

$servers = [
    [
        'type'    => 'minecraft',
        'host'    => '141.95.59.103:25565',
    ],
    [
        'type'    => 'csgo',
        'host'    => '216.52.148.47:27015',
    ]
            
];

$GameQ = \GameQ\GameQ::factory();
$GameQ->addServers($servers);
$GameQ->setOption('timeout', 5);
$results = $GameQ->process();

$GQ = json_encode($results);

$arr = json_decode($GQ, true);
 
foreach($arr as $key=>$value){
    echo $key . "=><br>" . json_encode($value) . "<br><br>";
}
echo "<br>";

?>

```

**Comment by bumbummen99** [comment]
> $results = $GameQ->process();

Does not work for me with current v3 branch either locally or from GitHub Actions https://github.com/Austinb/GameQ/pull/649/checks

Can you please tell us what version is in the composer.json file inside the GameQ directory? Also please include the PHP Version, you can get it with the command `php -v`. Also how did you obtain GameQ? Did you download it using composer or just directly from github?

**Comment by Erani0** [comment]
I downloaded it directly from github and my php version is 8.1.9
and @bumbummen99 please check your email i have write you

**Comment by bumbummen99** [comment]
Also make sure `query.port` is set to the port you use in your config. Turns out tested servers had this set differenly, once adjusted it does work as intended.
