### ISSUE TITLE
[Bug] BF3 + Fatal error: Uncaught exception 

### ISSUE THREAD

**Issue by A973C** [Austinb/GameQ#65]
When I query this bf3 server(173.199.93.167:25200), i have an error message:

Fatal error: Uncaught exception 'GameQException' with message 'length OOB' in /gameq/buffer.php:106 Stack trace: #0 /gameq/protocols/bf3.php(318): GameQ_Buffer->read(172707616) #1 /gameq/protocols/bf3.php(137): GameQ_Protocols_Bf3->decodeWords(Object(GameQ_Buffer)) #2 [internal function]: GameQ_Protocols_Bf3->process_status() #3 /gameq/protocols/core.php(547): call_user_func_array(Array, Array) #4 /GameQ.php(438): GameQ_Protocols_Core->processResponse() #5 /GameQ.php(420): GameQ->filterResponse(Object(GameQ_Protocols_Bf3)) #6 /json.php(46): GameQ->requestData() #7 {main} thrown in /gameq/buffer.php on line 106

**Comment by Austinb** [comment]
Generally this error means that the response returned was not in the expected format the protocol class was expecting.  Mainly it tries to read a key/value pair from the server response but it does not exist.

If you are having this on multiple servers please let me know.  If it is just one server please provide the ip:port of the server so I can try and test it.  It is possible the protocol responses have changed but I am unaware of any at this time.

**Comment by A973C** [comment]
Hi Austin!

By now, I only found this error on 1 server only (the ip and port was given in my initial post : 173.199.93.167:25200).

Thank you for your feedback, Austin.

**Comment by Austinb** [comment]
For that server I am getting " Error creating socket to server" which is most likely a firewall or something preventing the response from being returned to the server making the query request.

**Comment by A973C** [comment]
I've found a lot of servers with this error. I'm finishing scanning my list and i will give it to you if you're interested

**Comment by A973C** [comment]
Austin, i'm facing the same error while scanning some Battlefield Bad Company 2 servers: 194.153.116.136:25400.
