### ISSUE TITLE
Rising Storm 2 Vietnam Epic + Steam Support

### ISSUE THREAD

**Issue by MadMaxMangos** [Austinb/GameQ#665]
Rising Storm 2: Vietnam added Epic clients back in 2021 and now the query appears to only count Steam users, where you can in-fact have 10-15 epic users on a server.

**Comment by Austinb** [comment]
This library will only display the information provided by the server.  If a game server is not returning all of the information such as bots or crossplay players there is nothing that can be done to fix it on the library.
