### ISSUE TITLE
AA3

### ISSUE THREAD

**Issue by Maxchr** [Austinb/GameQ#67]
Hey m8 i was trying to get this working for my AA3 gameserver but when it's queried the server it just says: The server did not respond within the specified time.

Regards Bust3r

**Comment by Austinb** [comment]
Can you please provide the server information?  Also what version is the server running?

**Comment by Maxchr** [comment]
Servername: Danish Elite Fighters
IP: 108.61.253.124:8777
Query Port: 27020
Running: Americas Army Version 3.3.

Regards Bust3r

**Comment by Austinb** [comment]
I just tested it from my local development machine and it returned the following information:

``` php
Array
(
    [108.61.253.124] => Array
        (
            [dedicated] => d
            [game_descr] => 
            [game_dir] => aa3game
            [gq_address] => 108.61.253.124
            [gq_dedicated] => d
            [gq_gametype] => 
            [gq_hostname] => [Honor Server] Danish Elite Fighters
            [gq_mapname] => Bridge AI
            [gq_maxplayers] => 10
            [gq_mod] => aa3game
            [gq_numplayers] => 0
            [gq_online] => 1
            [gq_password] => 0
            [gq_port] => 27020
            [gq_protocol] => source
            [gq_transport] => udp
            [gq_type] => aa3
            [hostname] => [Honor Server] Danish Elite Fighters
            [map] => Bridge AI
            [max_players] => 10
            [num_bots] => 0
            [num_players] => 0
            [os] => w
            [password] => 0
            [players] => Array
                (
                )

            [protocol] => 17
            [secure] => 0
            [steamappid] => 13140
            [teams] => Array
                (
                )

            [version] => 49
        )

)
```

It is possible the server was blocking your connection.  Some servers have anti-dos mesures built in to keep the server from being pinged or queried to death.

Please let me know if you have any issue with this.  If so please reopen the issue.

**Comment by Maxchr** [comment]
What did u exactly do to get that result??

**Comment by Austinb** [comment]
Here is my code

``` php
$gq = new GameQ();
$gq->addServer(array(
        'type' => 'aa3',
        'host' => '108.61.253.124',
));

$gq->setOption('timeout', 7)
->setOption('debug', TRUE)
->setFilter('normalise');

$results = $gq->requestData(); // Returns an array of results

print_r($results);
exit;
```

**Comment by Maxchr** [comment]
how come i can not get the other info like gametype, hostname, mapname, maxplayers, numplayers ???

Array
(
    [108.61.253.124] => Array
        (
            [gq_address] => 108.61.253.124
            [gq_dedicated] => 
            [gq_gametype] => 
            [gq_hostname] => 
            [gq_mapname] => 
            [gq_maxplayers] => 
            [gq_mod] => 
            [gq_numplayers] => 
            [gq_online] => 
            [gq_password] => 
            [gq_port] => 27020
            [gq_protocol] => source
            [gq_transport] => udp
            [gq_type] => aa3
            [players] => Array
                (
                )
            [teams] => Array
                (
                )
        )
)

**Comment by Austinb** [comment]
I ran that code just now and it worked. I am not sure how you are running the script so it is hard to debug from my end.  Make sure you have the latest version of v2 pulled from git.
