### ISSUE TITLE
Counter-Strike 1.6 return some variables are null

### ISSUE THREAD

**Issue by HybridMind1337** [Austinb/GameQ#675]
Hello!
When I run the server to the stats it shows some variables are null. Any ideas how to fix it?

![index](https://user-images.githubusercontent.com/12223569/199837993-d093a7d3-33d2-4bb6-bf03-bb8862a742db.png)

**Comment by RikoDEV** [comment]
https://github.com/Austinb/GameQ/issues/663

**Comment by Austinb** [comment]
Pulling random servers from https://www.game-state.com/index.php?game=cs work as expected.  I tested the server ip:port shown in that screen capture but I was not able to get any information from it using either the new query call (with the challenge string) or without.  Conversely, both ways work from the servers from the site listed above. 

Please reopen with more information.
