### ISSUE TITLE
Can't get server data

### ISSUE THREAD

**Issue by starcevpro** [Austinb/GameQ#683]
I can’t get data about servers, when executing a command, I get an empty list of servers without waiting, when I change
$gameQ->setOption('write_wait', 50000);
I get an error:
GameQ\Protocols\Source::processResponse response type 'A' is not valid

my response
![image](https://user-images.githubusercontent.com/24702947/207281476-2f97ea58-0087-4c79-96fc-8f0e0adcdfc7.png)

PHP 8.1
Laravel 9
Windows 10 local dev with laragon

46.174.50.145:27016
46.174.50.145:27019
I tested this servers in SourceQuery, and this working.

**Comment by starcevpro** [comment]
I change
            if ($streams === false || ($streams <= 0)) {
to
            if ($streams === false) {
and all working...
what is this?

**Comment by starcevpro** [comment]
https://www.php.net/manual/en/function.stream-select.php

Note:

Be sure to use the === operator when checking for an error. Since the stream_select() may return 0 the comparison with == would evaluate to true:
```php
<?php
$e = NULL;
if (false === stream_select($r, $w, $e, 0)) {
    echo "stream_select() failed\n";
}
?>
```

change in Native.php
```php
if ($streams === false || ($streams <= 0)) {
```
to
```php
if ($streams === false || ($streams < 0) || ($streams === false)) {
```
and all work, please fix

**Comment by starcevpro** [comment]
I'm edit Native.php on 193 line

from
``` if ($streams === false || ($streams <= 0)) { ```
to
``` if ($streams === false || ($streams < 0)) { ```

and all work, please fix this.

**Comment by Austinb** [comment]
Both provided servers work as is without any change to any files as currently available in the v3 branch.  Please try using the v3 branch directly and not the release as it is a little bit behind.   Without any other reasons there should be no need to modify this file.  

My best guess at this point is your requests are getting dropped or interrupted on the destination side for any number of reasons.  If other people are having the same issue with these 2 servers as well as others we can look into it a bit more.
