### ISSUE TITLE
Can u add please  ulti-packet Source response format

### ISSUE THREAD

**Issue by bibi-blocksberg** [Austinb/GameQ#688]
Can u add please the new Multi-packet Source response format

My Provider using new Multi-packet Source response format  and GameQ have problem to Check Csgo Server  Status 

https://developer.valvesoftware.com/wiki/Server_queries#Source_Server

thank you =)

**Comment by bibi-blocksberg** [comment]
My Fix for Source Query Games with Split-Packet / Multi-Packet Response Format

This problem happened when using Path.net Firewall and the Source Query Proxy (SourceQueryFilter) which uses Split-Packet / Multi-Packet Response Format


This solution works for me with Csgo , others were not tested 

https://pastebin.com/mEZBWexr

**Comment by Austinb** [comment]
Please create a pull request with the changes so they can be viewed in line and commented on.
