### ISSUE TITLE
INFO : Support for Medal of Honor Warfighter

### ISSUE THREAD

**Issue by A973C** [Austinb/GameQ#69]
Medal of Honor Warfighter is currelty supported by GameQ using 'bf3' protocol and all informations seems to be returned. However, i have an error message:

Notice: Undefined offset: 24 in gameq/protocols/bf3.php on line 200

**Comment by Austinb** [comment]
BF3 recently added another item at the end of the info query response.  So using bf3 on another game server will probably have this result.  I will try to add this game asap.

**Comment by A973C** [comment]
Thank you! You're the best,Austin!
