### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by gaisindanil** [Austinb/GameQ#692]
Greetings, when receiving the server name, an error arrives in the form: "^4U^5n^7i^5trem^1i^6a ^7EU - GrangerHub.com", but it should be like: "Unitremia EU - GrangerHub.com" what is the problem, help me please...

**Comment by Gasjki** [comment]
Hello! Game type? IP / Port / Query port?

**Comment by Austinb** [comment]
This is mostly likely due to color codes in the hostname field.  There is a strip color filter that can be used to remove these characters before the data is returned.  Please read the wiki for more information.
