### ISSUE TITLE
Response from Rust server

### ISSUE THREAD

**Issue by ReptiDK** [Austinb/GameQ#693]
Hi

Rust is not returning much from a query: 

Array
        (
            [gq_address] => 193.xxx.xxx.xxx
            [gq_dedicated] => 
            [gq_gametype] => 
            [gq_hostname] => 
            [gq_joinlink] => steam://connect/193.xxx.xxx.xxx:27121/
            [gq_mapname] => 
            [gq_maxplayers] => 
            [gq_mod] => 
            [gq_name] => Rust
            [gq_numplayers] => 
            [gq_online] => 
            [gq_password] => 
            [gq_port_client] => 27121
            [gq_port_query] => 27121
            [gq_protocol] => source
            [gq_transport] => udp
            [gq_type] => rust
            [players] => Array
                (
                )

            [teams] => Array
                (
                )

        )

**Comment by Krymonota** [comment]
Due to lack of information, I can't say anything specific to your case, but querying information from Rust servers works fine for me - at least for Rust servers that I'm personally aware of.

**Comment by es1538** [comment]
For example, the server 45.63.67.84:28016 works fine, but for example the server 185.189.255.135:35100 does not work, I tried different ones, some work, and some do not
