### ISSUE TITLE
Empyrion Galactic Survival doesnt show playernames

### ISSUE THREAD

**Issue by ghost** [Austinb/GameQ#694]
Is it possible that also player names are output?

Because currently it shows only the playing time of the player but no name.

**Comment by Austinb** [comment]
Need a server or list of servers to test against.  Using publicly available lists it appears the A2S_rules response does not include player names in the response so there is nothing to display.  Other games do not return player names as well.

**Comment by ghost** [comment]
Here you can use my server:  comgames.de:30000
