### ISSUE TITLE
New Rust query port

### ISSUE THREAD

**Issue by Boy132** [Austinb/GameQ#697]
Rust servers now use a different query port, usually game port + 1.
See https://wiki.facepunch.com/rust/Creating-a-server#importantinformationregardingtheserverqueryportstartingfrom2ndfebruary2023

**Comment by hej-julian** [comment]
https://github.com/Austinb/GameQ/pull/698

**Comment by Austinb** [comment]
Closed as duplicate.

**Comment by Boy132** [comment]
Please reopen this. The PR hasn't been merged. (also, this was never a duplicate)
