### ISSUE TITLE
ArmA 2 OA - Missing player information

### ISSUE THREAD

**Issue by WillWaywell** [Austinb/GameQ#71]
Hi there,

When querying any ArmA 2 Operation Arrowhead server with GameQ, all player data besides names are missing from the result array. Pings, deaths, score, side etc etc is all missing.

I can't for the life of me figure out what it is, so does anyone else have any ideas?

Regards,

Will

**Comment by Austinb** [comment]
This appears to be a bug in the gamespy 3 protocol class.  I will some research and see if this is something specific to ArmA 2 or if this is a broader bug.

Thanks for the find.

**Comment by Austinb** [comment]
It appears that the response from ArmA 2 (& OA) is broken.  The team_ section of the response has all kinds of empty data followed by empty breaks (\x00) which was breaking the old Player/Team information parser from v1 that I adapted.

I just rewrote that section of the code and made a new method for GS3 called parsePlayerTeamInfo which works fine with the old data from BF2, etc and the broke data from ArmA 2.

Note there is only the following information provided by the response: player name, score, deaths & team (if not empty, which is what broke the original parser section).  The response does not provide anything else.

Will push up fixed code shortly.

**Comment by WillWaywell** [comment]
Great stuff mate, thanks a lot!

**Comment by firefly2442** [comment]
I believe this issue is back.  In testing Arma2OA and Arma3, the servers I query with Arma2OA do not show the player names.  There's a commit here: https://github.com/firefly2442/GameQ/pull/1
that has a small fix for scores not showing up all the time (it seems to be different for odd/even numbers of players).  

Not sure if that helps or not.
