### ISSUE TITLE
Stalker and ARMA2 player info  [gamever] => 1.5.10?

### ISSUE THREAD

**Issue by mkden** [Austinb/GameQ#72]
Stalker player info Not work!

Work only [gamever] => 1.6.02 !

test server [ IP: 77.243.98.232 ] [ C_PORT: 5441 ] [ Q_PORT: 5447 ] [ TYPE: stalker ]

and not work ARMA2 [gamever] => 1.5.10

Work only [gamever] => 1.11.86949 !

[ IP: 77.243.98.232 ] [ C_PORT: 5445 ] [ Q_PORT: 5447 ] [ TYPE: arma2 ]

Fatal error: Uncaught exception 'GameQException' with message 'length OOB' in \gameq\gameq\buffer.php:106 Stack trace: #0 \gameq\gameq\buffer.php(282): GameQ_Buffer->read(2) #1 \gameq\gameq\protocols\gamespy3.php(131): GameQ_Buffer->readInt16() #2 \gameq\gameq\protocols\gamespy3.php(203): GameQ_Protocols_Gamespy3->preProcess_all(Array) #3 [internal function]: GameQ_Protocols_Gamespy3->process_all() #4 \gameq\gameq\protocols\core.php(547): call_user_func_array(Array, Array) #5 \gameq\GameQ.php(438): GameQ_Protocols_Core->processResponse() #6 \gameq\GameQ.php(420): GameQ->filterResponse(Object(GameQ_Protocols_Stalker)) #7 \gameq\examples\index.php(24): GameQ->requestData() #8 {main} thrown in \gameq\gameq\buffer.php on line 106

**Comment by Austinb** [comment]
Hello.  I see you have the Q_PORT (which I assume is the query port) is the same for both game servers even though their connection ports are different.  Is this a typo?  Both those games use gamespy3 as the underlying query protocol.

As far as the response from 77.243.98.232:5447 I am only getting the following response:

``` php
string(5) " 0@"
```

Which leads me to believe the server is crashed or is just not responding properly for some reason (addon or something else, I am not familiar with the game server for that game).  Was unable to test any other servers running stalker, all the lists I found the servers did not respond (probably non-standard query port). 

For ArmA2 the query should work regardless of the version of the server as it is just gamespy3 and that protocol has not changed in sometime.  I just tested v2 against 74.201.57.106:2352 which according to the response is running 1.11.86949.  There are others but they were all running 1.62.xxxx and responded properly.  If you have a server running 1.50.xxx I can take a look but I was unable to find one.

If you wish for me to test other server please verify the query ports and ips and list them out like you did before and I will see if there are any issues.

**Comment by mkden** [comment]
Stalker servers [gamever] => 1.5.10:
[ IP: 77.243.98.232 ] [ C_PORT: 5441 ] [ Q_PORT: 5447 ] 
[ IP: 94.244.164.127 ] [ C_PORT: 5445 ] [ Q_PORT: 5448 ]
[ IP: 109.254.8.89 ] [ C_PORT: 9387 ] [ Q_PORT: 9385 ]

all server online test: http://www.greycube.co.uk/lgsl/test/

player info not snow!

**Comment by Austinb** [comment]
Stalker seems to actually be based on Gamespy2 protocol not 3 as GameQ v1 had defined.  Also it appears there may be some issues with the Gamespy2 response (teams, players), not sure.  Please test it out and if there are issues open up a new ticket.

Pushing up fix now.
