### ISSUE TITLE
Mincraft 1.4.2 does not work

### ISSUE THREAD

**Issue by Austinb** [Austinb/GameQ#79]
It seems the protocol has been changed slightly for 1.4.2.

**Comment by Austinb** [comment]
I saw where the protocol has been changed on xPaw and it did not work for 1.4.2.  Does anyone have any issues using GameQ v2 to query any minecraft servers?  The servers I test were running 1.4.6 and they worked as expected.

Reference: https://github.com/xPaw/PHP-Minecraft-Query/commit/b3280af2ca6559400e6c2b8c3847aa2d91e2ec84

**Comment by zeagon** [comment]
Had several reports that no minecraft servers were working as of late, though i recieved no info of the game version ( no way to find out in the scope of the project iam using it )

**Comment by Ruok2bu** [comment]
Works fine for me.  Didnt notice anything odd when querying my server.
