### ISSUE TITLE
Medal of Honor: Allied Assault & Medal of Honor: Spearhead  Don't Work

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#81]
No matter which server i query in either of these 2 games, it always appears offline.  It's odd too since it appears these games dont use a different query port.

**Comment by Austinb** [comment]
Turns out the default query ports for both games are incorrect. 

Query port = server port + 97

Example for 8.12.64.137:12203 you would query at 8.12.64.137:12300

Default fix coming soon.
