### ISSUE TITLE
San Andreas Multiplayer - No Player List

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#82]
Tested against 178.218.214.78:7703
http://www.game-monitor.com/sa-mp_GameServer/178.218.214.78:7703/Samp-Rp.Ru__Server_03__Client_0.3x.html

No player list is displayed.

**Comment by Austinb** [comment]
I just tested using 178.218.214.78:7703 with samp and it worked fine.  Also showed me all of the players, 73 at the time.

Still an issue?  If not please close.

**Comment by Ruok2bu** [comment]
Player list still doesnt display for me.

My result code is:

function print_results($results) {

```
foreach ($results as $id => $data) {

    printf("<h2>%s</h2>\n", $id);
    echo '<pre>'; print_r($data['players']);
    print_table($data);
}
```

Does samp need a different result code?

**Comment by Austinb** [comment]
This is what I used to test:

``` php
$gq = new GameQ();
$gq->addServer(array(
        'type' => 'samp',
        'host' => '178.218.214.78:7703',
));

$gq->setOption('timeout', 7)
->setOption('debug', TRUE)
->setFilter('normalise')
;

$results = $gq->requestData(); // Returns an array of results

print_r($results);
exit;
```

**Comment by Ruok2bu** [comment]
No player list displays for me with that code.  All i see is:

Array ( [178.218.214.78:7703] => Array ( [dedicated] => 1 [gametype] => Samp-Rp.Ru Russia [gq_address] => 178.218.214.78 [gq_dedicated] => 1 [gq_gametype] => Samp-Rp.Ru Russia [gq_hostname] => Samp-Rp.Ru | Server: 03 | Client: 0.3x [gq_mapname] => Russia [gq_maxplayers] => 1000 [gq_mod] => [gq_numplayers] => 80 [gq_online] => 1 [gq_password] => [gq_port] => 7703 [gq_protocol] => samp [gq_transport] => udp [gq_type] => samp [gravity] => 0.008 [map] => Russia [mapname] => Russia [max_players] => 1000 [num_players] => 80 [num_rules] => 6 [password] => [players] => Array ( ) [servername] => Samp-Rp.Ru | Server: 03 | Client: 0.3x [teams] => Array ( ) [version] => 0.3x-1000p [weather] => 10 [weburl] => samp-rp.ru [worldtime] => 06:00 ) )

**Comment by Austinb** [comment]
I would check your code. Perhaps you made some changes trying to debug?  I do that all the time and sometimes forget to remove overriding code. If in doubt clone the repo into another folder and try from there.  I tested in the latest commit I pushed up to github. 

Also do not run any filters or options to see if it helps.

**Comment by Ruok2bu** [comment]
I reinstalled and its doing the same thing.  This is all i have in the php file:

<?php
// Include the main class file
require '../GameQ.php';

$gq = new GameQ();
$gq->addServer(array(
        'type' => 'samp',
        'host' => '178.218.214.78:7703',
));

$gq->setOption('timeout', 7)
->setOption('debug', TRUE)
->setFilter('normalise')
;

$results = $gq->requestData(); // Returns an array of results

print_r($results);
exit;

?>

**Comment by Austinb** [comment]
It seems they changed the limit for player information being returned.   It is now 100 down from 256 in a previous version.  Please try a server with 80ish players and see if it works. Ref: http://wiki.sa-mp.com/wiki/Query_Mechanism#Limitations

I use http://www.game-monitor.com/GameSearch/sa-mp/San_Andreas_Multiplayer.html for a listing

**Comment by Austinb** [comment]
Hmm there maybe an issue in my code processing the query.  I will try and take a look soon.  Not sure if throttled to 100 means will only show 100 or after 100 it doesnt return any clients.

**Comment by Austinb** [comment]
It seems they reduced the player information to 100.  So once the server has more than 100 players (playing/connected) it will no longer return the detailed information about the players.  Kinda sucks but I cant do anything about it.

You can try to petition the coders to remove this limit, not sure why it is there but probably to prevent ddos or performance issues.
