### ISSUE TITLE
Server appears always offline

### ISSUE THREAD

**Issue by xFlip** [Austinb/GameQ#83]
Hi, i have installed a Webserver with Apache2 on Debian.
I uploaded my old website (with GameQ) but all Gameservers seem to be offline on the Homepage. Bzip2, Zlib are installed on the Server and the Firewall is disabled. I dont get any Error.

Thanks, Philip

**Comment by Austinb** [comment]
Have you tested multiple servers or just a specific one?  If you have tried multiple please post a couple of game type and ip:query ports.  Make sure you are querying the query port for the server (not game port).  Most servers have separate query and game connection ports. 

Also there is a debug mode for it to throw errors if there is an issue with connecting to a server.  By default this is turned off.

**Comment by xFlip** [comment]
Hi, thanks for your answer. I found now the problem. It didn't worked because i had set
magic_quotes_gpc = On
magic_quotes_runtime = On
magic_quotes_sybase = On

and now i have changed it to

magic_quotes_gpc = On
magic_quotes_runtime = Off
magic_quotes_sybase = Off

and it worked perfeclty like on the old Webserver! (File: /etc/php5/apache2/php.ini)
