### ISSUE TITLE
Crysis 3 ADD!

### ISSUE THREAD

**Issue by mkden** [Austinb/GameQ#84]
Demo servers:
http://www.multiplaygameservers.com/game-servers/crysis3/

**Comment by Ruok2bu** [comment]
He needs information on the protocol.  Simply linking to a game server doesnt help (as he would have to reverse engineer and that takes a lot of time).  Ask on the official Crysis 3 forums what protocol the game uses.  Hopefully one of the devs will answer.

**Comment by Austinb** [comment]
Doing a quick test using old crysis settings I am unable to get a query working.  My guess is the game will use GameSpy3 but I have no information on the query port. Also was unable to find anything using Google.  Please provide any more information you can find.

**Comment by mkden** [comment]
http://forums.gameservers.com/viewtopic.php?f=31&t=49630

**Comment by mkden** [comment]
http://www.figh7club.com/forum/showthread.php?t=80576

**Comment by Austinb** [comment]
I spent a little bit of time today on this again but I am unable to come up with any definitive information on if crysis 3 is even supports querying.  There is a crysis 3 stats site already but I am unsure how they are getting their data.  I tested serveral different servers that should be online at various ports but was unable to get any response.  I assume it would be the same as crysis 2 but I am unsure of that.

Best info I could find atm is that querying is currently not supported.
- http://www.mycrysis.com/forums/viewtopic.php?f=65&t=60969&p=623839&hilit=query&sid=cbc87ce9e781bd5e355e236180a54c32#p623839
- http://www.mycrysis.com/forums/viewtopic.php?f=65&t=61812

**Comment by mkden** [comment]
Should I use HTTP / XML-RPC protocol in php and rcon password from the server in concol to give commands to the server to get data.

HTTP:received xmlrpc command:status
HTTP:received xmlrpc command:sv_servername
..............

comand in console to get info!

**Comment by Austinb** [comment]
It is possible to use that method and technically GameQ could be modified to send those commands and return the information but would require a server to test with and its rcon password.  This is similar to the issue with COD Black Ops requiring a password to query the server.  In many cases users will not have access to the rcon password. 

Bottom line, I would like to wait and see if a traditional query port is added to crysis3 in the coming patches.  If anyone else has any information on this please let us know.  I do not own the game or play it.

**Comment by Austinb** [comment]
Is there any update for this game and it supporting a traditional query protocol?  Can even be a custom plugin, assuming the game allows them.

**Comment by Austinb** [comment]
I will be unable to do anything to support this game until
a) there is a traditional query protocol added to the game server side (i.e GameSpy3) or
b) I can get access to a populated server with XML-RPC setup (including a password)

If something changes please feel free to reopen this issue or create a new issue.

**Comment by foca68** [comment]
Hi ! I do some php just for hobby,  If you can do something with XML-RPC i can provide you acces to a server. I am have 2 servers Crysis 3 and it will be nice to control from my site.
