### ISSUE TITLE
Freelancer Support

### ISSUE THREAD

**Issue by testoverride** [Austinb/GameQ#88]
Can we get freelancer support added back to gameq?

**Comment by Austinb** [comment]
I started on this tonight.  The code from the v1 library that parses this doesnt seem to work properly, or the standard has changed.  Can you provide any documentation on the query protocol response the server sends?  Is it in the server manual or something.  This is a pretty old game and any searches I did on google lead me mainly to dead links.

Thanks

**Comment by Austinb** [comment]
Need current server protocol docs.  Once available please reopen this issue.
