### ISSUE TITLE
Ventrilo Server appears offline half of the time

### ISSUE THREAD

**Issue by stephen304** [Austinb/GameQ#94]
Hi! Me again...
Here is a status page I am working on: http://status.stephen3.com/

If you watch the ajax requests, as well as the page, you will see that frequently it will show up as offline. The script is running on the same machine as my vent server, as you can see with the 127 loopback address. I have no clue what the issue is, but it's really annoying because it looks like my server is going up and down all the time.

Any ideas?

**Comment by Austinb** [comment]
Are you using any kind of caching mechanism or is the server being queried every time the page loads?

I believe ventrilo servers have some kind of anti-dos mechanism so if you query the server multiple times in a short period of time the server will begin to ignore requests for a period of time.  Does this sound like the behavior you are seeing?

**Comment by Austinb** [comment]
Any update on this for you? If you have any more issues or have questions please feel free to reopen this issue.
