### ISSUE TITLE
Minecraft Doesnt List Player List Anymore

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#95]
Nothing changed on my server or other servers, but the player list no longer displays (when theres players in the server).

I'm testing against: 209.44.100.12:25565

**Comment by Austinb** [comment]
Hmm interesting.  I tested that server and it said 0 players of 100 max.  I tested 198.12.14.132:25565 and 199.189.87.51:25565 (from gametracker) and they both show players and the players list.  Please let me know when the server has players and I will take a look again to see if it is some kind of weird return or something else going on.

**Comment by Ruok2bu** [comment]
I'll connect to the server right now and stay connected all night.

**Comment by Austinb** [comment]
I just checked it and it shows 1 player of 100 max.  I assume it is you.  Here is the output: (note this is not normalized)

``` php
Array
(
    [209.44.100.12:25565] => Array
        (
            [hostname] => Â§6*For The Win* (Whitelisting Disabled)
            [gametype] => SMP
            [game_id] => MINECRAFT
            [version] => 1.4.7
            [plugins] => CraftBukkit on Bukkit 1.4.7-R0.1
            [map] => world
            [numplayers] => 1
            [maxplayers] => 100
            [hostport] => 25565
            [hostip] => mc.ctpftw.com
            [players] => Array
                (
                    [0] => Array
                        (
                            [player] => PAL_18
                        )

                )

            [gq_online] => 1
            [gq_address] => 209.44.100.12
            [gq_port] => 25565
            [gq_protocol] => gamespy3
            [gq_type] => minecraft
            [gq_transport] => udp
        )

)

```

**Comment by Ruok2bu** [comment]
Ah, odd.  Whenever i query it or any other minecraft server, the player list is empty.  Even if there's players connected.

Any idea why the player list never displays?  I doubt its a port issue as i tested from 2 different computers in 2 different locations.

**Comment by Austinb** [comment]
I would recommend checking out a fresh version from the repo and using that with no changes.  Perhaps you changed something in the code and did not realize it?  Also git status can show changes that have been made on your local repo and not added yet.

**Comment by Ruok2bu** [comment]
Yup, that was it.  I updated again and im able to see the player lists again.  I guess the last release had something broken.

Thanks for the help anyways ;)
