### ISSUE TITLE
Multi-thread data request?

### ISSUE THREAD

**Issue by marcoekb** [Austinb/GameQ#97]
How i can to send request to all my servers at same time? Or i'ts impossible?

**Comment by Austinb** [comment]
The only way to send data to all servers at the same time (well as close as possible) is to run multiple scripts in parallel.  The script iterates over each server and does all the necessary work and sends out the requests but this is one at a time (but fairly fast except for gamespy3). 

The main issue is you have to create a socket for each server and I do not know of a way to do this in PHP from a single script. I guess this could be done by forking but that brings in a whole new set of issues.  If anyone has any other thoughts please respond.
