### ISSUE TITLE
minecraft hostname

### ISSUE THREAD

**Issue by zeagon** [Austinb/GameQ#99]
Iam not sure if this is rather uncommon, but on a site where i query minecraft stats iam always getting the following response for hostname on several servers
§eWWW.§bMCRAFT§aSPLEEF§e.COM

I suppose this is some color codes or so, no real experience there. Issue is i cant seem to strip them our using preg_replace or str_replace. Also tried iconv before, but illegal character detected.

Am i missing something or this a bug or supposed to be?

reproduce
5.9.152.119:25565

running version 1.5

**Comment by Kurounin** [comment]
I use the following regex to remove any invalid utf-8 characters from the hostname:

``` php
$strRegex = <<<'END'
/
  (
    (?: [\x00-\x7F]                 # single-byte sequences   0xxxxxxx
    |   [\xC0-\xDF][\x80-\xBF]      # double-byte sequences   110xxxxx 10xxxxxx
    |   [\xE0-\xEF][\x80-\xBF]{2}   # triple-byte sequences   1110xxxx 10xxxxxx * 2
    |   [\xF0-\xF7][\x80-\xBF]{3}   # quadruple-byte sequence 11110xxx 10xxxxxx * 3 
    ){1,100}                        # ...one or more times
  )
| .                                 # anything else
/x
END;

$strHostname = preg_replace($strRegex, '$1', $arrServiceInfo['gq_hostname']);
```

Could you try it and see if it works?

**Comment by zeagon** [comment]
Ahh thats how it is done, thx for the code, works perfectly ripping that char out, though had to remove the heredocs.

Which of the 4 line sequences is taking the § char out? Will need to implement a lookahead or so to take care of the b in §b as well.
And are other invalid chars structured like this? or is this pretty much the only one appearing with a second character after it?

Could these invalid chars come up in the map name as well? From what ive seen till now, no.

In case you know :)

**Comment by Kurounin** [comment]
That regex was borrowed from http://stackoverflow.com/questions/1401317/remove-non-utf8-characters-from-string
As it states there, the regex searches for UTF-8 sequences, and captures those into group 1. It also matches single bytes that could not be identified as part of a UTF-8 sequence, but does not capture those. Replacement is whatever was captured into group 1. This effectively removes all invalid bytes.

It's not minecraft that uses odd signs (i had the problem with the hostname of a SAMP server). The data sent by the server that identifies the hostname contains invalid bytes that do not define any characters from UTF-8 character map, so those are converted to other symbols. This usually happens because the servers don't use UTF-8 encoding, but ISO 8859-1 (Latin 1).

**Comment by zeagon** [comment]
Oh i see, thats some good info. Got tonight a server to test with, so maybe i can come up with a fix in the core. Doubt it, but worth a try. For this project i defenetly need the right charset, so its worth a try. As i think Austin didnt planned any deep utf support 
Remember this once was mentioned by another user and i replied practially the same as you ( without code though  :P ). Now i see what his issue were like

**Comment by Austinb** [comment]
I would rather add a utf8 only as a filter that way each user can choose to use it or not.  Since the regex can be done over an array with ease and little performance penalty.  The non-utf8 characters seems to be specific to certain servers/games.

Any thoughts?

On a side note:  Thanks for the info Wiseon3, much appreciated,

**Comment by zeagon** [comment]
Indeed a filter would be a good idea and let it run only if the charset is actually wrong, this would avoid the regex array to run on servers where it dont need to.

I might be wrong, but just shooting some ideas here, would mb functions do any good? if wrong charset set the intenal encoding to xxx. Not sure if that works on sockets at all though

**Comment by Austinb** [comment]
The multibyte functions could be useful but I try to limit the number of required modules (i.e. bzip2) that need to be installed for GameQ to run. Its possible this could be added as part of a filter and it would need mb_\* functions. But you are right you would have to set the proper character set for the base one you want to use.  Also I am not sure on the accuracy of multibyte functions auto-finding the character set being used.

**Comment by zeagon** [comment]
I normally use iconv('', 'UTF-8', $var) to convert everything to utf8. Using that in my own project to convert language locales and its working good, even with russian chars, though then again while most have iconv i bet, its like you said another requirement then

This wasnt working though in the output, like i stated in first post, but thats because of the byte values and no real characters, hence the illegal characters. Not sure how it would react in a filter, but i guess the same

**Comment by Kurounin** [comment]
A filter definitely sounds good. Don't know if you could accurately identify the charset of the hostname, but applying the provided regex even to utf-8 encoded hostnames shouldn't do any damage.

**Comment by zeagon** [comment]
Specific minecraft filter using the regex from above might not be bad, ill try myself on it.
All the color codes possible in the servername must be stripped http://www.minecraftwiki.net/wiki/Classic_server_protocol

**Comment by zeagon** [comment]
Just in case someone is quicker than me, which is likely :) here is the updated code to strip all color, underline, bold codes etc from hostname

``` php
            $strRegex = '/(
                            (?:   [\x00-\x7F]                 # single-byte sequences   0xxxxxxx
                              |   [\xC0-\xDF][\x80-\xBF]      # double-byte sequences   110xxxxx 10xxxxxx
                              |   [\xE0-\xEF][\x80-\xBF]{2}   # triple-byte sequences   1110xxxx 10xxxxxx * 2
                              |   [\xF0-\xF7][\x80-\xBF]{3}   # quadruple-byte sequence 11110xxx 10xxxxxx * 3 
                            ){1,100}                          # ...one or more times
                          )
                          | .[0-9|a-f|cX|nY|nX|cY|k-o|r]      # anything else
                        /x';
```

**Comment by Supryk** [comment]
Where can I add the code to remove these strange characters from hostname

lokk add link http://polish-zone.pl/nosound/status/status.php?game=minecraft&ip=178.255.41.211:25565

i add the real hostname is [PL] [RzeZnia.eu] SkyBlock SHOP VIP

**Comment by Austinb** [comment]
Actually after having rechecked the PHP manual it appears iconv is part of the core and is enabled by default.  I will try to put together a fast filter to help with removing non utf8 characters from pretty much any entity returned.
